### ISSUE TITLE
Ads showing up after day or two, have to keep restarting phone.

### ISSUE THREAD

**Issue by gpioneer** [AdguardTeam/AdguardForAndroid#1017]
Hi, it started all of a sudden maybe a few weeks ago. AG used to work great, but now ads start showing, and have to restart phone (stopping protection and starting does't help, neither does closing AG and reopening). I have tried clearing AG cache, but problem still persits. I've sent bug report (userid 1453689) with ads recorded today at 11AM-11:05AM) on Relay for Reddit and Night Screen (where ads normally blocked). Late last night was blocking, then when I woke up today ads are showing. Seems to only break app ads, believe website ads are still blocked

Once phone is restarted, AG works great again for a day or two.

Set up by VPN proxy with normal filters, including experimental.

**Comment by ameshkov** [comment]
Btw, have you changed anything in the apps management section?

**Comment by ameshkov** [comment]
I've just taken a look at the screenshots in the ticket, looks like either Google ads or Facebook ads, let me think a bit about it.

Btw, sorry for the support service answers, this icon thing was obviously unrelated.

**Comment by ameshkov** [comment]
Regarding the ads, I've taken a look at the requests log.

The only thing I see there is a few Google ad requests blocked and nothing more. All these requests are originated from the apps (relay and night mode), which is unusual.

You see, Google ads metadata is loaded by a separate app (Google Play services or Google Services Framework). This metadata is then used by the apps.

That's why I am asking about changes to the Apps management section. Could it be that you've disabled ad blocking for google system apps?

**Comment by gpioneer** [comment]
. I purchased the ad free version of night screen and haven't used relay
for reddit in a bit, so not sure if it's resolved. Currently Google play
framework is disabled in adgaurd, but I think I just made that change a few
days ago. Is it safe to enable it for filtering then? Didn't know it was
used to drive ads and I saw adguard was blocking much traffic from it which
I thought was unnecessary, heh.

**Comment by ameshkov** [comment]
> Is it safe to enable it for filtering then? Didn't know it was
used to drive ads and I saw adguard was blocking much traffic from it which
I thought was unnecessary, heh.

Yeah, it is safe.
