### ISSUE TITLE
ooniprobe app filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1048]
Please let AdGuard automatically whitelist the new Tor project "[ooniprobe](https://play.google.com/store/apps/details?id=org.openobservatory.ooniprobe&hl=en)" by default, which is a new app and project designed to test the internet for censorship and statistical purposes. I feel AdGuard gets in that way for those types of things.

623633

**Comment by TPS** [comment]
@evgeniy-ADG Thanks for pointing this app out to me.  Fascinating!

However, since I don't do any of the HTTPS filtering, I don't observe any effects from AG on these tests, other than maybe #975, which probably can be mitigated by setting a higher timeout in ooniprobe settings.

At most, wouldn't HTTPS whitelist be enough, instead of complete whitelisting, @evgeniy-ADG?

**Comment by ameshkov** [comment]
@evgeniy-ADG it can be whitelisted manually in the apps management section. I think AG shouldn't mess with it (unless it probes some phish/malware domains).
