### ISSUE TITLE
[Feature request] DNSCrypt Support

### ISSUE THREAD

**Issue by dylanwinn** [AdguardTeam/AdguardForAndroid#1053]
There are a few different DNSCrypt clients for Android, but the ones that do not require root work the same way Adguard does — by creating a local VPN. This makes them incompatible with Adguard. Since Adguard already allows you to specify your own normal DNS servers, it would be nice if it supported DNSCrypt servers too.

**Comment by vozersky** [comment]
@dylanwinn 
You can still use Adguard in local proxy filtering mode though.

**Comment by dylanwinn** [comment]
Yes but unfortunately local proxy filtering mode doesn't have full functionality on non-rooted devices. If I had a rooted device I could just run the DNSCrypt daemon and set my DNS server to 127.0.0.1, but then I wouldn't even need Adguard, I could just use AdAway.

**Comment by vozersky** [comment]
@dylanwinn 
Fair enough, proxy mode is not that effective. 

But I didn't get your point about using AdAway instead of Adguard app. AdAway filtering quality can only be compared to using Adguard DNS, but no more than that. 

DNSCrypt is a great thing and we would consider supporting it a little bit later, sure. Unfortunately, devs are too busy atm.

**Comment by ameshkov** [comment]
@vozersky I guess we still can plan DNSCrypt support for a v4.0 milestone.

**Comment by TPS** [comment]
Would be especially good to work end-to-end w/ [AGDNS](https://github.com/AdguardTeam/AdguardDNS/issues/2). ☺

**Comment by ameshkov** [comment]
Dup of #1134, will arrive in v2.10
