### ISSUE TITLE
Use locale-specific number format on the main screen

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1117]
It would be better to have it like 364.500 rather than how it's now:

![image](https://cloud.githubusercontent.com/assets/15856304/24145626/b048bf52-0e3a-11e7-8a65-5fcc645d0a7e.png)

**Comment by TPS** [comment]
Umm, be quite careful with this: different languages/dialects/regions use very different schemes for # division.  Please use [Android's own `NumberFormat`](https://developer.android.com/reference/java/text/NumberFormat.html) or equivalent (instead of making your own) in ___all___ # fields throughout UI.

**Comment by ameshkov** [comment]
Yeah, we use it already except main view:)

**Comment by ameshkov** [comment]
Done
