### ISSUE TITLE
Firewall profiles

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#1239]
I'd love to see a feature that lets you set profiles for the firewall, so if you connect to you home wlan it enables wifi for all apps and if you use some hotspot it only allows specific apps to use wifi

**Comment by vozersky** [comment]
It will also be nice to have profiles for sets of filters

**Comment by ameshkov** [comment]
Guys, I might be wrong, but somewhere there already was a feature request about user profiles, which, apparently, covers the firewall profiles as well.

**Comment by sam20e** [comment]
Following this, we really need this feature :)

One thing I really love about adguard - your app management system where i can restrict data/wifi access to individual apps.

I'd really like to see different set of firewall/app-management rules at least 3 pre-defined rules i can switch whenever i need.

Let me give you an example - Last week, i had to travel overseas. Unfortunately I had to use my data roaming feature. So you all know data roaming is very expensive so i cannot let facebook/instagram and few other apps to use any data (normally i dont restrict these apps when im using local data/wifi). So i literally had to open app management and update these apps one by one to restrict data access. I had to do it for like 10-15 apps.

Lets say if i can create and save different type of app management list. for example 1) normal profile 2) roaming profile 3) sleep mode and when im using data roaming i can simply load the roaming profile and that will restrict data access to facebook and any other apps i;ve selected. that way i dont have to go one by one and change app settings.

I'm using unrooted device. so i found this 1-2 other apps in playstore which can block an app running for a predefined period but that requires a VPN profile. so its impossible for me to run that app along side adguard. Since adguard is already utilizing a VPN mode, this feature will be a GREAT addition. I'm 100% sure your users will appreciate this feature and I dont see many apps which offers this feature.

Also as @Bluscream stated, we can even create profiles like Home, Office and restrict certain apps. 

Please prioritize this request :)

**Comment by sam20e** [comment]
@ameshkov the only reason i opened a new request because as you can see this is a very old request. Nearly 2 years old.. Adguard is a great product, so please consider this request.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
