### ISSUE TITLE
Clarify the Filtering Method screen descriptions

### ISSUE THREAD

**Issue by jawz101** [AdguardTeam/AdguardForAndroid#1332]
High-quality: filter everything
High-speed: filter everything except page content
Simplified: only filter ad requests

I guess I'd need a more technical description to understand what these actually mean.

Are any of them implying cosmetic filtering?  Meaning the content is still downloaded but is hidden from view?  As in it's purely cosmetic but from a privacy or download resources point of view- there is no benefit from a privacy/security/bandwidth-savings viewpoint.  I'm thinking this is what high-quality implies but I have no idea.  If that's the premise, high-speed _could_ still remove page content but _some_ content _could_ get passed it.

I don't even know why you'd need 3 options when 2 could probably cover most users' opinions on what is preferable to block.  I couldn't see anyone ever pick simplified if, I'm assuming, it just serves as a DNS block.

**Comment by ameshkov** [comment]
* `High-quality` -- able to use all sorts of filtering rules from the documentation: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

* `High-speed` -- able to use everything save for "HTML filtering rules" -- https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#html-filtering-rules

* `Simplified` -- able to use just the basic filtering rules

> Are any of them implying cosmetic filtering?

`Simplified` does not use cosmetic filtering rules, others do.

> I don't even know why you'd need 3 options when 2 could probably cover most users' opinions on what is preferable to block. I couldn't see anyone ever pick simplified if, I'm assuming, it just serves as a DNS block.

High-quality is what we'd prefer to have, but it appears to be too slow even on high-end devices as it requires full page code parsing. That's why we came up with `high-speed`.

"Simplified" is rarely used, it is supposed to used on very slow devices, something like 512mb ram cheap phones.

**Comment by jawz101** [comment]
Thank you!

**Comment by jawz101** [comment]
So is simplified equivalent to DNS filtering or still something more substantial than that?

**Comment by ameshkov** [comment]
> So is simplified equivalent to DNS filtering or still something more substantial than that?

No, AG still blocks requests as usual (not just on the DNS-level).

For instance:

* `https://example.org/banner` -- cannot be blocked on DNS-level without blocking the whole `example.org`
