### ISSUE TITLE
The ability to modify HTTP headers and connect to proxy.googlezip.net

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1405]
Could you add an option to modify http headers and connect to
proxy.googlezip.net? By doing so, users will be able to use google
data saver with their favorite browser other than chrome.

ID of the requester: 946002

**Comment by ameshkov** [comment]
More info about using data compression proxy:
https://superuser.com/questions/945924/how-do-i-use-the-google-data-compression-proxy-on-firefox

**Comment by TPS** [comment]
Possibly duplicates #775?

**Comment by ameshkov** [comment]
#775 is about providing our own compression service.

This one is about providing means to use Google's compression proxy. The problem with it is that we'll never add a direct option to use their proxy without their permission/consent. 

However, maybe we'll make AG customizable enough so that setting up Google's compression proxy became possible. We definitely won't do it for this single purpose, but it's useful to keep this feature in mind.
