### ISSUE TITLE
[Feature Request] Rework 'Send Feedback' screen

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#143]
Currently it only allows to see three lines of entered text at one time. Also with tablet's vetical orientaion a lot of empty space is left.

WER-881-88139 - original requester

**Comment by TPS** [comment]
If you're doing this anyway.…  I suppose you all have the e-mail field setup so it does some sort of validation on the e-mail entered?  Is there a flag you can toggle for that field so that it allows the keyboard auto-correct?  My e-mail's a whole lot easier to type accurately when I let Android do it.… :wink:

**Comment by ameshkov** [comment]
Duplicate
