### ISSUE TITLE
[Enhancement Request] Changes to battery stats screen

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1475]
First off I just want to say the new battery screen is awesome. But I think it could be better / more useful. IMO the time frame should match that of Android's stats.

If I check my battery in settings, it says "since last full charge." But AdGuard is the last 24 hours. This creates a disconnect when trying to compare and see actual usage at any given time, especially if the phone is charged during those 24 hours.

I'm not sure what the right solution is - configurability? defaulting to since last charge?

**Comment by ameshkov** [comment]
> IMO the time frame should match that of Android's stats.

That's quite problematic, it's not clear when Android decides to discard previous stats. It's not always the "full charge" event.

1. `since last full charge` -- it may never happen (in theory).
2. It may require additional permissions (not sure about it, though)

As a compromise, we can mark the last charge event on the graph.

**Comment by vozersky** [comment]
merged into #3378
