### ISSUE TITLE
Add a button to read the current changelog

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1487]
Add a button to view the changelog not only while on updating.

**Comment by carlylemiii** [comment]
This was my request :-)

Doesn't even have to be a button. It could just be a link in the About AdGuard section.

**Comment by ameshkov** [comment]
Something like "Versions History"?

**Comment by carlylemiii** [comment]
Yep! Just an easy-to-access way of getting at it in-app instead of doing a Google search for the changelog (which is even a little trickier for beta releases).

Another idea would be in the About AdGuard section, where it says Version 2.10.106, make the 2.10.106 a hyperlink to the changelog. Whatever you all determine is best; I just think it would be nice to have somewhere.

**Comment by ameshkov** [comment]
It makes perfect sense, thank you!

**Comment by vozersky** [comment]
merged into #3378
