### ISSUE TITLE
Automatic proxy (with root) is starting very slowly

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1516]
### Steps to reproduce
1. Set filtering mode to proxy auto (with root)
2. Try to start protection
3. It will start about 5-6 seconds on decent phone with Snapdragon 835
4. Cry

### Expected behavior
The protection should start in about 1-2 seconds tops

### Actual behavior
It starts in about 5-6 seconds, because _there is a delay 50ms between each iptables command_.

### Customer ID 
Me

### Your environment
* Adguard version: 2.10.*
* Adguard filtering mode: Proxy auto
* Device model: Sony Xperia XZ
* Operating system and version: Android 7.1
* Rooted or not?  Of course
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by carlylemiii** [comment]
I always hesitate whether issues should be written up as new, but as part of this fix, please investigate the latest Magisk build with Android 8.0. Not sure if it's AdGuard or Magisk's fault, but automatic configuration takes about five *minutes* with Magisk instead of SuperSU, and it totally locks AdGuard up:

![screenshot_20171006-185234](https://user-images.githubusercontent.com/29067983/31302660-28f82c46-aac9-11e7-8708-68c833947dc5.png)

![screenshot_20171006-185244](https://user-images.githubusercontent.com/29067983/31302662-2c12f2b2-aac9-11e7-9dd1-585cd34e3b19.png)

[adguard_logs_2.10.108_0610_1855.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1364143/adguard_logs_2.10.108_0610_1855.zip)

I suspect more and more people will migrate to Magisk now with Chainfire's official retirement from SuperSU, so please don't brush off! (Not that you guys would...the development and response from dev for this app is truly outstanding.)

**Comment by Revertron** [comment]
I am using Magisk on my phone with Android 7.1.1 and it is working as it should, nothing like that.
I will go through your logs now...

**Comment by Revertron** [comment]
I see interesting timings in your log:
```
18:51:13.770 [pool-2-thread-26] INFO  com.adguard.filter.proxy.o - Creating server listening to ::/:::1102
18:51:13.770 [pool-2-thread-26] INFO  com.adguard.filter.proxy.o - Server has been created successfully
18:51:13.771 [pool-2-thread-26] INFO  com.adguard.filter.proxy.a - Proxy is configured to MITM connections
18:51:13.771 [pool-2-thread-26] INFO  com.adguard.filter.proxy.a - Listening to ::/:::1102
18:51:13.771 [pool-2-thread-26] INFO  com.adguard.filter.proxy.a - HTTP proxy server has been created successfully
18:53:53.075 [pool-2-thread-26] INFO  com.adguard.android.g.c - Using system iptables /system/bin/ip6tables
18:53:53.991 [pool-2-thread-26] INFO  com.adguard.android.g.c - Using system iptables /system/bin/iptables
18:53:53.991 [pool-2-thread-26] INFO  com.adguard.android.g.c - executeShellCommands:
chmod 0755 /data/user/0/com.adguard.android/files/create_transparent_socket
/data/user/0/com.adguard.android/files/create_transparent_socket -p /data/user/0/com.adguard.android/cache/socket_receiver -i lo -s untrusted_app_25 -r
```
In particular these two lines:
```
18:51:13.771 [pool-2-thread-26] INFO  com.adguard.filter.proxy.a - HTTP proxy server has been created successfully
18:53:53.075 [pool-2-thread-26] INFO  com.adguard.android.g.c - Using system iptables /system/bin/ip6tables
```
There is nothing between them, but there is a gap of 2 minutes and 40 seconds...

**Comment by sfionov** [comment]
Seems that they may have done something with the Magisk bug for that was previous workaround, and now SU program fails to communicate with kernel SU daemon after changing SELinux context, so it hangs.

**Comment by ameshkov** [comment]
Argh

**Comment by ameshkov** [comment]
@sfionov any idea what to do with it?

**Comment by sfionov** [comment]
Depends on that what they changed. If they fixed a bug for that workaround was, we may switch off the workaround for magisk >= 14.2. Otherwise, additional research is needed.

**Comment by ameshkov** [comment]
@sfionov let's check it somehow

**Comment by Revertron** [comment]
The main task in this issue is fixed.

**Comment by ameshkov** [comment]
Re-check it please, I see the same complaint with .150:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=66209518
