### ISSUE TITLE
Fix certificate state styles in HTTPS filtering settings

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1551]
By @ameshkov:
**We should discuss it before implementing anything**

First of all, we have different text sizes and one text color in status texts. This is looking like a bug, very weird.
![1](https://user-images.githubusercontent.com/105154/31821898-f62b14de-b5a6-11e7-806c-1d2bd119c7e1.png)
If we change the first text's color to a ordinary header color, it looks better. But it mimics ordinary settings item that we can press:
![2](https://user-images.githubusercontent.com/105154/31822014-67603a1c-b5a7-11e7-8477-4812050d7997.png)
Another approach is to show texts as one. It will become like an explanation of section at the top:
![3](https://user-images.githubusercontent.com/105154/31822132-e3411ab6-b5a7-11e7-8a5c-b8ac8faccf82.png)
We need to think about it more time...

**Comment by ameshkov** [comment]
We can use the "regular color title" + "gray help text" if we make this item "selectable". The question is what possible action will be caused by the tap?

My idea is that tap can bring up a menu with all the possible certificates actions: "Alternative install", "Install into Firefox", etc. Maybe even moving certificate to the system storage (whether we decide to finally make it a feature).

**Comment by Revertron** [comment]
Or we can just recheck it's status :)

**Comment by ameshkov** [comment]
After https://github.com/AdguardTeam/AdguardForAndroid/issues/1698 is implemented it will have the regular+gray  style
