### ISSUE TITLE
"Protection" button misbehaves

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1556]
Issue description:
https://forum.xda-developers.com/showpost.php?p=74205641&postcount=2782

Logs:
https://forum.xda-developers.com/showpost.php?p=74232238&postcount=2799

I don't see `ServiceManager handle status event` records in the log file at all, and this is really weird.

It's possible, that it also causes this:
https://forum.xda-developers.com/showpost.php?p=74235089&postcount=2802

**Comment by Revertron** [comment]
The problem is with AOT of the Android 7.x. It's optimization step is removing "unused" methods that we implement from listeners.
If we call this method in onCreate() once with dummy data (or status in our case with ServiceManager) the method is working further normally, as it should.
The implementation of otto Bus is very sophisticated to AOT of Android, it can not determine that our methods of listeners are used.

**Comment by Revertron** [comment]
The tests show that if we additionally annotate these methods by @Keep they are not removed by AOT.
