### ISSUE TITLE
Please put the strings of DNSCRYPT servers' descriptions on oneskyapp.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1574]
@ameshkov
@aalpatkina

Hi,
I found that all of DNSCRYPT servers' descriptions are not translated.
![Image of Yaktocat](https://i.imgur.com/U0Iajkb.png)

May you put the strings of DNSCRYPT servers' descriptions on oneskyapp?

And then...
Did you finish thinking about how to structure Miscellaneous projects?
Traditional Chinese translations for filters in the various platforms (Windows, Mac, Android and iOS).
https://github.com/AdguardTeam/AdguardForiOS/issues/500

The quality of filters' Traditional Chinese translation is incomplete and uneven.
I want to let them be regular.

Thanks.

**Comment by aalpatkina** [comment]
@lancelot-moon 

Hello,

These strings will not be uploaded on OneSky app, because we may not localize the DNSCrypt descriptions. 

The descriptions are taken from - https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

As about Miscellaneous projects we are still working on it.

Thank you.
