### ISSUE TITLE
AG Establishes connection to Phishing Sites even though they are blocked

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardForAndroid#1609]
Phishing and malware protection is enabled under Browsing Security. Filters are updated & Filtering Log is enabled to show the connections/requests.

An attempt to visiting a phishing site (which is added to the phishing & malware filters) is blocked by AdGuard. However, looking at the Filtering Log shows some requests/connections to the phishing site. Can you explain why? Ideally, when the site is blocked, there should not be a single request/outgoing connection to the site.

The filter list should be first checked locally and if a match is found, should block the website without any single connection/request to the site. Correct me if I am wrong.

### Steps to reproduce

1. Open the website "megamovie.pw" (which is a fake movie streaming site or any other site that is in the phishing list) in a web browser (Ex: Firefox). AG tries to load the page and after a split second, shows the warning message.
2. Check the Filtering Log and you will see connections/requests to the site (see screenshot)

Screenshot 1: [https://forum.adguard.com/index.php?attachments/screenshot_20171117231046-jpg.11778/](url)

Screenshot 2: https://forum.adguard.com/index.php?attachments/screenshot_20171117231115-jpg.11779/

### Expected behavior
When a website (that is added to the list of phishing sites) is attempted to open, the website should be blocked without even a single connection/request going to the phishing/scam site.

### Actual behavior
When a website (that is added to the list of phishing sites) is attempted to open, one can actually see few connections/requests to the phishing site and also sometimes able to the see the site contents in the browser for a split second and then the warning message appears.

### Your environment

* Adguard version: 2.10.175
* Adguard filtering mode: VPN
* Device model: Xiaomi Redmi Note 3
* Operating system and version: MIUI Global 8.5 (Stable) [Android Version: 6.0.1 MMB29M]
* Rooted or not? : Not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? N/A

**Comment by ameshkov** [comment]
@clementine123 yes, and that's by design as AG for Android uses "light" version of the safebrowsing protocol (unlike Win version for instance).

There're two possible states for a security information: cached and not cached. When you open a website for the first time, AG asynchronously sends prefix of the domain name hash to the web service. We do it asynchronously to now slow down the page load. Once the response is obtained, if the domain is blacklisted, AG stops loading and shows the access denied page. The response is cached and the next time AG blocks requests to that domain synchronously.

The only way to solve properly this is to switch to the "heavy" safebrowsing protocol. It means that AG should download the prefixes database (a couple of MB) and update it periodically. That's possible and we'll do it in course of the products transition to the new core engine.

**Comment by clementine123** [comment]
Ok, thanks @ameshkov . Just like other filters are updated, I believe even this one can be included as a local filter and can be updated. I was surprised to see many phishing sites that even opened for a brief moment and I was able to see the page contents and that's why was worried. Please include this as a feature request for future versions. Thanks.

**Comment by ameshkov** [comment]
> as a local filter and can be updated

It's too huge to be a local filter:(

**Comment by ameshkov** [comment]
Will be solved in due course, closing this question

**Comment by Nzzyme** [comment]
I just happened to stumble upon this domain which is malicious and AG blocks it by showing the warning page however offering the file for download

12273.url.7wkw.com

This needs to be fixed so that when a malicious domain is detected, it should not even connect to the site, let alone download a file from their server.

**Comment by vozersky** [comment]
@Nzzyme thanks for reporting it!

**Comment by Nzzyme** [comment]
> Will be solved in due course, closing this question

I was wondering as to when would this be solved?

**Comment by ameshkov** [comment]
> I was wondering as to when would this be solved?

Sorry that it takes so long, we prioritized DNS filtering over this for now.
