### ISSUE TITLE
Reconfigure auto-proxy on network state change

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1630]
This will solve quite a lot of issues right away.

I might've been created such an issue already (self-note -- review all the issues in the Android repo and close redundant).

**Comment by Revertron** [comment]
Review ready.
Btw, I did a new system of determining "true" network change. We need it like a workaround for (almost every) broken system, which sends 2-3 exact same broadcasts about network change. With this patch we will be able to just one reconnect cycle instead of 2-3 cycles.
P.S.: We have a system to throttle reconnections, but it doesn't always help.

**Comment by Revertron** [comment]
Merged.
