### ISSUE TITLE
Integrate AdGuard Assistant into the Android app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1696]
We've got it on iOS (in a simplified form) allowing to select & block any element on a page, so it'd doable. On Android, the only question is how to draw the Assistant so that it was usable and not too annoying.

I like how Samsung Internet's helper looks like:
https://uploads.adguard.com/up04_dfkun_Samsung-Internet-Review-01.jpg_43202220_.png

It's draggable, not too annoying, easy to remove. We should simply use the same style for the mobile Assistant.

**Comment by BlazDT** [comment]
Any updates to this request?

**Comment by artemiv4nov** [comment]
@BlazDT , Hi!
This task is in line for execution.

**Comment by ameshkov** [comment]
This is actually a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2163

**Comment by BlazDT** [comment]
Since this ticket has ID 1696 which is less than the other, actually the opposite.

**Comment by ameshkov** [comment]
@BlazDT well yeah, you're right:) But the newer ticket contains the proper explanation of how we should try to implement this

**Comment by Neon329** [comment]
@ameshkov Do you have any UI mockups and the UX-flow available for this feature so that I can give feedback on the UX if needed? Drawing elements on the webpage on a mobile device doesn't seem like a good idea to me (like the Samsung Internet browser example in the https://github.com/AdguardTeam/AdguardForAndroid/issues/1696#issue-288828882). But again I don't have any better ideas. May be if I see it visually perhaps I may be able to give some suggestions.

**Comment by ameshkov** [comment]
Well, I explained it in the new task: https://github.com/AdguardTeam/AdguardForAndroid/issues/2163

Using the "Sharing Provider" we could avoid drawing anything. You just share any link to AG, AG shows a dialog with a couple of options, for instance disabling/enabling protection for a website, reporting a website, etc.

**Comment by Neon329** [comment]
Oh, sorry. I didn't notice that this issue is already closed. I saw the proposal at #2163, It's a great solution since it completely avoids drawing anything on the webpage. Sorry for the interpretation.
