### ISSUE TITLE
AdGuard for Android blocks connections via Chromecast

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1750]
Tested via Google Photos app (https://play.google.com/store/apps/details?id=com.google.android.apps.photos)

### Steps to reproduce
1. Enable AdGuard;
2. Attempt to transfer anything via Chromecast;
3. Nothing happens.
4. Settings: Android is configured to have AdGuard local VPN enabled all the time; Block connections without VPN = enabled (also an Android settings, as I would see)

### Expected behavior
Files should be transferable over Chromecast

### Actual behavior
Files are not transferable over Chromecast

### Customer ID, logs and screenshots
1453131

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: Google Pixel XL
* Operating system and version: Android 8.1
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None found

**Comment by ameshkov** [comment]
> Settings: Android is configured to have AdGuard local VPN enabled all the time; Block connections without VPN = enabled (also an Android settings, as I would see)

This is what's causing the issue.

AdGuard does not filter LAN by default. But with this setting set to true, all the LAN connections are effectively blocked.

In order to fix that either disable that option or let AdGuard filter LAN (settings - advanced - low-level - pref.vpn.ipv4.routes.excluded -> clear the list)
