### ISSUE TITLE
Allow excluding apps/networks from using an outbound proxy

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1776]
Just like it works now with the HTTPS filtering in the Apps management settings.

### Expected behavior

Users can tell AdGuard not to proxify specific apps through an outbound proxy

### Actual behavior

All traffic goes to a proxy

**Comment by PerezChilli** [comment]
Confirmed. Waiting for a feature.

**Comment by ministr91** [comment]
неужели так сложно реализовать это?
@ameshkov поставь отметку, чтобы не забыть

**Comment by TPS** [comment]
@Eugene-Savenko @ameshkov I would like to renew this request.  Some apps don't play well w/ external proxies, especially Tor/Orbot.

**Comment by lancelot-moon** [comment]
@ameshkov 

Exclusive?
No, should be "inclusive".
https://github.com/AdguardTeam/AdguardForAndroid/issues/3043

I only wish several specific apps to use the outbound proxy, but most other apps won't.
Otherwise, please give "inclusive/exclusive" option.
Have a reference to Windscribe Android app.
https://play.google.com/store/apps/details?id=com.windscribe.vpn
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ZiHiqOI.jpg)
</details><br/>

Thanks.

**Comment by kovalovk** [comment]
Hello, there is one request, we have some sites blocked. It would be interesting to add the option to forward some sites through a proxy or the like, so that you can enter blocked sites there and select a proxy server, and all other sites go without a proxy (directly)

Namely, sending only certain sites through a proxy

There’s even an extension (you can get a list of servers from there)

it has already been recalled and is not being updated, but it WORKS !!!

Please make selective proxying.

**Comment by AnthonyBe** [comment]
Tesla's v4 app for Android will not even display login screen while VPN is connected. Requires VPN to be disconnected. Given I use AG and AG VPN, right now, I need to enable AG bypass for Tesla app.

**Comment by TPS** [comment]
Tesla uses a proxied/VPNed network _inside_ the vehicle?  Or would simply unblocking something do it?

**Comment by Nzzyme** [comment]
A much needed functionality. I would like to be able to use the main AdGuard app along with the VPN app and have the ability to only include some apps to use the VPN connection.

**Comment by Samuel12321** [comment]
This is needed as it breaks support for the tesla app

**Comment by Samuel12321** [comment]
> Tesla's v4 app for Android will not even display login screen while VPN is connected. Requires VPN to be disconnected. Given I use AG and AG VPN, right now, I need to enable AG bypass for Tesla app.
> 
> Would love to proxy bypass switch in AG app management.

The problem can be solved by disabling filtering for the Tesla app in the apps management settings.

**Comment by artemiv4nov** [comment]
Well, a part of the feature has already been implemented in the 4.0 version. Let's think it's done for now
