### ISSUE TITLE
[Nightly] Incorrect notification when switching to manual proxy filtering mode

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1882]
Notification remains the same

<details><summary>Expected</summary>

![screenshot_20180522-124037](https://user-images.githubusercontent.com/17472907/40355321-bf94baf4-5dbe-11e8-9357-630c02d2c730.png)

</details>

<details><summary>Actual</summary>

![screenshot_20180522-124007](https://user-images.githubusercontent.com/17472907/40355324-c0ee8b6e-5dbe-11e8-83bf-0bb5bf39ca1a.png)

</details>

**Comment by nkartyshov** [comment]
The notification works is correct. 
If you aren't set system proxy in wifi connection then shows notification about setting this in wifi, otherwise shows notification about blocked ads and trackers.
If the  filtering mode switch to the local proxy, you see notification about settings proxy for your wifi.

I cannot see problem with notification.
