### ISSUE TITLE
Compatibility with the encrypt.me app

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1922]
The [encrypt.me](https://encrypt.me/) app revokes VPN access when being launched even if you do not start its VPN. Does not happen with No Root Firewall and NetGuard apps.

### Steps to reproduce

1. Open AdGuard
2. Start the protection
3. Open the encrypt.me app

### Expected behavior

AdGuard VPN is running until you launch the encrypt.me VPN

### Actual behavior

The VPN access is instantly revoked before attempting to launch another VPN

<details><summary>Screenshot:</summary>

https://uploads.adguard.com/loa78.mp4

</details>

### Customer ID 
1403048, logs from my personal test device: https://uploads.adguard.com/3oygx.txt

### Your environment

* Adguard version: 2.12.52
* Adguard filtering mode: VPN
* Device model: HTC One
* Operating system and version: 5.0.2
* Rooted or not? no
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? none

**Comment by zebrum** [comment]
@Eugene-Savenko when you open the encrypt.me app, it sends a message to android system that its VPN is working (even if it is not yet) and AdGuard stops.

**Comment by carlylemiii** [comment]
@zebrum the other half of this issue is that even when leaving encrypt.me, AdGuard doesn't reenable itself, as it is supposed to.

**Comment by zebrum** [comment]
@carlylemiii This is not something we could fix on our side. Check with other VPN app - the same behaviour.

**Comment by carlylemiii** [comment]
Isn't AdGuard supposed to check when the VPN is done? I mean that's what the notification itself says. And @Eugene-Savenko and I did test with two other apps so I'm confused what you're saying.

**Comment by vozersky** [comment]
@carlylemiii Is there any other VPN apps like encrypt you experience the same issue with?

**Comment by carlylemiii** [comment]
@voxersky, I just installed Tunnelbear, Express VPN, NordVPN, and PIA to try things out and opening the apps didn't mess with AdGuard, just when actually enabling the VPN (could only test those first two though since I don't have subscriptions). As soon as that VPN was disabled, AdGuard was up and running again.

**Comment by vozersky** [comment]
So, you have discovered one incorrectly working app that revokes VPN access from others on launch and doesn't give the appropriate network interface back properly, and also have discovered that few other apps do work fine. I assume our Android devs could look into the problem and come up with some solution for restarting VPN after this specific app, but it seems to me that the appropriate way of handling this issue is fixing bugs in encrypt.me
