### ISSUE TITLE
Add "Enable all" and "Disable all" to User Filter selection options

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#1925]
Hi, this is a generic request and is not related to any specific Android version. Therefore, excuse me if I have not provided more information.

There is currently no option where we can select all or Uncheck all user filters.  currently one can only check or an uncheck the individual user filters. The other option would be to backup the entire User list file and then again restore later. Many users including me have several user filters and while doing testing there is requirement to uncheck all the filters in one go and later again select all to activate them.

Can you please add these two options in the menu of the user filter page:

Select All
Unselect All

Thank you.

**Comment by ameshkov** [comment]
Would it really be useful?

Wouldn't it be better to provide a switch for enabling/disabling the user filter completely?

**Comment by ameshkov** [comment]
Anyway, it's almost done already, so keeping it on v2.12 milestone.

**Comment by Nzzyme** [comment]
Yes, a switch would would be fine too. So when you say it's almost done, do you mean the switch option or the two options ( Check/uncheck all)? Thanks

**Comment by ameshkov** [comment]
Two options

**Comment by Nzzyme** [comment]
Awesome. Thank you :)

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:

1. Reinstall AdGuard
2. Go to `Settings –> User Filter`
3. Tap on menu icon

Expected result:
a. "Enable all" and "Disable all" buttons are invisible if there are no filters.
b. "Disable all" is visible and "Enable all" is invisible if all filters are enabled.
c. "Disable all" is invisible and "Enable all" is visible if all filters are disabled.
d. Otherwise both "Enable all" and "Disable all" are visible.

Expected behavior:
a. All filters becomes enabled after tap on "Enable all". Protection must be restarted
b. All filters becomes disabled after tap on "Disable all". Protection must be restarted

**Comment by admitrevskiy** [comment]
Fixed
