### ISSUE TITLE
Unblocked URL

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1953]
I found that ad banners in MoPTT.
One is the below link.
It'll redirect URL.
You have the rule, ||beap.gemini.yahoo.com^, in AdGuard Base filter.

Why is the below link not blocked?
https://beap.gemini.yahoo.com/mbclk?bv=1.0.0&es=TXINNe0GIS8cIuNqvQukHPBl327gaVkrXex3M1bf9AdsZCfg4imJ2jbIFbsybw282Y37FZ018452OAjrHfBI2XkYuhIeL9_xPw9xmyxLEgqkZjtQn3ynHlp.u_MvtKqmmEmBAtI12H7NMPuPZc0ENChJK9yfLX02y7bX5APKnMMlPafBMImWTDVtD2Nlhfi.FmAaJ2EUc4ic9f4KG8yg75ybX_PuZu1PXHHj5owDioYagz7pHrg0bZYn5bYbGKqZIbw4vBO2sryGbkI5rs3LEkbcdkS4p.Zc9OOSw4ZGGHz6Yj4uKrnxNjKnvMiRmI2lbs3BItGP5VkpgPXSe8Z27lXRI7k.kz59l82TMZIaj9nc27e3fFZegAWBtqgkMOk9sbtGfpgY9bPb.Ir_hNiGCielA1qC96ipfMEEab1BuDXcDWJZZSi1sJL5_lpGP04mInPgZ_0VbUkl.jq_ifA0Gz8IC07ihGzSbi6GxPrPg0hbgegOj_YiVwksUPqEsCx1y.WSUZickuc14ynt809lF1E1OVE_GpFKF8Gwj3pl3XNAPowhuQ--&lp=

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/yR2qngk.png)

![image](https://i.imgur.com/McmIkJr.png)

![image](https://i.imgur.com/QYcZ1kg.png)
</details><br/>

Thanks.

**Comment by lancelot-moon** [comment]
Don't mind MoPTT.
You don't understand my problem.
Why does the rule ||beap.gemini.yahoo.com^ not block that link?
We still can use browsers to open the page.

**Comment by vozersky** [comment]
> You don't understand my problem.

Good point.

>Why does the rule ||beap.gemini.yahoo.com^ not block that link?

Because the rule `||beap.gemini.yahoo.com^` blocks requests from beap.gemini.yahoo.com, not opening this page in browsers.

Looks like you want to use something like `||beap.gemini.yahoo.com^$empty,important`

Here is filtering rules [documentation](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)
