### ISSUE TITLE
Varies across devices: pref.vpn.disable.pause

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdguardTeam/AdguardForAndroid#1989]
I'm testing Adguard on several different Android versions (well done, BTW).

I noticed that ***pref.vpn.disable.pause*** is enabled on some Android versions / devices and is disabled on others.

Is this a bug, or intentional?

*Testing version 2.11.81*

**Comment by ameshkov** [comment]
Yeah, that's intentional.

On older Android versions VPN cannot run along with Hotspot, for instance, and AG pauses itself.
Also, on KitKat if VPN is not restarted from time to time, it might start misbehaving, after all, completely breaking the internet access.

The situation improved with Android 6.0, and there're almost no issues on 7+.

**Comment by Gitoffthelawn** [comment]
@ameshkov Great explanation.  Very useful details.  Thank you.
