### ISSUE TITLE
Why were some requests from doubleclick.net not blocked?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2046]
||doubleclick.net in SDN filter.
||g.doubleclick.net in both SDN filter and mobile ads filter.
The rule /pubads. is in AGuard Base filter.

Why were some requests from doubleclick.net not blocked?

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/CnsgsBx.jpg)

![image](https://i.imgur.com/jW4CA6J.jpg)
</details><br/>

Similar with my past question. But vozersky didn't clearly explain at that time.
Why can the page be opened with ||beap.gemini.yahoo.com^?
If I don't want to open the page, I need to use ||beap.gemini.yahoo.com^$empty,important.
Why?
https://github.com/AdguardTeam/AdguardForAndroid/issues/1953

Thanks.

**Comment by ameshkov** [comment]
Q: did that happen when you click on a link in that app?

It might be that both doubleclick requests were unblocked because they were used as intermediate URLs for opening a page in the main browser/app window.

$empty overrides this behavior and makes AdGuard block the request even if it's opened in a browser window.
