### ISSUE TITLE
Overflow menu that doesn't do anything

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#2087]
### Steps to reproduce

1. Use an app shortcut to launch AdGuard Assistant, then open the filtering log for one of the apps in that pop-up.
2. Use the back arrow (either system or in AdGuard, but not the X) to clear the value in the search field.
3. You're on the Filtering Log now, with no search and no trash, and the overflow menu button that exists is non-functional.

<details><summary>Screenshot:</summary>

![screenshot_20180828-165720](https://user-images.githubusercontent.com/29067983/44753430-ad80d600-aae3-11e8-93b9-e5280787cae7.png)

</details>

### Customer ID 

1403048

### Your environment

* Adguard version: 2.12.187
* Adguard filtering mode: VPN
* Device model: Pixel 2 XL
* Operating system and version: Android 9 Pie
* Rooted or not? Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by nkartyshov** [comment]
In version 3.0, this problem is not reproduced.
But fixed the filling of the search field, if a filter log is opened from the Assistant.

**Test investigation:**
1. Start protection
2. Open any website on browser
3. Open AdGuard shortcut menu
4. Click to the AdGuard Assistant
5. Click to the any list item
6. Click to the Open Filtering log

**Expected result:**
Filter log should be filtered by search value
