### ISSUE TITLE
Enhance proxy settings.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2111]
Now it only supports HTTP and Socks4/5.
Even HTTP proxy doesn't work.
A bug.
https://github.com/AdguardTeam/CoreLibs/issues/470

Please additionally support HTTPS, SSH, ShadowSocks, Socks over TLS and so on.
You know that Chinese Great Firewall blocks VPN protocols and unencrypted proxy (HTTP & Socks) for foreign IP.
It's better if AdGuard can support encrypted protocols (HTTPS, SSH, ShadowSocks, Socks over TLS...etc.).

**Comment by sfionov** [comment]
Basically all mentioned protos requires intermediate library/software, because it is not simple after-connect hook for file descriptor, like current implementation is.
1) SSH
Ticket about SSH proxy is https://github.com/AdguardTeam/AdguardForAndroid/issues/1356
Implementing it will require an intermediate library (libssh2).
But you may use ConnectBot with SOCKS5 dynamic port forwarding. However, it's automatic reconnect functionality may fail when you lose mobile network signal. So, they may be better, but it's their room for improvement.
2) ShadowSocks
ShadowSocks client provides SOCKS5 proxy server. Also, they can provide tunneled DNS in manual proxy mode too, but doesn't do it (but you may ask them to add this functionality)
3) HTTPS and Socks over TLS will require intermediate library too, but we are not planning to do that in near future, until CoreLibs are integrated in all platforms.

**Comment by lancelot-moon** [comment]
@sfionov 
Proxy HTTP and Socks are unencrypted.
At least, supporting more encrypted proxy protocols is better.

Do you have any ideas for the issue?
https://github.com/AdguardTeam/AdguardForWindows/issues/2326
Thanks.

**Comment by andreysaksonov** [comment]
buit-in support for shadowsocks proxies would be superior

**Comment by adrianh-za** [comment]
Want to also request ShadowSocks proxy support

**Comment by sfionov** [comment]
Task for HTTPS proxy support: #3307

**Comment by ameshkov** [comment]
We'd better have a separate task for it: https://github.com/AdguardTeam/AdguardForAndroid/issues/3308

**Comment by sfionov** [comment]
@adrianh-za You may use AdGuard with ShadowSocks. Just configure it as local SOCKS proxy, exclude ShadowSocks from filtering inside AdGuard, and configure AdGuard to use ShadowSocks at localhost SOCKS port as outbound proxy.
