### ISSUE TITLE
Another proxy client app and AdGuard for Android's auto local HTTP Proxy mode 

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2121]
https://www.speedin.cc/

A Taiwanese reported that his rooted Android device has troubles between the Chinese VPN app and AdGuard auto local HTTP Proxy mode.

Other VPN apps and AdGuard auto local HTTP Proxy mode work fine.
But he couldn't get Chinese IP when using speedin's VPN app with AdGuard auto local HTTP Proxy mode.
It's still Taiwanese IP or lost internet connection when enabling speedin's VPN and AdGuard together.

We know Chinese Great FireWall.
It should already block most VPN protocols.
Only some encrypted proxy protocols can be through GFW, such like HTTPS, SSH, ShadowSocks and so on.
So I doubt that speedin's VPN app is actually a proxy client app.
(Afterwards speedin's customer support proved that connecting to its servers is via **ShadowSocks protocol**.)

Can another proxy client app and AdGuard for Android's auto local HTTP Proxy mode run together on a rooted Android device?

The Taiwanese user ever sent the log to AdGuard customer support if you need the log.
Can you solve it?
Thanks.

**Comment by ameshkov** [comment]
Does it help to disable AdGuard for that VPN app specifically in the apps management?

**Comment by abelyi100** [comment]
Dear Andrey,
Yes, it does help.

BTW, someone on a Taiwanese forum helped me post my problem on github.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2121

It would be great if what he guess is true.
I'm willing to test my device for it if you guys can fix this problem in a beta release.

Sincerely,
Abel

**Comment by ameshkov** [comment]
The thing is that this issue is somewhat expected.

Here's what happens:

Browser -> AdGuard intercepts data -> VPN app intercepts data -> AdGuard again intercepts data sent by the VPN app -> we're stuck in an infinite loop.

The only way to prevent this infinite loop is for AdGuard not to filter the VPN app's traffic (e.g. disable it in the apps mgmt).

We'll discuss it internally and look for other generic solutions:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2123
