### ISSUE TITLE
New DNS module settings UI

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2145]
See the sketch file in slack

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/1849f16c-07c0-4970-9132-c56976d4da61

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA:
-Add any custom server
-Choose any pre-defined server
-Reinstall AG
-Examine new DNS module

Expected result:
-Custom server is in `My DNS servers` list
-If pre-defined server is not AG/Google/Cloudflare/OpenDNS/Quad9 (quad9-dns/quad9-dnscrypt-ip4-filter-pri/quad9-dnscrypt-ip6-filter-pri/quad9-doh-ip4-filter-pri/quad9-doh-ip6-filter-pri): Selected server is in `My DNS servers` list
-Otherwise: The appropriate provider is selected

**Comment by ameshkov** [comment]
@admitrevskiy there are more changes required.

1. DNS --> DNS Filtering
2. Description in the settings section: `DNS filtering settings`
3. "Choose DNS server from list" --> `Choose from a list`

Click on the "choose" button should lead to a page on the knowledge base with a list of known DNS services.

Here's the proposed page layout:
https://gist.github.com/ameshkov/b904a5bf7bb162bbc4d95c6f1ea1b89e

4. Intercept `sdns://` protocol links and open the "Enter DNS Server" dialog in AdGuard.

**Comment by admitrevskiy** [comment]
Resolved,

Testing instructions:
-Reinstall AG
-Go to Custom DNS Settings
-Tap on `Choose DNS server from the list` should lead to KB article about popular DNS providers (https://kb.adguard.com/ru/general/dns-providers) via browser.
-Select any server from list in the article and click on `Add to AdGuard`

Expected result:
-AG opens "Add new server" dialog with pre-defined server parameters (Addresses for regular DNS and sdns-stamp for encrypted(DNSCrypt/DoH) servers)

**Comment by AlikhanAliev** [comment]
Behavior of "Choose DNS server from the list" button is incorrect
