### ISSUE TITLE
Add a new "Notification Icon" option: "Notification without icon"

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#222]
As user showed here: http://content.screencast.com/users/vasily_bagirov/folders/Jing/media/f9b9a93c-7933-470f-8c9c-77c938f86e95/2015-12-10_1858.png

AHE-618-60043

**Comment by TPS** [comment]
It's be appreciated if this could all be combined into 1 single-height notification — there is some functionality loss when all notifications reach > 1 screen height (much harder to expand notifications).

**Comment by tobia** [comment]
I'm not sure what @TPS is referring to.

My request, as per the screenshot above, is to have Adguard's notification in the ongoing or permanent area.

The problem with the current kind of notification is that it comes up on the locked screen, it lights up the notification LED, and so on, as if it were an unread message, which it's not.

**Comment by TPS** [comment]
Ahh, I understand now.  I've no experience with this with Android 4.4.x, as everything's just mixed together.  I thought this was requesting for the _(marked-off area in AG in that screenshot)_ # of blocked ads to appear in an additional notification, so my comment is in _that_ context.

**Comment by ameshkov** [comment]
@tobia it seems that the problem was not in "ONGOING" flag.
To achieve what you want our notification priority should be set to PRIORITY_MIN.

So, what I have done:
1. If "Notification icon" is set to "None", we show notification with minimum priority. In this case it looks like in "Avast" away, no icon and grayed out notification.
2. If "Notification icon" is set to "None", we simply show the notifcation + icon.
3. In both cases we now set FLAG_ONGOING_EVENT. It does not change UI appearance, but I hope this will increase the app priority.

**Comment by ameshkov** [comment]
Change of plans.

Instead of changing how "NONE" works, we'll introduce one more option: "Low Priority".
In "Low Priority" Adguard's icon is not visible, but notification is visible and grayed out.

**Comment by ameshkov** [comment]
Done
