### ISSUE TITLE
Add "firefox should be default browser on this phone" description 

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2229]
It is not clear for User that Firefox should be chosen as the default browser in order to install the certificate шт HTTPs Settings.
It is possible to add this description?

In case if the user has more than one browser and Firefox is not a default, the Firefox certificate is downloaded but not installed.

<details><summary>Screenshot:</summary>

![adguard qa bot _ adguard software ltd slack 2018-10-31 19-04-53](https://user-images.githubusercontent.com/41899455/47801817-023d0900-dd40-11e8-9f7e-173581a2ce75.png)

</details>

**Comment by Revertron** [comment]
On decent devices you have a browser selection dialog like this:
![screenshot_1541070079](https://user-images.githubusercontent.com/105154/47848191-d6686480-ddcd-11e8-9ef2-7f895905479a.png)

**Comment by TPS** [comment]
@Revertron That menu shows iff no default browser…
@karina-archazh …but there exists a version of that menu since @ least Android 2.×!

Is there a way for AG's logic (having an internal browser list as it does) to:
- Show/open _only_ browsers compatible w/ that manual certificate (mostly only certain Ff versions)?  Bonus if 1 can design the intent directly toward adding to its certificate store.
- Failing that, *replicating* that browser menu, based on known installed browsers, bypassing the system functionality (which might be disabled if there's that default set)?
