### ISSUE TITLE
Filtering log option buttons disappear after clicking "Remove all"

### ISSUE THREAD

**Issue by Yevhen1996** [AdguardTeam/AdguardForAndroid#2331]
### Steps to reproduce

1) Open Filtering Log page – in the top right corner, there are 3
icons: magnifying glass, 3 parallel lines, 3 vertical dots 
2) Click 3 vertical dots, then "Remove all", 3 parallel lines and 3 vertical dots disappear
3) Open any kind of browser, do some browsing
4) Switch back to filtering log. Buttons don't appear
5) If you click the update button (circle arrows) all options in filtering log are back in place. 

### Expected behavior
After you click "Remove all" in the filtering log, all buttons in the top-right corner should still appear.

### Actual behavior
3 parallel lines and 3 vertical dots disappear after cleaning the filtering log

<details><summary>Screenrecording:</summary>

<https://uploads.adguard.com/ovsdg.mp4>

</details>

### Customer ID 
1781723, 2428255

### Your environment

* Adguard version: 3.0.72n
* Adguard filtering mode: VPN 
* Device model: Meizu M6 Note
* Operating system and version  Android 7.1.2
* Not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by ameshkov** [comment]
Yeah, this is quite annoying

**Comment by SergeiShir** [comment]
I reported the same issue.
Customer ID = 1146569.

- AdGuard version: This issue was seen in all Nightly versions 2.xxx and in the latest Nightly versions 3.xxx
- AdGuard filtering mode: VPN
- Device model: Google Pixel 2 XL
- Operating system and version: Stock Android 9, Security patch from 05Nov2018, Kernel 4.4.116-g62fd7c7873da (07 Sep 2018), Build PQ1A.181105.017.A1
- Rooted or not: NOT rooted
- Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? NO

Thanks

**Comment by admitrevskiy** [comment]
Resolved in https://github.com/AdguardTeam/AdguardForAndroid/issues/2217

Testing instructions:
The same behaviour was observed in all screens with search option. Please, examine all of them.
