### ISSUE TITLE
"QuickRemote" app fails

### ISSUE THREAD

**Issue by Dariamag** [AdguardTeam/AdguardForAndroid#245]
User's got an LG g4 h818p. 
The g4 comes with a remote control app using the built-in ir blaster. Whenever the user installs Adguard the remote control app fails. 
https://scontent-arn2-1.xx.fbcdn.net/hphotos-xtl1/v/t34.0-12/12399190_10205757401958287_1413500739_n.jpg?oh=69f1ae8b3559688e33b0071608c53030&oe=567B9600

This procedure didn't help:
1. Go to Settings -> Advanced - Low Level
2. Find and edit pref.net.exclusions preference there
3. Add 'com.lge.qremote' on a new line
4. Restart Adguard protection

**Comment by ameshkov** [comment]
@Dariamag 
I'd like to see user's log file to understand what's going on.

Here is an instruction:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/49/9/collecting-a-full-log-on-adguard-for-android

Please post a ticket ID if user send the logs.

**Comment by Dariamag** [comment]
@ameshkov User has just sent us detailed info. Ticket ID: QSP-993-64159

**Comment by ameshkov** [comment]
According to the log file, the app was not excluded from VPN, so it is either was not added to "pref.net.exclusions" OR it was not installed.

Here is a test build with:
1. com.lge.qremote added to default exclusions list
2. Extended logging

http://static.adguard.com/android/release/adguard_issue245.apk

@Dariamag please ask user to try that new build.

**Comment by evgeniy-ADG** [comment]
QSP-993-64159

[debug (6).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/71642/debug.6.txt)

The customer has set the log to record everything and reproduced the problem

**Comment by ameshkov** [comment]
I have bad news about this.

So, what do I see in the log. I see that the app was successfully excluded from the VPN and after that I see nothing about that app at all. It seems that the app functionality is broken simply by the presence of VPN service and not by some specific action we do. Maybe this issue is similar to tethering/hotspot problem when Android simply does not allow to use it when VPN is on.

**What now:**
1. @Dariamag, please ask user to check it. He can install some simple VPN app like Netguard: https://play.google.com/store/apps/details?id=eu.faircode.netguard&hl=en and check if QuickRemote works with this app's VPN enabled.

2. If I am right and the problem is in VPN itself, then the only workaround is to disable AG when user wants to use QuickRemote. This can be automated by using Tasker: https://kb.adguard.com/index.php?/Knowledgebase/Article/View/59/9/tasker-app-configuration-to-work-with-adguard-for-android

**Comment by Dariamag** [comment]
@ameshkov The user replied: "Hello! I tried the given instructions. Here's what I did. I uninstalled adguard/installed netguard/restart phone/ran netguard/tested qremote. It works fine without adguard. Once I installed adguard the qremote fails again."

**Comment by ameshkov** [comment]
jackie chan jpg

**Comment by ameshkov** [comment]
Ok, what do I now suppose: we simply do not exclude the right package from VPN (NetGuard simply excludes all packages and it solves the issue).

First of all I need to know the full list of installed packages.

Here is a build which includes list of all installed packages to the information sent by "Send Feedback" option. @Dariamag please ask user to install it and send us a message from there.

Download link:
http://static.adguard.com/android/release/adguard_issue245.apk
