### ISSUE TITLE
Firewall temporary unblock notification is shown every minute

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#251]
Steps to reproduce:
1. Disable network access for an app
2. Start the app
3. Do nothing with unblock notification and continue working with the app
4. Notification will be shown again in a minute

**Comment by TPS** [comment]
Is this a _particular_ app?  For any of the apps I have such notifications, it only happens once per attempt by the app.  Is this then to make rate-limiting these notifications in some fashion?  If so, could that rate be configurable?

**Comment by ameshkov** [comment]
According to user it happens for every app.

I think we simply shouldn't repeat this notification until the app goes background and foreground again.

**Comment by Revertron** [comment]
Okay, I've blocked internet access for `com.alensw.PicFolder` (QuickPic gallery app) and I see following behavior:
The app is trying to connect to its servers constantly, without any pause.
We are clearing last notified package variable after 1min timeout. I will rethink the mechanism right now...

**Comment by Revertron** [comment]
If we remove the code that clears timeout, this case will not work:
User starts blocked app, it tries to connect, we block and notify user.
After using the app user is quiting it, goin to some other app.
After a minute user goes to this blocked app once more and *he will not get our notification again*.
If he decides to use Internet in that app he will have to go to firewall settings to enable it (not temporarily).
The problem is - we do not constantly check foregroundness of blocked app, only on blocking event.

**Comment by Revertron** [comment]
Yahoo! I've found a way :)

**Comment by ameshkov** [comment]
What was it?
