### ISSUE TITLE
Importing settings from file from 2.12 does not transfer filters

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2513]
1.  Install 2.12.250 
2. Enabled some unusual filters
3. Export settings
4. Install last nightly version (clearly)
5. Import settings

### Expected behavior
Filters should be available 

### Actual behavior
Filters doesn't importing

<

**Comment by nkartyshov** [comment]
fixed

**Comment by aspasskaya** [comment]
### Steps to reproduce
1. Install 2.12.250 
2. Disable all filters
3. Enable [ROlist filter or ABPVNlist+ABPindo]
4. Export settings
5. Update to nightly v3.0.232n
6. Clear data and cache
7. Disable all filters group and filters inside !!!
8. Import settings
8.а -> settings file -> enabled ROlist filter
https://uploads.adguard.com/assa_gth89.json
8.b -> settings file -> enabled ABPVNlist+ABPindo
https://uploads.adguard.com/assa_san7w.json

### Expected behavior
Should be enable [ROlist filter or ABPVNlist+ABPindo] filters.

### Actual behavior
Enabled only language filters group.

![image](https://user-images.githubusercontent.com/43952607/52485219-6a19b000-2bc9-11e9-8f87-30c7a83d74a2.png)

**Comment by nkartyshov** [comment]
Fixed
