### ISSUE TITLE
Exclude Android browser [Xiaomi devices] from the enforce https filtering list

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2538]
Package name - com.android.browser

**Comment by ameshkov** [comment]
Hm, why?

**Comment by ameshkov** [comment]
On most of the devices, it should be filtered. If there's a device-specific issue with this package, the task needs to be changed accordingly.

**Comment by TheHasagi** [comment]
It warns about certificate issue every time you try to reach HTTPS websites.

**Comment by ameshkov** [comment]
**Which devices are affected**?

**Comment by TheHasagi** [comment]
For now, it's Xiaomi devices. (example Xiaomi Redmi Note 4/4x)

**Comment by ameshkov** [comment]
@TheHasagi well, the task should be about excluding this package on Xiaomi, not everywhere

**Comment by nkartyshov** [comment]
Cannot reproduce. The com.android.browser works fine with https filtering enabled in the Redmi 3s.

**Comment by TheHasagi** [comment]
Seems like after the update of Xiaomi Browser problem has gone. Closed.

**Comment by ronildo66** [comment]
I have an Xiaomi Mi 5 for 2 years, since always I used the a Google Chrome downloaded through the Play Store with AdGuard.

This week I tried to use the default browser called "Mi Browser" Version: 10.5.6-g (updated) but all the https pages I tried to access had the following error:

> **Security warning**
> 
> There are problems with the security certificate for this site.
> 
> Continue | View certificate | Go back

I was able to resolve the issue by disabling HTTPS filtering for "Mi Browser" in AdGuard> Apps Management

But I'm not satisfied, I would like to use https filtering in this browser. Any idea what might be happening?

I've heard that this happens a lot in default browser from several manufacturers, is it true? I tested the default browser of NoxPlayer 6.2.7.1028 emulator (Android 7.1.2) with AdGuard and was the same problem.

Thanks!
