### ISSUE TITLE
Add Kiwi browser to the browsers list

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2585]
AdGuard does not filter com.kiwibrowser.browser in a free mode.

**Comment by lancelot-moon** [comment]
@AMeshkov 

It's strange that kiwi browser isn't in the list of enforcing HTTPS filtering in the low settings since I remember that you have fixed it.
Something wrong?

What's New:
version 3.0.264 from March 1, 2019
* [Feature] Update CoreLibs to 1.3.179;
* [Fix(regression)] Disable Whitelist function does not work;
* [Fix(regression)] Magisk Manager unable to pass SafetyNet check with AdGuard enabled;
* [Fix] A group should be enabled if a filter is enabled from search a filters;
* [Fix] Add Kiwi browser to the browsers list;
* [Fix] Do not restart protection when enabling filter group if all filters disabled;
* [Fix] HTTPS Filtering settings bug;
* [Fix] Remove icon to custom filter group sections.
