### ISSUE TITLE
UI does not support Android TV

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2611]
People report that it's hard to navigate through the app with TV remote. What can we do about it?

And one more thing -- some Android TVs do not allow user cert installation. We should handle it gracefully and show a user-friendly warning when we detect this situation.

**Comment by BooBerry** [comment]
Also there should be a "friendly" error informing the user when AG's certificate can't be installed, which in my case doesn't work on the Mi Box S nor Nvidia Shield TV on Android TV. In fact, I'd actually recommend telling the user to uninstall the app (since without HTTPS filtering AG for Android would be practically useless) and instead use AG DNS or AG Home as an alternative.
