### ISSUE TITLE
Suppress browser cache after filtering startup for a short period of time

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#270]
The same issue in Win version:
https://github.com/AdguardTeam/AdguardForWindows/issues/675

**Comment by ameshkov** [comment]
Review ID: CR-AG-730

**Comment by ameshkov** [comment]
Not sure if we need this in Android, cache is not much of a problem here.

**Comment by TPS** [comment]
I tend to have a *lot* of issues that seem to resolve (wireless not connecting, pages not loading) if I manually clear AG's over-large cache.  I notice once AG's cache becomes > 5 mb or so, it causes these issues, so I force-stop, clear the cache, & restart AG, so I'm hoping issues related to the cache will resolve it.

**Comment by ameshkov** [comment]
That's bad that you have these issues in the first place:)

Clearing AG cache just stops the process and I suppose that's why this helps.
Could you please next time try to force stop AG instead of clearing the cache?

Also this issue is not about AG, but about a browser cache. Some ad elements may be cached along with the page code, that's why we suppress it in desktop AG. However it seems to be useless on mobile, it seems that browser ignores the old cache when VPN is turned on.

**Comment by TPS** [comment]
Oops, my fault.…  Promote to new issue?

I will try as you ask next time problems occur, but it didn't seem to help before as:
* clearing cache _doesn't_ force-stop AG
* just force-stopping _hasn't_ resolved issues

**Comment by ameshkov** [comment]
> clearing cache doesn't force-stop AG

Yep, you're right, my bad. But it clears AG certificates cache and this could break existing HTTPS connections.

> just force-stopping hasn't resolved issues

Weird. I just don't understand how it could be a problem.

What we store in cache:
1. Logs
2. Certificates cache

**Comment by TPS** [comment]
No clue @ all, but solves 'til next time.  DNS cache in there, too?  To simplify, I've kept HTTPS-filtering off since testing it toward the beginning, so I don't know what certificates may cache in this scenario.

**Comment by ameshkov** [comment]
Weird, nothing there except the log then.

**Comment by ameshkov** [comment]
Moved to CoreLibs
