### ISSUE TITLE
Option to block all internet access when AdGuard is down

### ISSUE THREAD

**Issue by sebast889** [AdguardTeam/AdguardForAndroid#2733]
Android has a "Block connections without VPN" option but that setting doesn't work as you would expect at all.

There should be an option within AdGuard to block all internet/intranet access when AdGuard is down, disconnected, changing networks, failed to start etc so that traffic will only work and pass through an active AdGuard connection tunnel.

**Comment by Revertron** [comment]
I wish that would be possible, but it is not :(

**Comment by sebast889** [comment]
What is the reason for that? Because the app isn't running?

But it should still be possible when app is running but disconnected for whatever reason, right?

**Comment by Revertron** [comment]
The only option is on system side - "always on VPN, block connections outside VPN".
Please, take a look at this thread: https://android.stackexchange.com/questions/14455/how-can-i-block-the-traffic-outside-the-vpn-even-if-the-vpn-is-down

If you use VPN mode and have Android 8+, you can set AdGuard as always-on vpn, and disable all traffic if there is no VPN established.
If you use Auto-proxy mode (with root) in AdGuard, there is no such option for now, but we can think of something in coming versions.

**Comment by TPS** [comment]
@Revertron, @TheHasagi, @ameshkov: Sadly, AG no longer functions under "Block connections outside VPN."  To repro:
1. Turn on airplane mode (or otherwise turn off _both_ data & wifi connection).
2. Turn on both "Always on VPN" ___&___ "Block connections outside VPN"
3. Turn off airplane mode (or turn on wifi &/or data connection)
4. AG'll attempt to startup.

__Expected:__ AG should stay working.
__Actual:__ AG rapidly toggles between on & off. But, whenever "Block connections outside VPN" is _off_, AG's just fine.

I'm on OEM Android Oreo/8.1, unrooted Moto G5+, w/ AG VPN.
