### ISSUE TITLE
AG crash if many applications are installed

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2744]
### Steps to reproduce

1. Install more than 250 apps
2. Try to edit firewall rules (wi-fi/data)
3. AdGuard won't be able to list all apps and it will freeze/stop protection/crash

### Customer ID 

AdGuard Form (Post-181589)
### Your environment

* Adguard version: versions v2.x and v3.x(irrelevant)
* Operating system and version: Android 6.x Android 7.x Android 8 and Android 9 and it has always been the case.

**Comment by Chinaski1** [comment]
One more user Faced this issue: **1997608**
**Logs in NCloud**.

**Comment by artemiv4nov** [comment]
We made a deep dive into the problem. After all, I guess, it's an Android code bug.

The problem is the Android Package Manager cannot perform a request about providing a lot of applications. He needs either one big request or a few little, and it does that.
Anyway, Cursor memory overflow occurs and a request breaks the application.

I'm going to close the task, please re-open it if new logs appear.
