### ISSUE TITLE
Review the VpnService.setUnderlyingNetworks code

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2836]
First of all, we can use newer APIs on P. Look at what's done in Shadowsocks.
https://github.com/shadowsocks/shadowsocks-android/commit/0af450008b021592d3a1241891f593ddfbd57b15

Second, there are some Xiaomi-specific workarounds, we should check if we still need them.

Original issue: https://github.com/AdguardTeam/AdguardForAndroid/issues/1587

Btw, OpenVPN simply sets it to null:
https://github.com/schwabe/ics-openvpn/blob/450e99c135ebabbf911d6880e39811d88454cdd1/main/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java#L879

**Comment by sviperz** [comment]
The issue is easy reproducible on the latest Android 10 release and AG Nightly. You just take a new photo and watch Google Photos waiting for WiFi infinitely though it is definitely turned on.

![Google_Photos_WiFi_Issue](https://user-images.githubusercontent.com/11470610/66020692-908db200-e4f0-11e9-8ce3-0f34c86ff68e.png)

Please escalate as since backup using mobile data is usually turned off, the photos are never back up to the cloud when AG is switched on.

### Environment
* Adguard version: v3.3. nightly 7 (50)
* Adguard filtering mode: VPN
* Device model: Google Pixel 3
* OS: Android 10
* Google Photos version: 4.25.0.271222815
* No root

**Comment by artemiv4nov** [comment]
@Revertron you lead this task.
@admitrevskiy you need to support ur teammate, checking the decision on Xiaomi devices.
