### ISSUE TITLE
HTTPS filtering in Firefox Fenix

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2861]
Firefox Preview (https://play.google.com/store/apps/details?id=org.mozilla.fenix) is not currently recognized as a known browser, and as such its traffic is not filtered when AdGuard is in free mode.

**Comment by TheHasagi** [comment]
It will be possible only if the certificate is allowed to be installed

**Comment by Xophile** [comment]
Hi!

Is this a Firefox preview issue or AG?

**Comment by Revertron** [comment]
@Xophile https://github.com/mozilla-mobile/fenix/issues/2286

**Comment by Xophile** [comment]
Hi!

Thanks for the link. Seems like it's not being added to the features coming in the near future.

This will affect Adguard as well, any possibility for you to push for this feature?

Thanks!

**Comment by artemiv4nov** [comment]
@Xophile , when Firefox Preview will have a possibility to install user certificates, we'll add the browser to the known browser's list.

**Comment by Xophile** [comment]
> @Xophile , when Firefox Preview will have a possibility to install user certificates, we'll add the browser to the known browser's list.

Hi!

Yes I know that. My question was if you, from Adguard, could push the wish for this feature in Firefox preview since there really is no reply on Github for Firefox preview.

See link above. Thanks

**Comment by ameshkov** [comment]
@Xophile this is one of the top upvoted issues on their Github: https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

Hopefully, they'll implement this when Firefox preview is closer to release.

**Comment by ameshkov** [comment]
Firefox Fenix has been released and we now should deal with it now.

1. By default, there's no way to import a cert there.
2. However, there's an option to enable it: user needs to enable `security.enterprise_roots.enabled` in `about:config`.
3. The problem with it is that `about:config` is broken in all Firefox Fenix versions save for Nightly. However, I think we should anyway show an instruction that explains how to enable it.


When the user taps on "Install to Firefox", show an instruction on how to make it trust user certs, e.g. open Firefox, enter `about:config`, find and enable `security.enterprise_roots.enabled`.

The task is re-assigned to v3.5 since Fenix is now released and it's important to deal with it asap.

Useful links:

* https://github.com/mozilla-mobile/fenix/issues/3728
* https://github.com/mozilla-mobile/fenix/issues/7865
