### ISSUE TITLE
Custom filters aren't restored from backup

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2864]
Please find the example backup file in Nextcloud.

### Steps to reproduce

1. Add a custom content blocking filter
2. Enable some random filters as well
3. Export settings
4. Reinstall AG
5. Import settings

### Expected behavior
All filters are restored

### Actual behavior
Custom filters aren't restored

**Comment by patrickdrd** [comment]
I should add that it wasn't only custom filters,
but all the filters in general,
i.e. I had 19 filters (out of 20) enabled and only 3 were enabled after the restore (!)

my custom filters are 9 enabled (out of 10) and
none was restored, I've had to input the urls from start

apart from them, the problem was big with the annoyances,
if I remember correctly, none was restored

**Comment by TheHasagi** [comment]
The user filter counts wrong after importing settings until you add or remove some of the existing rules.

**Comment by admitrevskiy** [comment]
Done.

@TheHasagi please, check this issue in the next nightly build
