### ISSUE TITLE
Fix search suggestions in Firefox

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#2884]
We have bug: when user enters something in the address bar of firefox, then it doesn't show suggestions. This can happen because the browser doesn't trust user certificates and search engines' requests breaks up.

How to reproduce:
1) Install latest version of Firefox;
2) Go to duckduckgo.com and setup as default search engine;
3) Try entering something in the address bar with turned off AdGuard's protection: browser should show suggestions;
4) Turn on AdGuard's protection;
5) Entering something in the address bar again, suggestions should not be show.

**Comment by artemiv4nov** [comment]
After all we decided to keep everything as it is now.

**Comment by GyokuroT** [comment]
In the latest beta release you marked this issue as fixed. On GitHub the other hand you closed it without a fix.

**Comment by ameshkov** [comment]
@GyokuroT yup, thanks for noticing.

Let me please explain why we decided to keep the current behavior. The problem is that if we try to fix it, we risk breaking HTTPS filtering of the search domains.

There is a simple workaround for Duckduckgo, though: simply adding `ac.duckduckgo.com` to the HTTPS filtering exclusions will fix the issue. On the other hand, for Google we'll have to exclude `www.google.com` completely -> we won't be able to block search ads.
