### ISSUE TITLE
Use app cloning to circumvent SSL pinning issues

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2889]
As reported by user 2046342,

> Some apps dont trust user certificates and cant use https block,But I
> have a way can block all advertisements with turning on https block in
> all inapplications.
> 
> We can make an application that can copy a app and run it in this
> apps, such as 双开助手 and dubbel. As long as the Android target
> of this application is not more than 23, This software will be able to
> run the application above the  Nougat+ framework with https
> interception enabled.
> 
> I hope that you will create a more adaptable application which ability
> to clone and run other software in this app. Meanwhile it can create
> icons to the desktop,Not only on Google’s official desktop, but also
> some third-party desktops which can’t create icons to the desktop
> and only put the installed apps on the desktop.li[http://desktop.li]ke
> my phones system, Smartisan OS.
> 
>   PS: This method is 100% feasible after my test.But I am learning
> English. I dont know if my description can make you understand.

**Comment by LU-LEI** [comment]
My idea is to make a more matching clone tool alone.If you choose to integrate in adguard, you may encounter push problems, because there will be a traffic notification when you hang VPN, many people include I choose to close the notification, so it will affect the software notification.But one of the biggest benefits of integration is that it is easy to use, But have to take into account the adguard's Android target。

**Comment by TheHasagi** [comment]
I don't think that this is necessary for now :) Also, kinda weird idea.

**Comment by LU-LEI** [comment]
Ok, then in some countries, adguard is basically a useless software, because the main purpose of blocking ads does not take effect.

**Comment by ameshkov** [comment]
Duplicate of #1675

This is a valid approach actually.
