### ISSUE TITLE
After returning from ultra-saving battery mode to normal Adquard does not start automatically

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#289]
It has to be started manually. More information and LogCat logs are inside the ticket:

PGL-698-42306

**Comment by ameshkov** [comment]
@vbagirov what's that mode? There is no such thing in stock Android.

Something device specific?

**Comment by evgeniy-ADG** [comment]
HUAWEI ALE-L21

**Comment by vbagirov** [comment]
@ameshkov user called it 'ultra-frugal mode', I believe it is called 'Ultra power saving mode'.

**Comment by ameshkov** [comment]
I guess this "ultra-power-saving-mode" is yet one task killer app bundled with huawei devices? Also I guess it does not respect "sticky" services behavior and that's why AG is not restarted automatically.

I don't know what to do with it except (maybe) adding AG to exceptions (if any).

In order to fix this we should search for more information about it.

**Comment by seba2282** [comment]
Hello, on my Huawei this problem is still valid. Ultra frugal/ultra saved mode battery and I still must run manually AG after back to normal ,/ intelligent mode saved battery. I haven't any option with add to exclussion application. The same problem for me with my AV. But for example facebook or google applications start normally.

Best Regards

**Comment by ameshkov** [comment]
@seba2282 how does it look like in facebook/google case? Apps just get back to foreground or what?

**Comment by seba2282** [comment]
@ameshkov, Facebook mobile, gmail or more android google apps (gmail etc.) reactive (start turn on/synchronize normally) after back normal trybe from ultra trybe mode battery. AG app not reactive (doesn't start) and must turn on manually (I reported this bug to Adauard support) . The same problem with my Antivirus but I reported it and Eset works over fix).I don't know how I can should write it.

**Comment by ameshkov** [comment]
> start turn on/synchronize normally

Do you mean that you start receiving FB/google updates right after returning back to normal mode?

> I reported this bug to Adauard support

As you see support has escalated it to us:) We just need more details on this as we don't have a test device with this ultra-mode.

**Comment by seba2282** [comment]
I write only, if I have ultra-saved/frugal trybe battery active, AdGuard will be close automatically, but I back to normal / intelligent trybe after, Adquard doesn't start automatically. Must turn on it manually. And add few example from my apps, which start normally automatically.

**Comment by ameshkov** [comment]
> I write only, if I have ultra-saved/frugal trybe battery active, AdGuard will be close automatically, but I back to normal / intelligent trybe after, Adquard doesn't start automatically. Must turn on it manually. And add few example from my apps, which start normally automatically.

I understand what's the issue, it's just not so easy to fix, so I am trying to figure out how do these apps start normally.

You see, I suppose that FB/Google react on some event raised after device is back from ultra-mode. However, I don't see any network related issue in AG logs (and that's the only thing AG listens to).

I see two possibilities how these apps do it:
1. There is some event that we can "listen" to.
2. These apps are simply started on timer.

To find out which one is true, I'd like to know more about their behavior. That's why I ask about their reaction. If you get new FB/google updates/notifications *right after* getting back from ultra-saving mode, then it means that point 1 is true. If there is some "lag", then point 2 is true.

**Comment by seba2282** [comment]
Sorry for my small active, but work all time. I think,  problem is in huawei rom. It is specific modified rom by huawei (emui). Maybe in it this problem. Eset has the same problem and they try fix it but they can't.

**Comment by ameshkov** [comment]
> Sorry for my small active, but work all time. I think, problem is in huawei rom. It is specific modified rom by huawei (emui). Maybe in it this problem. Eset has the same problem and they try fix it but they can't.

I suppose this issue should be also reported to Huawei as the problem is caused by their app.

**Comment by seba2282** [comment]
Hello, I reported this problem to Huawei. 

Best Regards

**Comment by ameshkov** [comment]
Thank you! I hope they'll start respecting "sticky" services behavior as Android itself does it.
