### ISSUE TITLE
 No gap in protection status in some languages

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2939]
European languages like Francais, Deutsch, Espanol. There is no space between, for example in Dutch it reads: **Bescherming isuit**  >> but it should be: **Bescherming is uit**.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/61527362-ee981680-aa24-11e9-8055-e614f88af717.png)

</details>

### Your environment
AdGuard : Nightly 3.2.100

**Comment by OfficialNyTony** [comment]
This will most likely be fixed later on upcoming versions. Pretty minor issue. Great point though!

**Comment by lancelot-moon** [comment]
#2362173
" enabled"

#2362174
" disabled"

T'hey're not "enabled" and "disabled".
There is a space there, but it's not clear.
That's why most translators didn't note this.
Simply solve them on onesky.

**Please don't add a space in your program codes.
It doesn't need a space there for some Asian languages.**

**Comment by TheHasagi** [comment]
It's just a wrong translation strings.

**Comment by lancelot-moon** [comment]
I went to check Nederlands on onesky.
#2362173 and #2362174 were fixed by a translator on 23rd June, 2019.
But maybe the space is deleted when AG team took the translations from onesky.
Or something wrong.
You can check your locales files.
