### ISSUE TITLE
Can't access Internet with airplane mode on and wifi turned on

### ISSUE THREAD

**Issue by anoop-b** [AdguardTeam/AdguardForAndroid#2940]
### Steps to reproduce

1. keep Adguard running & enabled
2. turn airplane mode on
3. turn on wifi

### Expected behavior

should have access to internet via wifi, with Adguard enabled.

### Actual behavior

can't connect to internet via wifi, with Adguard enabled

### Your environment

* Adguard version: 3.2.100n
* Adguard filtering mode: Local Vpn
* Device model: OP6  
* Operating system and version: 9.1.2
* Root access:Yes
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?:  NO

**Comment by lancelot-moon** [comment]
Can't reproduce on HTC U11 (Android 9).
BTW, a temporary solution:
Try disabling `pref.vpn.disable.pause` in low level settings.

**Comment by artemiv4nov** [comment]
@anoop-b send logs to devteam@adguard.com, please

**Comment by anoop-b** [comment]
> @anoop-b send logs to [devteam@adguard.com](mailto:devteam@adguard.com), please

just sent it!

**Comment by artemiv4nov** [comment]
@anoop-b , unfortunately, your logs are not enough. Can you send debug logs and also logical with exact time of error?

**Comment by ameshkov** [comment]
@anoop-b to troubleshoot this issue, we need to get the additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by artemiv4nov** [comment]
The task is closed due to the lack of appeals to similar problems. The task can be reopened if someone will have similar issues again.
