### ISSUE TITLE
DNS filtering does not work properly in case of IPv6 DNS server

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#295]
The customer reposts that Filtering DNS requests makes Wi-Fi speed noticeably slower after latest AdGuard update. Mobile data seems to be unaffected. 

debug logs: XEH-256-49655
screencast of the issue: https://goo.gl/photos/wyp7iP7gUtYENAcH7

**Comment by ameshkov** [comment]
The issue is caused by the fact, that users DNS servers are IPv6.

I believe that the issue is caused by the fact, that actual users DNS servers are on IPv6.

So, how it looks like:
1. We register fake IPv4 DNS
2. Receive a DNS request from the client app
3. Pass it further to the real DNS server (IPv6)
4. Get response and pass it back to the client app
5. Client app expects DNSv4 answer, while we return DNSv6.

@evgeniy-ADG please thank user from me for such a good bug.

**Comment by TPS** [comment]
Does #139 exacerbate this?

**Comment by ameshkov** [comment]
Not sure, this issue seems to be very rare.

**Comment by ameshkov** [comment]
Dup
