### ISSUE TITLE
Can't choose Local HTTP Proxy [Android 10/Rooted]

### ISSUE THREAD

**Issue by izark99** [AdguardTeam/AdguardForAndroid#2999]
My Phone: Xiaomi Redmi K20 Pro
Android version: 10
Root: Rooted with Magisk

After I upgrade my phone to Android 10 and rooted it with Magisk, I can't connect to Internet if I choose "Local HTTP Proxy (Local Proxy auto mode)" in Filtering Method. I can connect to Internet if I choose "Local VPN" in Filtering Method.

This problem appear after I upgrade my phone to Android 10. Before that, Android 9 I can choose it normally.

Sorry because my English is not good.

**Comment by ameshkov** [comment]
Android Q is not compatible with root+proxy mode in the current version:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2894

We are going to push the fix for it to the nightly update channel this week.
It'd be great if you could verify if it's okay or not once we do that.

Can you test a build with the fix if we send you one?

**Comment by izark99** [comment]
okay

**Comment by ameshkov** [comment]
@izark99 please check the new release, it is now fully compatible with Android Q
