### ISSUE TITLE
Adguard proxy doesn't with host name

### ISSUE THREAD

**Issue by Superman1974** [AdguardTeam/AdguardForAndroid#3005]
After plenty of trials adguard I finally realized Nordvpn host servers names don't work like us4263.nordvpn.com in adguard proxy settings the host name has to be converted to and actually ip for socks5 to actually work us4263.nordvpn ->ip converted->208.131.139.43 now it works I hope this helps your software development and adguard users.

**Comment by Superman1974** [comment]
And I also look into the openvpn file configuration us4263.nordvpn.com.tcp.ovpn has the ip for tcp also that adguard website describes that udp doesn't work for socks5 adguard proxy so I tried that ip and it work also.

**Comment by ameshkov** [comment]
Hmm, this is weird.

**Comment by ameshkov** [comment]
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Send it to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by TheHasagi** [comment]
@Superman1974 

I can not reproduce this issue. Actions described above are important. Please, follow the steps and send the logs to devtean@adguard.com.

**Comment by TheHasagi** [comment]
Issue closed. Will be reopened if there will be more details.
