### ISSUE TITLE
Can't remove discord notifications when adguard is enabled

### ISSUE THREAD

**Issue by samsepiol59** [AdguardTeam/AdguardForAndroid#3040]
### Issue Details

- **AdGuard version:**
  - Latest Android App
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Xiaomi Mi A1
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

Discord notification should disappear when clicking on "Mark as read"

### Actual Behavior

It doesn't disappear, but it goes away instantly if I pause adguard even minutes after first clicking on "Mark as read"

**Comment by TheHasagi** [comment]
Seems ok from my side. Give another try with the latest release 3.2.150.

**Comment by samsepiol59** [comment]
v3.2.150 is the one I'm using currently! Do I need to whitelist something by any chance?

I'm using every starred filter (only the Easy List Italy for language) + the nocoin one in Security! Using cloudflare dns-over-https, no extensions, using local vpn!

**Comment by TheHasagi** [comment]
@samsepiol59 
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by TheHasagi** [comment]
Unable to reproduce the issue. Should be reopened if there will be more details.
