### ISSUE TITLE
Router admin panel is very slow with Adguard enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#306]
GKD-852-84210

http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=46933329

**Comment by TPS** [comment]
Huh.  Obviously, I can't follow any of that discussion (my Russian = 0 :disappointed:), but 2 general notes from my setup:
 1. I don't have this issue whatsoever on either of my routers.  I can provide details (privately only, _please_, because.…)
 2. I know the temptation is to just whitelist the LAN addresses, but [consumer routers tend to some of the most hacked/hackable hardware bits in existence](https://www.google.com/search?q=large+percentage+of+consumer+routers+hacked) & I think we all need protection from them as much as the rest of the 'Net!



Interesting semi-related link:
- [Adblocking via router firmware](https://github.com/search?q=adblock+router)

**Comment by ameshkov** [comment]
There's not much to follow, it just really works very slow and I can't understand why.

I suppose that this issue may be pretty important as *maybe* it is caused by a mistake in our HTTP protocol implementation. Routers often use some very old web servers supporting only old HTTP/1.0 or something like that.

**Comment by ameshkov** [comment]
Uh, still no clue what's going on. Reassigned to v2.6
