### ISSUE TITLE
il.co.pat.WhatsAppStickersIL - does not work when AdGuard protection running

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3074]
@adguard-bot commented on [Tue Sep 17 2019](https://github.com/AdguardTeam/AdguardFilters/issues/40641)

### Issue URL (Incorrect Blocking)
[NSFW][http://www.pat.co.il](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.pat.co.il)
### Comment
> When adguard Is activated, the app sticket doesn't open. 
> The app sticket, the film mame Is sticket - WAStickerapps 
> Ir adguard Is disabled, the app sticket work properly. 
> Thanks

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/VJY6ZZs.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/xbA6fqd.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
Browser: | Firefox Mobile
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Spanish/Portuguese,<br>EasyList

**Comment by Alex-302** [comment]
URL: https://play.google.com/store/apps/details?id=il.co.pat.WhatsAppStickersIL&hl=en_US

It is not working even if protection is disabled for this app. Works only when AG is paused.

**Comment by admitrevskiy** [comment]
According to the logcat, something like this happens:

WhatsAppStickersIL app tries to get banners via Android GMS Dynamite ads module and real ad request is sent via `Google Play Services`, not WhatsAppStickersIL. Looks like if the app doesn 't get a valid response from Play Services, it refuses to continue loading.
This issue is unsolvable since we will not disable ad blocking for Play Services. User may do it but it's strongly not recommended.
