### ISSUE TITLE
App language can't be change

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdguardForAndroid#3104]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

1. Set language to English.

- **AdGuard version:**
  - `3.3 nightly 7`
- **Filtering mode:**
  - `Local VPN`
- **Device:**
  - `Nextbit Robin`
- **Operating system and version:**
  - `Android 7.1.1`
- **Root access:**
  - `No`

### Expected Behavior

App UI language will change to English.

### Actual Behavior

See the screenshots.

正體中文 makes me can't understand what the function does.
I don't want to see the 正體中文 user interface!!!!!
I feel very uncomfortable!!!!!

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/5698157/66047743-e72fd600-e55a-11e9-8f3e-2968a607d29f.png)
![image](https://user-images.githubusercontent.com/5698157/66047751-ee56e400-e55a-11e9-9300-b6fba34969a4.png)

</details>

**Comment by TheHasagi** [comment]
@bestpika 

Please, clarify the issue - you feel uncomfortable after the language is changed and some elements displayed in English?

**Comment by bestpika** [comment]
@TheHasagi
I change the language to English and I want to see the English UI.
I don't want to see the 正體中文 UI.

**Comment by TheHasagi** [comment]
@bestpika 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by bestpika** [comment]
3.3 nightly 10 is fixed, but I don't know why.
