### ISSUE TITLE
Update translations and filter lists before beta 1

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#3115]
We need to prepare the AdGuard application for beta 1:
- [x] Update translations
- [x] Update filter lists

**Comment by lancelot-moon** [comment]
There are untranslated new phrases in v3.3.
You need to upload new phrases to Crowdin first.

**Comment by artemiv4nov** [comment]
@lancelot-moon new phrases have been uploaded. You can start translate them.

**Comment by lancelot-moon** [comment]
Hi,
https://crowdin.com/translate/adguard-applications/17634/en-zhtw#3908722
Enter login -> Enter your AdGuard account

https://crowdin.com/translate/adguard-applications/17634/en-zhtw#3908682
Can I only translate one?
There is no plural type for most words in Chinese grammar.
裝置 = device = devices

**Comment by lancelot-moon** [comment]
It seems a bug.
The translations for extensions aren't correctly shown from previous nightly versions.
Please go to check your program codes. Thanks.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/HNDVBsy.jpg)
</details><br/>

**Comment by lancelot-moon** [comment]
@ameshkov 
What happened on Crowdin?
You uploaded and deleted all translations for AG for Android.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/unILxBS.png)
</details><br/>

**Comment by artemiv4nov** [comment]
@lancelot-moon We are on the way to some restructuration, please, keep calm.

**Comment by lancelot-moon** [comment]
@ameshkov 
@artemiv4nov 

1. There is a bug.
The translations for extensions aren't correctly shown **from previous nightly versions**.
In the latest v3.3 nightly 12 (69), this also isn't fixed.
Please go to check your program codes.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/HNDVBsy.jpg)
</details><br/>

2. Please also update the translation for "Disable AMP".

3. The new English phrase isn't fluent, especially this sentence: `Please unbind one of the license keys from its current device`.
https://crowdin.com/translate/adguard-applications/17634/en-zhtw#3908752
`The number of assigned license keys in this account has been maxed. Please unbind one of the license keys from its current device or purchase a new one.`

Can we use **multiple AdGuard** in **one Android device** generally?
Note that you use `from its current device`.
`Please unbind one of the license keys from its current device`
-> `Please unbind the license key from one of the devices`

I suggested this in the comment on Crowdin.
`The number of licensed devices in this account has been exceeded. Please unbind the license key from one of the devices or extend the number of devices. Or purchase another new license key.`

Will you cancel the activation method of inputting a license key?
I mean to login into AdGuard account for activating Premium, right?

Does a license key allow over 9 devices in your future licensing?
Ex: In the situation, original Premium license 5 PC + 5 Mobile -> 10 devices.
On telegram, Andrey: `all old licenses are unaffected don't worry`
Well, maybe you'll keep the original status for old licenses.

If not, assume that Premium license 5 PC + 5 Mobile will be converted to 10 devices.
Will it show the warning when a user uses his license key on the 10th device?
`The number of assigned license keys in this account has been maxed. Please unbind one of the license keys from its current device or purchase a new one.`
As what I know, the max number of devices in a key is 9.

Thanks.

**Comment by artemiv4nov** [comment]
Thanks a lot, @lancelot-moon !
We fixed it already, you can touch it in the next nightly.

Also, If you have any issues with extensions, you can write a task on https://github.com/AdguardTeam/DisableAMP

**Comment by lancelot-moon** [comment]
@ameshkov 
For the 3rd point, assume that you're a **newbie who doesn't know AdGuard licensing at all**.
https://crowdin.com/translate/adguard-applications/17634/en-zhtw#3908752
`The number of assigned license keys in this account has been maxed. Please unbind one of the license keys from its current device or purchase a new one.`

`Please unbind one of the license keys from its current device`
a. The sentence lets me feel that multiple AG license keys can be used on ONE Android device.
b. Assume that I have a license key for 2 devices. I use the license key on the 3rd device.
It shows the warning: `Please unbind one of the license keys from its current device`.
There will be many question marks on my face.
It doesn't let me activate Premium on my 3rd device.
Why does it ask me to unbind one of the license keys from the current device?

Please modify this at least.
`Please unbind one of the license keys from its current device`
-> `Please unbind the license key from one of the devices`

**Comment by artemiv4nov** [comment]
@lancelot-moon after all, we decided to keep it as now.

**Comment by lancelot-moon** [comment]
I don't know if the warning will show when slots in one key aren't enough.

Assume that a user only have One key.
How to unbind one of the license keys from its current device?
One key is used in multiple device.
It's still one key, not keys.

**Comment by artemiv4nov** [comment]
@lancelot-moon the warning will be shown in the dialog when slots in one key aren't enough.

**Comment by lancelot-moon** [comment]
@ameshkov

So one of the license keys is wrong because the user only has ONE key, not some keys.
You can't say one key in multiple devices is "keys".

I don't know if you understand my logic.

**Comment by lancelot-moon** [comment]
https://crowdin.com/translate/adguard-applications/17634/en-en#3908752
`The number of assigned license keys in this account has been maxed. Please unbind one of the license keys from its current device or purchase a new one.`

I early knew it means to unbind one of the license keys from that license key's current device.
But `Please unbind one of the license keys from its current device` is very not fluent.
For a newbie (not me), it's not understandable.

Assume that a user only has **ONE** license key for multiple devices in his account.
1. A user may only have **ONE** license key in his account, **not have plural license keys**.
So `The number of assigned license keys in this account has been maxed.` is not good.
We can't say ONE license key for multiple devices is **plural** assigned license **keys**.

2. As the above, we can't say **ONE** license key for multiple devices is **plural** assigned license **keys**.
**What's one of the license keys** since a user may only have **ONE** license key in his account?
So `Please unbind one of the license keys from its current device` is also not good, especially it's not fluent.

After all, it talks about releasing a empty slot.
Another translator also thinks it's better to modify the English phrase.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/saNzesP.png)
</details><br/>

B/R

**Comment by lancelot-moon** [comment]
We read its translation by other translators.
For example, the Simplified Chinese translator modified your English phrase in his translation.
https://crowdin.com/translate/adguard-applications/17634/en-zhcn#3908752

1. Because most Chinese character nouns don't have plural types, the Chinese translation of `The number of assigned license keys in this account has been maxed.` isn't very weird.
在此账户中被分配的授权码数量已经达到最大值。
= `The number of assigned license code in this account has been maxed.`, which is suitable for only having one key.
= `The number of assigned license codes in this account has been maxed.`
(Well, I don't why he translated keys as code in Chinese.)

2. 请从该账户当前授权的某一设备上解除绑定授权码或购买新的授权码。
= `Please unbind the license code from the account's current licensed certain device or purchase a new one.`

You can see that some translators think your English phrase isn't suitable.
And we have to modify the English meaning in our translations.

**Comment by artemiv4nov** [comment]
@lancelot-moon , we decided to change this phrase to:
`The number of assigned license keys in this account has been maxed. Please unbind any license key from the device it's been currently used on, or purchase a new license.`

**Comment by lancelot-moon** [comment]
`The number of assigned license keys in this account has been maxed. Please unbind any license key from the device it's been currently used on, or purchase a new license.`
-> `The number of licensed devices in this account has been maxed. Please unbind the used license key from the certain device, or purchase a new license.`

Mine is shorter.

A user may only have one key in his account, not have plural license keys.
One key for multiple devices isn't plural keys.

I don't know why you insist plural keys and don't talk about upgrading a license key for extending the number of devices.
