### ISSUE TITLE
Redesign the Update screen and connect AdGuard Download Manager to all Android versions

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3192]
Well, we have to make up the Update screen again like on the AdGuard 4.0 design templates. Also, we have to extend the AdGuard Download Manager use to all Android versions (now it's working only on Android 11).

Here is the [link](https://share.goabstract.com/b34f6887-6a6b-4e95-a8a0-9f9a9f52aa4c?collectionLayerId=627ba1c0-3a6b-42c5-9180-759db5976061&mode=design) to Abstract.

---
### Archive

Issue Details

AdGuard version:
3.3.81
Filtering mode:
VPN
Device:
Mobiistar Zumbo J2
Operating system and version:
7.0
Actual Behavior

The user has encountered an update problem when using 4G.
If the customer connects to Wi/Fi, the update is performed without any problems.
P.S. Feature: Update over Wi/Fi only is off

Logs in NCloud
HelpDesk ID: 2239621

Video&screenshot with the issue are included in the logs archive.

**Comment by artemiv4nov** [comment]
Well, there is no bug technically, but we can improve the design of the app update.
In my opinion, the progress bar for the app downloading makes sense while the app downloads.

We need to consider this idea.

**Comment by artemiv4nov** [comment]
@ameshkov 
I would like to redesign the Updates Activity during the application update.

Now, when the user touches to "Update" button, the Progress dialog shows and hides only after the application downloaded.

I want to add some thin progress bar with percents ([like this first](https://material.io/components/progress-indicators/) and make the Activity closeable while the app downloads.

If the user not on Updates Activity, we can send the notification or snack about the app downloaded.

**Comment by ameshkov** [comment]
1. The most important question is can we run install the apk in the background? If we can, we should simply implement the auto-update.

2. Regarding the update screen, it is crucial to keep the user there while the download is in progress. That's why we should keep the progress dialog and simply add a progress bar there.

    > Please note, that if auto-update is possible, this point is not that important anymore.

3. There's still a possibility that the user will leave the update activity. The problem is that if they leave the app, we won't be able to run the update apk. This should be handled the following way:
    * apk should be cached and reused next time user tries to run the update
    * apk cache should be cleared on the app exit

**Comment by artemiv4nov** [comment]
Updated the task description.

**Comment by temp272** [comment]
@ameshkov 

>There's still a possibility that the user will leave the update activity.


Users *will* leave the app if the download doesn't finish within 2 or 3 seconds. I'll leave an app in this case and do something else until it finishes its downloading. That's what I do while using the Play Store; if the app is only a few megabytes I stay in Play Store otherwise I leave the Play Store to do something else. AdGuard doesn't finish its update downloading quickly; it takes time, and users *will* leave the app, and I in fact did leave AdGuard while it was downloading recently (I am a new user, but I think I know the Android UX a bit, and as soon as the app update appeared and it didn't download within few seconds, my natural impulse was to leave the app at that moment) and the download failed, I had to download it again. 

One thing if possible we can do is: If the user leaves the app, as you say cache the APK, and after update download finishes give toast ( I don't think toasts are a good UX always, I'm not sure if this should be implemented) or a notification, and when user opens AdGuard show an update icon on the AdGuard homescreen so that they know an upstate is pending and they can update the app. These are very rough thoughts. But my point was that users will leave the app if it doesn't download within a few seconds.

**Comment by ameshkov** [comment]
Yeah, giving a notification makes total sense, updated my comment

**Comment by TPS** [comment]
> 1. The most important question is can we run install the apk in the background? If we can, we should simply implement the auto-update.

@ameshkov No-interaction auto-update is now _possible_ (I've 1 app — [FFUpdater](https://github.com/Tobi823/ffupdater/commit/f10d54cefd9f334f6499c47667f6cf4ff0a41431) — that implements it flawlessly), but very tight parameters must be met, most notably targetting Android 12+.  See some details @  https://www.xda-developers.com/android-12-alternative-app-stores-update-apps-background/.

**Comment by TPS** [comment]
@ameshkov I haven't noticed any improvement re: background auto-update (as re-quoted below).  Is that still being evaluated?

> > 1. The most important question is can we run install the apk in the background? If we can, we should simply implement the auto-update.
> 
> @ameshkov No-interaction auto-update is now _possible_ (I've 1 app — [FFUpdater](https://github.com/Tobi823/ffupdater/commit/f10d54cefd9f334f6499c47667f6cf4ff0a41431) — that implements it flawlessly), but very tight parameters must be met, most notably targetting Android 10+.  See some details @  https://www.xda-developers.com/android-12-alternative-app-stores-update-apps-background/.
