### ISSUE TITLE
Add bank apps to exclusion list 

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3196]
App:
>- ru.simpls.mbrd.ui
https://play.google.com/store/apps/details?id=ru.simpls.mbrd.ui.beta&hl=ru>

**Comment by artemiv4nov** [comment]
We have to add the `ru.simpls.mbrd.ui` package name, also.

**Comment by razz100** [comment]
I second this demand. I recommend banking apps and payment to be in exclusion list by default. They don't show and use ads or trackers anyway. In fact most of these apps get into compatibility issues due to Adguard. I can name many such apps from India such as DBS DIGIBANK, Phonepe, Freecharge etc. So best to exclude these kinds of apps which are free from ads and trackers.

Thanks

**Comment by artemiv4nov** [comment]
@razz100 This task already done in nightly version.
