### ISSUE TITLE
disable app updates, keep filter updates?

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#3260]
hello,
I have some issues with the update:
first of all, when my channel is "release", even though I'm running nightly,
I shouldn't be offered with an option to update to the next nightly in my opinion,
but to update on next release only

secondly,
I'm interested in filter updates,
but I don't want the app to check for app updates,
I would like to do those whenever I want,
if I want,
can you make it possible?

thanks

**Comment by TheHasagi** [comment]
@patrickdrd 

Hello!

For now, do you receive a notification to update to the latest nightly (or new version of nightly is available to update) even if you switch update channel to release being on nightly build?

**Comment by patrickdrd** [comment]
yes, and I have blocked this update with changing the signature,
so I'm getting an update error because the app tried to update to latest nightly,
my channel is release of course

**Comment by TheHasagi** [comment]
Very interesting,

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by patrickdrd** [comment]
how can I collect logs when I have absolutely no idea when it's happening?

once again, it is your software and you should be debugging it, 
not your users,
I don't have time or effort to do anything of those you suggest, sorry, bye

**Comment by TheHasagi** [comment]
@patrickdrd 

If so, this issue is closed because it cannot be reproduced. Also, without the log files we cannot figure out what causes the issue you are facing and there are no same unusual activity of the application is detected/observed.
