### ISSUE TITLE
Add quick access for some features, which are often used by filter maintainers

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3296]
For example, an option in advanced/low-level settings, which add new menu items:
```
* Home
* Settings
* Advanced
   * Filters
   * User Rules
   * Assiatant
   * HAR recording
```
or new screen with frequently used features.

**Comment by ameshkov** [comment]
The problem is that it's not convenient to work with a mobile app **in general**. This is why browsers provide remote debugging capabilities, it's much more convenient to manage everything from a desktop computer.

We could continue trying making the mobile app UI more convenient or we could instead rework it and extract some kind of a "developer tools API" that can be used to implement "remote debugging" capabilities.

Regarding the mobile side of things

We need quick navigation to the following sections:

1. Recent activity
2. User rules
3. Filters
4. DNS User rules
5. DNS Filters
6. Userscripts
7. App Management

Also, a number of "quick actions" would also be useful:
1. Quick switch for HAR recording and debug-level logs
2. Export/import settings

Here's what I suggest:
1. Add an option to enable "Developer Tools" menu through the advanced settings.
2. If the option is enabled, add the following option to the bottom navigation bar.

**Comment by Alex-302** [comment]
It would be good to add a `Proxy settings` (it's easier to switch to Fiddler)
