### ISSUE TITLE
Check how AdGuard works when "always-on VPN" is enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3327]
### Steps to reproduce

1. Open Android settings -> VPN
2. Find AdGuard
3. Enable "always on" and "Block connections without VPN" there
4. Try checking filters updated when VPN is enabled

The problem is that we forcibly disable filtering for our app (to prevent recursion). However, this might be a problem when the VPN is configured to be "Always-ON + Block connections". AdGuard own connections won't go through the VPN so they might be blocked, right?

Marked this as "Waiting for repro". I may be wrong about this, Android might make an exception for the VPN app itself.

**Comment by anonymous-user** [comment]
I cannot reproduce this. I enabled the two VPN options and then checked for filter updates. AdGuard updated two filters.

I am using Android 10 on a Pixel 2 if it makes any difference.

**Comment by TPS** [comment]
I've had https://github.com/AdguardTeam/AdguardForAndroid/issues/2733#issuecomment-549135770 as a problem w/ this since many months.

**Comment by Hazbelll** [comment]
Thought I'd chime in; When "Always-on VPN" is enabled for me, everything appears to continue working as normal, with the exception of the Google Play Store which will show a "You're offline" message with an option to "Retry", but attempting will immediately fail again.

I do not have the other respective Google Play apps installed to test, but I imagine they're the same. I am on Android Version 9 (Pie) using a OnePlus 3T (Model: A3003) without root.

**Comment by Hazbelll** [comment]
Different behaviour observed on Android 10 (Q). The Play Store now works, but images seem to not load unless already cached. Haven't examined further than that.

**Comment by artemiv4nov** [comment]
So, here are the research results.
The AdGuard VPN interface allows work the AdGuard app even if it disallows itself using `Builder.addDissallowedApplications()`. 
Theoretically, our application can work in the "Kill switch" mode.
BUT.
due to the fact that we use a flexible system for configuring network connections, some applications may break. Their network connections may pass by us because the exclusion of specific network addresses from routing is the werewolf side of our flexible system.

Thus, a user can use the "Kill switch" mode but he should bear in mind there is a non-nullable possibility some applications will be broken up.

**Comment by TPS** [comment]
@artemiv4nov I'm not sure that what you wrote explains our experiences.  Could you possibly do so in terms of 1 of those?
