### ISSUE TITLE
When only opening AG v3.4 nightly 7 (23), third-party real VPN will be disconnected.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3338]
Mine is Android 9.
I was using Windscribe VPN.
When only opening AG v3.4 nightly 7 (23) but not enabling AG protection, third-party real VPN will be disconnected.

(You know the bug means AdGuard's local HTTP proxy mode won't be compatible with real VPN.)

**Comment by TheHasagi** [comment]
@lancelot-moon 

Please, record a short clip with the issue and send the debug logs to devteam@adguard.com.

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by lancelot-moon** [comment]
I only opened AG v3.4 nightly 7 (23) app but didn't enable AG protection.
Why should I provide AG's log?
Can you not use any third-party real VPN at your side and reproduce it with AG v3.4 nightly 7 (23)?

**Comment by TheHasagi** [comment]
@lancelot-moon 

True, reproduced now.

**Comment by admitrevskiy** [comment]
Fixed in https://github.com/AdguardTeam/AdguardForAndroid/issues/3416
