### ISSUE TITLE
Latest no night shift cannot save DNS data

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdguardForAndroid#3391]
- **AdGuard version:**
  -V3.4  night 10
- **Filtering mode:**
  vpn
- **Device:**
 oneplus 6t
- **Operating system and version:**
  android 10.0.1
- **Root access:**
  root

Latest no night shift cannot save DNS data

**Comment by thb007** [comment]
![Screenshot_20200327-180748](https://user-images.githubusercontent.com/17548936/77746043-4cbad600-7057-11ea-9215-17fdf513eeaf.jpg)

**Comment by TheHasagi** [comment]
@thb007 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by thb007** [comment]
> @thb007
> 
> To troubleshoot this issue, we need to get additional logs.
> 
> Here's what we need you to do:
> 
> 1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
> 2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
> 3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
> 4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

Has been sent to the corresponding mailbox, please check

**Comment by TheHasagi** [comment]
@thb007 

Got the logs, thank you very much.

**Comment by TheHasagi** [comment]
@thb007 

Please, update to the latest [nightly ](https://agrd.io/android_nightly)and check if the issue still exists.

**Comment by TheHasagi** [comment]
Will be reopened if needed.

**Comment by thb007** [comment]
> @thb007
> 
> Please, update to the latest [nightly ](https://agrd.io/android_nightly)and check if the issue still exists.

ok .Normal use now
