### ISSUE TITLE
Turn OFF Adguard DNS Filter does not works as should

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardForAndroid#3402]
Adguard Android Nightly (lastest) here. 
DNS forwarding set to Cloudflare (1.1.1.1) DOH
DNS filtering applet does not working properly for some sites and at end leaking ads/blocking video streams. Disabling only DNS Adguard's Ads Filters Rules in DNS Applet does not resolve issues with some sites. 
SITES WORKS PROPERLY only when I TURN OFF DNS APPLET in ADG ANDROID APP FOR GOOD. 

@ameshkov regards

CC @AdamWr

**Comment by TheHasagi** [comment]
@FadeMind 

Please, provide any examples from your side.

**Comment by FadeMind** [comment]
Some polish sites like wyborcza.pl or wp.pl leaking ads and EU GDPR cookies.
Xhamster leaking iframes empty boxes from Traffic Stars provider.
I have to whitelisting some domains against unable play content in internal player on polsatnews.pl.

**Comment by TheHasagi** [comment]
@FadeMind 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by FadeMind** [comment]
@TheHasagi this is simple issue: DNS blocking rules are too restricted and at the end leaking ads. Thats why some sites REQUIRED whitelisting some JS stuffs. 
You can simply reproduce this issue:
- enabling default DNS protection
- refresh database in ADG app
- Launch any sites from Poland or others. 
This issue is related only with DNS filtering, and it is gone when I disabling them at all.
