### ISSUE TITLE
app.author.today.authortoday - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3406]
@adguard-bot commented on [Mon Apr 06 2020](https://github.com/AdguardTeam/AdguardFilters/issues/52972)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=app.author.today.authortoday](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dapp.author.today.authortoday)
### Comment
Username: @adri83
> При включение и настройки пропускать через ваше приложение , приложение автор тудей некорректно работает, не видит интернет соединение, пока не нажмёшь на кнопку подключиться и не синхронизируется. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/2qcXhSx.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/867Ah9J.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.1.0
AdGuard version: | 3.3.2 (230)
Stealth mode options: | Hide your search queries
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | disabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>Fanboy's Enhanced Tracking List, <br/>Fanboy's Anti-thirdparty Fonts, <br/>Fanboy Anti-Facebook List<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Simplified domain names, <br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> RU AdList: Counters, <br/>RU AdList, <br/>YousList, <br/>RU AdList: BitBlock, <br/>AdGuard Russian, <br/>(Obsolete) Korean Adblock List

**Comment by Alex-302** [comment]
Reproduced. Cannot be fixed by ad filters.

**Comment by TheHasagi** [comment]
@adri83

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by TheHasagi** [comment]
Closed due to no response from the user.
