### ISSUE TITLE
Message is not delivered/delivering as RCS after update to 3.4 nightly 16

### ISSUE THREAD

**Issue by MPThLee** [AdguardTeam/AdguardForAndroid#3413]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 
  - 3.4 nightly 16
- **Filtering mode:** 
  - Local VPN, High Quality mode
- **Device:** 
  - Samsung Galaxy Note 10+ (Korean Varients)
- **Operating system and version:**
  -  Android 10 (One UI 2.1)
- **Root access:**
  - No

### Expected Behavior
Message with blue box

### Actual Behavior
Message sent with geen box

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20200418-175410_Messages](https://user-images.githubusercontent.com/26970092/79632988-a23d5b00-819d-11ea-9154-563ee22909fc.png)

</details>

### Additional Information

Maybe it's related a `*.connectrcs.com` domains.

RCS is called on Advanced Massaging or Chatting+ in Messgaes app.

It still shows chatting+ icons (The indicator of can communicate with RCS). But It seems not working.

Tried to non adguard user(phone) <-> me. Both side doesn't work with RCS. Seems the blocker of this is me after tring many ways. When i turn off adguard it works well.

**Comment by TheHasagi** [comment]
@MPThLee 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by TheHasagi** [comment]
The issue is closed due to no response from the user. Will be reopened if needed.

**Comment by MPThLee** [comment]
Sorry for late. I didn't saw that comments. But here's update.
Update to New version of ADGuard for Android, 3.4 nightly 18, It works again.

![SmartSelect_20200425-064543_Messages](https://user-images.githubusercontent.com/26970092/80259446-8ca9c300-86c0-11ea-9518-a28bcd41f039.jpg)
(Up is nightly 16, Down is nightly 18)

Dunno why what caused this issue. But it works again.
