### ISSUE TITLE
Proxy setting doesn't work

### ISSUE THREAD

**Issue by sky96111** [AdguardTeam/AdguardForAndroid#3417]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- I am running the latest version
- I checked the documentation and found no answer
- I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.3.3
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - Oneplus7
- **Operating system and version:**
  - 10
- **Root access:**
  - Yes

### Expected Behavior
I enabled proxy in setting to connect PC's local proxy to access google.And proxy works well in system proxy setting.But I can't open google.com and other websites which need PC's proxy to access after I enable proxy in adguard 

### Actual Behavior
Proxy doesn't work and I faild to open websites which need proxy to access.

### Screenshots

<details><summary>Screenshot:</summary>

System Proxy
![Screenshot_20200424-181030.jpg](https://i.loli.net/2020/04/24/bwakof4WjIPcGNg.jpg)
Connection
![Screenshot_20200424-181048.jpg](https://i.loli.net/2020/04/24/HNrwXiV2u76JDAx.jpg)
Adguard Proxy
![Screenshot_20200424-181135.jpg](https://i.loli.net/2020/04/24/H8EgxUdXI5puNjt.jpg)
Connection
![Screenshot_20200424-181424.jpg](https://i.loli.net/2020/04/24/uHAV7YQFw4o9tXg.jpg)
Connection test in Adguard is passed
![Screenshot_20200424-181810.jpg](https://i.loli.net/2020/04/24/8slCNwzk5ogeU34.jpg)
</details>

**Comment by TheHasagi** [comment]
@sky96111 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by mmyz1234** [comment]
Your configuration is wrong.

You need to configure a dns in the configuration file of Clash, then configure this dns in AdGuard.

If you need more help, please join Please join the [Adguard [CN]](https://t.me/Adguard_CN) group which is a unofficial telegram group for chinese user.

**Comment by mmyz1234** [comment]
And configure that Adguard dose not route the traffic of Clash.

**Comment by sky96111** [comment]
> Your configuration is wrong.
> 
> You need to configure a dns in the configuration file of Clash, then configure this dns in AdGuard.
> 
> If you need more help, please join the [Adguard [CN]](https://t.me/Adguard_CN) group which is an unofficial telegram group for chinese user.

What config should I change in Clash?Could you please tell me more information?

**Comment by sky96111** [comment]
Solved.Config DNS procided by clash in Adguard.
