### ISSUE TITLE
com.google.android.googlequicksearchbox

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3420]
@adguard-bot commented on [Fri Apr 24 2020](https://github.com/AdguardTeam/AdguardFilters/issues/54306)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dgoogle++playstore&pcampaignid=APPU_1_LdaiXsTEG46HmwXOwpKYAg](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.googlequicksearchbox%26hl%3Den%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Dgoogle%2B%2Bplaystore%26pcampaignid%3DAPPU_1_LdaiXsTEG46HmwXOwpKYAg)
### Comment
Username: @kklepacz
> I'm signed for Google app beta program. After last update of Google app, any link on Discover tab leads to error attached on screenshots. Page can be loaded if I will Refresh page in top right corner. No issues when AdGuard is disabled.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/h0S3iCZ.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/UDU4Km9.jpg)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/y8eMx0Z.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.3.3 (231)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances

---

@Alex-302 commented on [Mon Apr 27 2020](https://github.com/AdguardTeam/AdguardFilters/issues/54306#issuecomment-620018518)

@kklepacz Hi. Is that address was opened from `com.google.android.googlequicksearchbox` app?

---

@kklepacz commented on [Mon Apr 27 2020](https://github.com/AdguardTeam/AdguardFilters/issues/54306#issuecomment-620028871)

@Alex-302 yes. Discover tab (previously called Google Feed) of `com.google.android.googlequicksearchbox`. I have clicked "You Can Finally Apologize for Being Trash In Overwatch" header (lol btw xD) in linked screenshots. As I mentioned same issue with any header

**Comment by silberstick** [comment]
I'm having exactly the issues.

Clearing data of Google seems to solve the issue temporary, however within a few hours it reverts to the sames state.

I have tried it with multiple DND providers but it's always the issue persists.

**Comment by TheHasagi** [comment]
@kklepacz @sliberstick

Dears,

Update the app for the latest nightly version and check again, got no issues you've described. If the issue still exists please, send the debug logs according to this instruction:

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by kklepacz** [comment]
@TheHasagi I've installed nightly version and I cannot reproduce issue anymore. Seems working fine :) thanks!

**Comment by eezynow** [comment]
I too have installed the nightly and I am no longer experiencing the problem.. thanks!

**Comment by TheHasagi** [comment]
Glad to hear that :) Closed.
