### ISSUE TITLE
https://wiki.freifunk.net/

### ISSUE THREAD

**Issue by larena1** [AdguardTeam/AdguardForAndroid#3422]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  3.4 Nightly 19
- **Filtering mode:**
  - Proxy
- **Device:**
  - 
- **Operating system and version:**
  -  Android 10
- **Root access:**
  -  Yes

**IT DOES ONLY HAPPEN WHEN USING PROXY MODE. WITH VPN MODE THE SITE CAN BE OPENED**

https://wiki.freifunk.net/

This site can't be viewed in Chrome. It just says ERR_CONNECTION_RESET
The URL will also not even show up in the Filtering Log. WIth AdGuard turned off, the site can be viewed.

**Comment by TheHasagi** [comment]
@larena1 
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by larena1** [comment]
It does work now. I did not change anything.
