### ISSUE TITLE
The browser can't use the network if I use adguard+proxy(per-app proxy)

### ISSUE THREAD

**Issue by 1human** [AdguardTeam/AdguardForAndroid#3465]
I have tried v2ray ssr clash etc.  When I use per-app proxy and adguard for browser app, the browser can't use proxy network.
Is this a bug that can be fixed?
System  Android Q

**Comment by TheHasagi** [comment]
@1human 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by 1human** [comment]
[adguard_logs_3.4.120_2606_131049.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/4835199/adguard_logs_3.4.120_2606_131049.zip)

![Screenshot_20200626-131046_Microsoft_Launcher](https://user-images.githubusercontent.com/18576031/85823000-d68d5300-b7ae-11ea-9944-949db782f139.png)
Here is the log file and the screenshot when it goes wrong. Thanks for fixing this.

**Comment by TheHasagi** [comment]
@1human 

In what mode (VPN/Proxy auto/Proxy local) does the AdGuard working? Is the ByPass mode enabled in that v2RayNG enabled?

**Comment by 1human** [comment]
@TheHasagi  In adguard, I am using the local http proxy ,but in V2ray,  neither global nor bypassing mode with per-app proxy enabled,  the browser app can't use the proxy network...  And the adguard works well, most of the adv can be disabled
Maybe this is the v2ray's problem?

**Comment by TheHasagi** [comment]
@1human 

If you can see the blocked/processed request in the filtering log of AdGuard - it's working. Seems like this problem does not relates to AdGuard at all and can be solved in v2ray settings. Closed for now.
