### ISSUE TITLE
Mobile data randomly doesn't work when Adguard is ON

### ISSUE THREAD

**Issue by samit-tandukar** [AdguardTeam/AdguardForAndroid#3471]
#2821 # Issue Details

- **AdGuard version:**
  -  3.4
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Galaxy Note 10+
- **Operating system and version:**
  -  Android 10 (OneUI 2.1)
- **Root access:**
  -  No
 
### Actual Behavior

Mobile data doesn't work randomly when Adguard is ON. There is no issue while using in Wi-Fi connection but network drops randomly while using mobile data. Turning Adguard OFF and ON makes it work again in mobile data for a few minutes but again it drops out.

### Additional Information

Carrier: Optus Australia
OS: Android 10 
Security patch level: June 2020 
Model: Galaxy Note 10+ (unlocked)

**Comment by snappyapple632** [comment]
I am also getting this issue on my OnePlus 7 Pro.

Carrier: Visible Wireless
OS: Android 10
Security patch level: May 2020
Model: OnePlus 7 Pro GM1917

**Comment by TheHasagi** [comment]
@samit-tandukar 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by TheHasagi** [comment]
Did not received any e-mails with the logs. Closed due to no response. Will be reopened if needed.
