### ISSUE TITLE
Problems with data network not receiving push notifications

### ISSUE THREAD

**Issue by Richelieu4771** [AdguardTeam/AdguardForAndroid#3486]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.4 Nightly 4
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy S10 5G
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

A notification is given even in the data network like Wi-Fi network.

### Actual Behavior

On Android 10, after the Android minor update, push notifications don't work in the data network with AdGuard turned on, except for the default apps. The reason AdGuard was because I deleted it and the notification was working properly. A member of the Samsung Members Community said the issue is related to a policy change in Android updates.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by artemiv4nov** [comment]
For a long time, an unexpected problem exists with enabled AdGuard (and any other VPN) and not receiving push notifications.
Unfortunately, there is no explanation of why push notifications didn't receive. Perhaps, the problem is in Google services implementation (like in the situation with a Download manager).

It would be good to collect debug logs with the exact timeline and exact actions line.

**Comment by JhonHuGit** [comment]
I am having the same problem. FCM diagnotics shows a frequent disconnection to google servers. This only happens when the screen is off with celular network. I have tried to add fcm servers such as mtalk.google.com and so on to whitelist, but there is no effect. 

I think there may be something in AG that breaks the communicaiton with google servers, but I am not sure of it.

**Comment by artemiv4nov** [comment]
Well, I will think the problem has gone in the 4.0 version
