### ISSUE TITLE
The Wine Society email links blocked by AdGuard

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3507]
### Issue Details

- **AdGuard version:**
  -  3.4.120
- **Filtering mode:**
  -  VPN
- **Device:**
  -  Samsung SM-G955F
- **Operating system and version:**
  -  9
- **Root access:**
  -  No

### Actual Behavior

When the user clicking on links in The Wine Society email he gets an Invalid Request error instead of the webpage opening.

> I clicked on links in emails from the same company four times, all about 12.44, just 20 minutes ago.

### Additional Information
- Disabling extensions does not solve the issue

**Comment by Chinaski1** [comment]
Time: 12:44
Logs are added to NCloud.

**Comment by Revertron** [comment]
The Wine Society is very cunning, and they desperately need those `utm_*` tracking parameters that are cut out by our Stealth mode. The user can add a rule to disable param stripping on that domain: `@@||http://content.email.thewinesociety.com^$removeparam`.

**Comment by artemiv4nov** [comment]
@akmLaVx Hi!
So, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by artemiv4nov** [comment]
Closed the issue, please re-open it if you need.
