### ISSUE TITLE
Android 11: Podcasts, Gmail and Drive don't work correctly

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#3516]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
- **AdGuard version:**
  - v3.5 nightly 5
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 3
- **Operating system and version:**
  - Android 11 beta 2
- **Root access:**
  - No

### Actual Behavior

*Podcasts:* I can't download any podcast.
*Gmail:* I can't download email attachments.
*Drive:* After 5 minutes when Drive began to download a file, I got an error about "Download failed".

**Comment by admitrevskiy** [comment]
This issue depends on DownloadManager

Initially we had to exclude com.android.providers.downloads [from the filtering](https://github.com/AdguardTeam/AdguardForAndroid/issues/3355)

DownloadManager tried to bind to Wi-Fi bypassing our VPN and of course failed

Android 11 DP behaves completely differently and [no apps inside a VPN can use DownloadManager](https://github.com/AdguardTeam/AdguardForAndroid/issues/3517)

[Here](https://issuetracker.google.com/issues/163573415) is issue for Android team

For now it looks like DownloadManager is trying to bind to an active network and since VPN is running it's considering as an active network

As a result we should not exclude downloads provider from VPN for Android R
