### ISSUE TITLE
Breaks Textnow

### ISSUE THREAD

**Issue by Githubadamsh** [AdguardTeam/AdguardForAndroid#3518]
Using latest adguard but cannot dial out using textnow when adguard is on. Using default adguard filters and settings. Under apps mgmt, protection for textnow is already off.

**Comment by TheHasagi** [comment]
@Githubadamsh 

Please, provide the link to the app.

**Comment by Githubadamsh** [comment]
https://play.google.com/store/apps/details?id=com.enflick.android.TextNow

**Comment by TheHasagi** [comment]
@Githubadamsh 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by TheHasagi** [comment]
Closed due to no response.
