### ISSUE TITLE
m.31bz.org - ad domain is not visible in filtering log and cannot be blocked

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3524]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.5 n7
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Xperia
- **Operating system and version:**
  - Android 8
- **Root access:**
  - no

### Expected Behavior

`https://c.sysycloud.com:442/cv/?id=16&r=10` is blocked by `||sysycloud.com^` (Chinese filter)

### Actual Behavior

domain is not blocked and even not visible in the filtering log. You can check it using Chrome remote debugging.

**Comment by admitrevskiy** [comment]
The problem here is the port being used. We do not filter 442 port by default, so this connection is bypassed, and the only one message in the filtering log is TCP connection.
For now the only one workaround is to add 442 into `pref.filtered.ports` in Low-Level settings, but I don't think if it's a good idea since `sysycloud` may change port to 441 and we will return to the starting point and end up filtering all the ports.

**Comment by infinitewaveparticle** [comment]
I like the idea of filtering all ports! :)
