### ISSUE TITLE
DNS Filtering does not work properly on Realme devices

### ISSUE THREAD

**Issue by BlitW0** [AdguardTeam/AdguardForAndroid#3549]
### Issue Details

- **AdGuard version:**
  - v3.4.120
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Realme 1, Realme C2
- **Operating system and version:**
  - ColorOS 6 based on Android 9
- **Root access:**
  - No

### Expected Behavior

After a DNS query is blocked, the device should not be able to connect to that domain since it does not have the address of the domain.

### Actual Behavior

In the logs, after a DNS query is blocked, another web request appears with the blocked domain. This web request inexplicably has the remote address of the blocked domain. There is no private DNS option in ColorOS 6 settings, so I don't know why the custom DNS in Adguard is not working.

### Additional Information

Custom DNS is set to Cloudflare Regular.

**Comment by TheHasagi** [comment]
@BlitW0 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by zzebrum** [comment]
reopen if needed.

**Comment by BlitW0** [comment]
Currently don't have the time to collect logs, but I fixed the issue by changing `pref.dns.blocking.type` to 2 instead of 0. I think that returning `NXDOMAIN` does not work correctly for Realme devices, but it is just speculation.
