### ISSUE TITLE
In-app battery usage tracker not working when you turn it on through widget

### ISSUE THREAD

**Issue by josephmalonda** [AdguardTeam/AdguardForAndroid#3621]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✔ ] I am running the latest version
- [✔ ] I checked the documentation and found no answer
- [✔ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** **v3.5.1 (65)**
  - 
- **Filtering mode:** **Local VPN**
  - 
- **Device:** **Vivo S1 Pro**
  - 
- **Operating system and version:** **Android 10 | Funtouch OS** _(version PD1945F_EX_A_6.8.21)_
  - 
- **Root access:** **NO**
  - 

### Expected Behavior
- **The in-app battery usage tracker should also track the app usage when I turn the AdGuard on through its widget**.

### Actual Behavior
- When I turn AdGuard on through its widget, **the in-app battery usage tracker is not tracking the app usage**. No tracked statistics shown when I try to check it. Unless I manually turn it on through the app, leave the app opened and running in the background.

### Screenshots

![Screenshot_2020_1004_202020](https://user-images.githubusercontent.com/65003163/95015852-f4a60180-0681-11eb-8701-107da2f1a324.jpg)

<details><summary>Screenshot:</summary>
I've been using AdGuard for hours on my smartphone (I turned it on through its widget and never opened the app.) and it does not track the battery usage. While the built-in battery usage tracker in android does track some of the app usage.

</details>

**Comment by josephmalonda** [comment]
This is to add that I have further observed the in-app battery usage tracker on my phone. 
- **It also does not properly track the battery usage when I manually open the app and turn the protection on through it.**

**Comment by TheHasagi** [comment]
@josephmalonda 

It is ok on my side, the count is going as it should be. 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by TheHasagi** [comment]
Closed due to no response. Will be reopened if needed.
