### ISSUE TITLE
Block Youtube App Ads So Fucking Easy

### ISSUE THREAD

**Issue by stralpt2** [AdguardTeam/AdguardForAndroid#3628]
You Just Uninstall Adguard From Your Device and Install Adclear,And boom! you are free from Youtube Ads no-root,and this app are absolutely free,this is a hidden gold that adguard can't do over a months,
Download Link: adclear.com

this is the answer that say "Unfortunately, the situation has not changed. Nobody can block ads in the youtube app unless you use a patched youtube app. You can still watch youtube in a browser."

**Comment by stralpt2** [comment]
why adguard not listen my request over a month?

**Comment by Pixel11213** [comment]
@stralpt2 Hi, fellow user here. It is really not possible to block ads in the official Android YouTube app. It is so because the YouTube app doens't trust user-inatalled certificates, for this you need root access to move the certificate to the system store and it also needs a bit more setup from the users' side after that AFAIK. I understand the frustration you are facing but unless you use a patched YouTube app like [YouTube Vanced](https://vancedapp.com/) or [NewPipe](https://newpipe.schabi.org/) or use the YouTube website it is really not possible to block ads on YouTube. I also want to block ads on YouTube as they have become more and more frustrating over these fee months but nobody can block ads on YouTube on Android (well, Google can, if you purchase the YouTube Premium subscription). It is a technical limitation introduced by Android itself (https://adguard.com/en/blog/android-nougat-release-and-what-does-it-mean-for-adguard-users.html). I hope you can understand.


The link you gave me looks shady as they claim to block

**Comment by stralpt2** [comment]
it is already tested and work, Ads On Youtube App Are Trully Blocked although there is still a banner but at least they can block Youtube Ads When Watching A Videos And Intrusive Watching Experiences are gone.

you can try their app, maybe your team can get a refferences, i know Youtube App Ads Are Encrypted But hey No System Are Perfectly Safe. 

#PleaseTryTheirAppMaybeYourTeamCanGetRefferences

**Comment by stralpt2** [comment]
Why i still want Adguard To Block youtube app ads and why i just don't use adclear? because adguard are more advanced features and Nice UI,i like it but there still one big problem i hope it becoming true.

**Comment by stralpt2** [comment]
oh.. hell should i make a video for this?, come on trust me, i've been tested the app on a hundread of Youtube Videos. even on latest version youtube app, it working fine.
at first run adclear you need to restart your Youtube app,till the ads are blocked.

Once again It this possible to do

**Comment by stralpt2** [comment]
@Pixel11213 adguard wanna give up?

**Comment by ameshkov** [comment]
AdClear is not able to block Youtube ads without a using companion called "Dubbel". That companion app is basically a virtual machine that modifies YT. Tbh, I am failing to see what's the difference between this and using NewPipe or Vanced.

Oh, and note that AdClear collects and sells your browsing history to third-parties.
