### ISSUE TITLE
Using sharedrop.io to share files does not work with AdGuard in VPN mode

### ISSUE THREAD

**Issue by anonymous-user** [AdguardTeam/AdguardForAndroid#3639]
### Issue Details

- **AdGuard version:**
v3.5.1
- **Filtering mode:**
Local VPN
- **Device:**
Google Pixel 2
- **Operating system and version:**
Android 11
- **Root access:**
Yes

### Expected Behavior

Sharing files via sharedrop.io should work and I should be prompted to accept the file (on mobile)

### Actual Behavior

sharedrop.io gives me a message saying "It was not possible to establish direct connection with the other peer."

### Screenshots

![image](https://user-images.githubusercontent.com/4295854/96542103-3e801180-1256-11eb-9088-0da03f21c20f.png)

### Additional Information

To reproduce the issue have a phone and PC on a local network. Open a browser on both devices and navigate to sharedrop.io. Confirm that both devices can see each other. Attempt to send a file from PC to mobile by drag and dropping a file.

Current workarounds:

1. Disabling AdGuard entirely
2. Disabling AdGuard protection for the browser (on phone)
3. Using local proxy mode instead of local VPN

**Comment by max19-8** [comment]
On their website it is clearly stated that it will not work with the VPN connection turned on. Since some random STUN IP addresses are used for file exchange, the sharedrop.io site itself will not help us to add to the exceptions, and we cannot determine in advance the addresses at which files will be exchanged, so we decided to close the task
