### ISSUE TITLE
AdGuard Ads Not Blocking on YouTube App

### ISSUE THREAD

**Issue by seyoon20087** [AdguardTeam/AdguardForAndroid#3678]
### Issue Details

- **AdGuard version:**
  - 3.5.2
- **Filtering mode:**
  - Local VPN (AdGuard DNS)
- **Device:**
  - Samsung Galaxy A7 (2018)
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

I thought AdGuard for Android can also block ads on the YouTube app

### Actual Behavior

Ads are still displaying on the YouTube app

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20201205-100129_YouTube](https://user-images.githubusercontent.com/24852454/101229210-83ff7d80-36e2-11eb-9cd7-dbd04669dddc.png)
![Screenshot_20201205-104420_YouTube](https://user-images.githubusercontent.com/24852454/101230463-c75cea80-36e8-11eb-902d-8aaff83afab8.png)

</details>

### Additional Information

I want all ads on the YouTube app to be blocked

**Comment by Ruslanrem** [comment]
@seyoon20087 Hi, unfortunately at this moment it is impossible to completely block pop-up ads in the YouTube app, because YouTube app does not allow working with other certificates. 

 But you can block ads in the YouTube videos - when playing a video, click on the “share” button under the video, select adguard from the list of applications. The video will play without ads. 

More details about blocking ads in the YouTube app:  https://kb.adguard.com/en/android/solving-problems/youtube-ads

**Comment by seyoon20087** [comment]
>  But you can block ads in the YouTube videos - when playing a video, click on the “share” button under the video, select adguard from the list of applications. The video will play without ads.

There is no "AdGuard" app in the list
