### ISSUE TITLE
Popular VPN protocols support for Proxy based connections

### ISSUE THREAD

**Issue by devlamania** [AdguardTeam/AdguardForAndroid#3682]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [N] I checked to make sure that this issue has not already been filed

### Problem Description

In Android (unrooted), only one VPN can be used at a time. While I want to use the superior cosmetic treatments with adblocking that only Adguard offers - want to use a VPN as well which can go along.
SOCKS5 is the safest proxy protocol available with Adguard.
So far I was using NordVPN SOCKS5 Proxy servers, but their SOCKS5 servers are completely messed up right now. They are evidently unwilling to fix that and there are not many reputable VPN providers which provide SOCKS5 either even if I chose to change my VPN provider.
I use my phone for office and personal financial usage as well. It is imperative I use a VPN, but I want to use Adguard as well while for obvious reasons I don't want to root my device to achieve that.  

### Proposed Solution

Need a way to use Adguard and VPN same time in Android devices without having to root it. 
OpenVPN (UDP/TCP) are becoming more and more popular. It might be a good idea to explore if that can be used.

### Alternatives Considered

Whatever that is possible. Any open source proxy solution which at least few VPN providers support or likely to support more in future, or any method to filter ads and apply cosmetics once the packets already been received to localhost via VPN. Whatever that can keep cosmetic functionalities with adblocking.

**Comment by Neon329** [comment]
I bought AdGuard Premium to block ads primarily in browsers (since it is mostly useless for other apps which don't trust user installed certificates), but AdGuard completely takes away the ability to use VPNs (as Android doens't allow two simultaneously running VPNs). There's AdGuard VPN but I cannot afford it and it only has 3GB of free bandwidth allowance that is not enough for me. Currently I use ProtonVPN and keeping AdGuard VPN installed if I need to use AdGuard and VPN simultaneously.

I'm currently thinking of uninstalling AdGuard Premium from my device since it has essentially taken away the ability to use other VPNs and I am thinking of using Firefox for Android as it has support for AdGuard extension which seems to work just fine. I hope they don't take the free extension away or cripple its functionality to promote AdGuard Premium (I don't think they will) but they are still a business, I'm not sure what they'll do. 
___

@devlamania if you need adblocking with cosmetic filtering support in browsers then I suggest you use **Kiwi browser** or **Firefox for Android** with extension; since about:config isn't available on the Firefox's stable channel and security certificates also cannot be installed on it currently. **Or** if you can pay for VPN then maybe consider using AdGuard VPN (I'm essentially doing marketing for AdGuard VPN now, don't I? Lol)?

___ 

If someone from AdGuard is reading this, I request them to please find a solution to this problem somehow, if possible. VPNs are very essential.

**Comment by Ruslanrem** [comment]
@devlamania you can use Adguard VPN with Adguard adblocker in integrated mode (without rooting device), 
also you can try to use adblocker with another VPN providers:
https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy
