### ISSUE TITLE
Adguard DNS filtering resolve IPv6 records when using IPv4 proxy and internet

### ISSUE THREAD

**Issue by clatteringmarion** [AdguardTeam/AdguardForAndroid#3695]
This issue appeared when Adguard Android is set as VPN service and Clash for Android as proxy server (localhost port) with Adguard DNS filtering turned on and only IPv4 (in reality) are available.

Most of the times Adguard is working correctly, DNS is resolving A records only and pass it along to Clash proxy server. However, issues like this (see screenshot 2) happen and Adguard suddenly would resolve IPv6 records ( Filtering Log in Adguard showed Adguard resolved IPv6 for some domains, instead of IPv4 ) and pass that to proxy, which neither the proxy nor my internet connection support IPv6. This would result in error messages "IP version error" in my proxy software log, which caused the connection won't be handled correctly.

I'm not sure why or how Adguard behave in this way, and it's random but not rare. Most of the times, restarting Adguard would resolve the issue (causing it to send IPv4 address to Clash proxy).

### Screenshots
<details>
  <summary>Screenshot 1 (Clash for Android in use as VPN service, adguard paused)</summary>
  
![image](https://user-images.githubusercontent.com/59781847/102334519-a9b04080-3f86-11eb-8003-5f2db1d25c3a.png)
</details>

<details>
  <summary>Screenshot 2 (Clash for Android in use as proxy service, adguard in use as VPN service)</summary>

![image](https://user-images.githubusercontent.com/59781847/102334852-10cdf500-3f87-11eb-8bf3-10345b2c6d6b.png)

</details>

Information | value
-- | --
Platform: | Android Android 10 OneUI 2.5
AdGuard product: | AdGuard for Android v3.5.2
Browser: | Firefox Mobile
Stealth mode options: |  
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | disabled
DNS requests blocking: | enabled
Filters: | Ad Blocking: AdGuard Base, AdGuard Mobile Ads, EasyList, Peter Lowe's Blocklist
Other extensions used: | Clash for Android (a proxy software)

**Comment by sfionov** [comment]
By default, AdGuard has IPv6 on VPN interface always enabled. There are two options to change it:
1) You may disable IPv6 by turning on "pref.vpn.ipv6.disable" advanced option.
2) Or you may disable "pref.vpn.disable.reconfigure" advanced option which is enabled by default (because some firmwares like on Samsung S8 may hang on VPN reconfiguration). If this option in enabled, IPv6 is always enabled. If this option is disabled, IPv6 will only be enabled on VPN interface if it is enabled on active network.

However, IPv6 on VPN interface usually doesn't lead to problems even if there are no IPv6 connectivity.
Thats because AdGuard sends ICMP unreachable message to sender, and most of software is happy with it.
However, when using outbound proxy, AdGuard may expect different error codes to send "host unreach" to the host.

I recommend to use (1) if you proxy doesn't support IPv6. 

On our side, we'll check that Clash error code for missing IPv6 is handled correctly.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1393](https://github.com/AdguardTeam/CoreLibs/issues/1393) via [**ZenHub**](https://www.zenhub.com/)
