### ISSUE TITLE
AdGuard breaks Google Sync

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3701]
### Issue Details

- **AdGuard version:**
  -  3.6.1
- **Filtering mode:**
  -Local VPN
- **Device:**
  - "manufacturer=Google model=Pixel 5 brand=google version=11 security_patch=2020-12-05"
- **Operating system and version:**
  -  Android 11
- **Root access:**
  - No

### Reproduction

When I have AdGuard enabled on my phone, in less than 24 hours Google
account sync hangs and it's impossible to even start it manually ("Settings
-> Accounts -> [My account] -> Account sync -> 3 dots menu -> Sync now"
simply does nothing). I have to reboot my phone to unblock it but in less
than 24 hours the problem reoccurs.

### Expected Behavior

AdGuard shouldn't break synchronization in Google services

### Actual Behavior

AdGuard shouldn't break synchronization in Google services

### Screenshots

Not applicable

### Additional Information

Logs under helpdesk id 2292222

**Comment by Skwara** [comment]
Correction: I don't have to restart the phone. Disabling AdGuard also works.

**Comment by Chinaski1** [comment]
Hello there!

We starting to investigate your issue. But I would like to ask you one more thing.
For the purity of the experiment, you should try to turn off the DNS function.
Also, disable third-party filters (leave only the specified ones):
- AdGuard Mobile Ads filter
- AdGuard Base filter
- AdGuard Tracking Protection filter
- AdGuard Social Media filter

**Comment by Skwara** [comment]
Hello,

I already tried disabling DNS and it didn't help. I will also try leaving only the filters you specified but because I'm not able to reproduce the issue on demand I will have to leave it for a while and observe.

Additionally I would like to share my recent finding about the issue. I managed to find a workaround. I disabled AdGuard filtering for the following apps:
- Android OS,
- Android Services Library,
- Gmail,
- Google,
- Google Connectivity Services,
- Google Contacts Sync,
- Google Play Store,
- Google Support Services.
Since I did that the problem stopped occuring. I'm not sure disabling which of these apps helped but checking them one at the time would take around a day for each so I decided the check them all. Maybe you have an idea how to reproduce the issue on demand so I will be able to test this quicker?

So, to be able to check if the problem accurs after enabling only the filters specified by you I will reenable filtering for each of those apps one at the time and check if the issue comes back (it might take some time as it's not easy to reproduce the issue). When I will establish which one is responsible for syncing I will start testing the filters.

It would help me if you could tell me which one of those apps is responsible for syncing or maybe you have an idea I could try to reproduce the issue on demand.

**Comment by Skwara** [comment]
I'm trying to reproduce the issue and I found out that the problem likes to occur around the time when I'm switching from home WiFi to mobile connection. In previous cases the problem also has been occuring when leaving the house so I think I have a lead.

**Comment by Chinaski1** [comment]
@Skwara, Hello again. 

Sorry for the late reply, you know, it's New Year's holidays :)

You can try one of these methods. They are both in AdGuard settings -> Advanced -> Low-level:

1) Remove 1000 and 1001 from **pref.excluded.apps**

If first method doesnt help:

2) Disable these 2 features:
- pref.vpn.disable.pause
- pref.vpn.disable.reconfigure

**Comment by Skwara** [comment]
@Chinaski1 Hi,

I've been testing method no. 1 for a couple days and everything seems fine. Can you explain what exactly I'm disabling by removing those numbers from the preferences?

**Comment by Skwara** [comment]
Unfortunately I was to quick with my assumptions. Yesterday the sync stopped and is not coming back even if manually triggered. It again happened when I disconnected from home WiFi and have been using mobile connection and a WiFi hotspot (a bit of both). What's interesting is that I can see the hour of the last performed sync and it's not around the time I disconnected from the home WiFi but rather when I came back and reconnected after using mobile connection and WiFi mobile hotspot.

I will try the second method and post the results.

**Comment by Chinaski1** [comment]
I am closing this task as the user has not responded for a long time.
Reopen it if necessary.

**Comment by Skwara** [comment]
@Chinaski1 I think there is a misunderstanding. You state that I haven't responded but there are 2 responses from me right above your comment. In the first response I asked about what I'm disabling by removing those numbers. I would like to understand that. In the second one I stated that the problem was not fixed by the first method and that I'm trying the second one and underlined that disabling AdGuard is a workaround, but not a fix.

**Comment by Chinaski1** [comment]
Oh, sorry.
I Re-opened the task.

**Comment by Chinaski1** [comment]
Hello @Skwara 

We have made changes to the filtering rules, so it looks like the issue has been solved.
Please update the filters and check if the synchronization issue recurs?

**Comment by Skwara** [comment]
Hello @Chinaski1 

Can you tell me what do you mean by updating the filters? Do I have to do something more than updating the app itself?

**Comment by Chinaski1** [comment]
Press the [two arrows](https://uploads.adguard.com/Chinaski23t55.png) on the screen's main menu.

**Comment by Skwara** [comment]
Thanks. I will test it for the following days and will report back.

**Comment by Skwara** [comment]
@Chinaski1 After several days of testing the issue haven't come back. It looks like it's fixed.

**Comment by Chinaski1** [comment]
Glad to hear it!

So I closing this task
Reopen it if the issue reproduces again.
