### ISSUE TITLE
Question: How to monitor HTTP Auto-Proxy Mode Inbound connections via IPTables?

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdguardForAndroid#3706]
This isn't a feature request or a bug report, but a question. On rooted Android devices AdGuard can work in HTTP Local Auto-Proxy mode. That works best when combined with a non-local VPN connection. In HTTP Auto-Proxy Mode, most inbound connections (highest packet number) use ADGUARD_INPUT IPTable chain, but ADGUARD_INPUT tables show only 2 rules with REJECT WITH TCP RESET.  

How do I use IPTables to look into what INPUT connections were accepted and/or rejected and/or dropped by AdGuard's HTTP Proxy?

**Comment by sfionov** [comment]
Auto-proxy mode is for filtering outbound connections. AdGuard doesn't support filtering of neighbor devices (including tethering clients) in auto mode.

**Comment by EntropySmoke** [comment]
That is strange because ADGUARD_INPUT gets the highest number of INPUT packets. The devices I test are WiFi-only (without data/LTE/SIM-cards), each WiFi connection uses Layer-2 isolation for each device, WiFi Direct is fully disabled, tethering is also disabled entirely. IFCONFIG only shows packets for Tun0 (used by OpenVPN Connect client) and WLAN0. 

Here are the screenshots of what I mean:
[](https://i.ibb.co/Cv3jTVb/Ad-Guard-Input1.png)
[](https://i.ibb.co/7zcHxvC/Ad-Guard-Input2.png)

The top screenshot shows many input packets for ADGUARD_INPUT and the bottom screenshot shows no packets for ADGUARD_INPUT.

**Comment by sfionov** [comment]
ADGUARD_INPUT chain has only two rules:
1) reject incoming connections to transparent proxy port which should be bound on [::] due to redirecting method
2) otherwise return back to INPUT

So, for every packet, netfilter will go to ADGUARD_INPUT, and then will return to INPUT, so it is actually no-op for most packets. We use separate table to isolate AdGuard rules from the other ones.

**Comment by EntropySmoke** [comment]
Thanks! Are there any plans to switch to local SOCKS5 Auto-Proxy to filter both TCP and UDP and use online VPN encryption at the same time instead of using AdGuard local VPN + SOCKS5 online proxy?

**Comment by sfionov** [comment]
You already can redirect application TCP traffic to SOCKS5 when in auto-proxy mode, if you use SOCKS5 outbound proxy in AdGuard.
However, UDP traffic is not redirected in that case. There is no plan to implement such redirection in the near future because it requires separate network daemon running under superuser.

**Comment by EntropySmoke** [comment]
Thanks and sorry about my new thread with the same question (that was already answered) about local SOCKS5.

How do I view the separate HTTP Proxy AdGuard table you mention? ADGUARD_INPUT rule in general INPUT chain shows many accepted packets, but ADGUARD_INPUT table only lists 2 "Reject With TCP Reset" rules, both of them for localhost interface and the count of rejected packets is always 0. ADGUARD_INPUT table doesn't show how many inbound packets are rejected by the proxy and returned. I want to make sure my device drops all packets for specific protocols and my general INPUT and OUTPUT table rules already do that, but I don't know what ADGUARD is doing... I do understand if its a proprietary property, mechanics of which are not meant for disclosure.
