### ISSUE TITLE
Local VPN Connection Star UP Slowly

### ISSUE THREAD

**Issue by AuroraStar05** [AdguardTeam/AdguardForAndroid#3723]
### Issue Details

After long-term used the local vpn star up slowly

- **AdGuard version:**
  4.0 Nightly 9
- **Filtering mode:**
  Local VPN(Auto/Manual)
- **Device:**
  MEIZU 17 Pro
- **Operating system and version:**
  Android 10
- **Root access:**
  No

### Expected Behavior

When I click the main switch,VPN will start up,but slowly

### Actual Behavior
When I click the main switch,VPN will start up,but slowly,sometimes maybe not to create a local vpn connection

### Screenshots
I don't have it,but I have a screenrecord,host on my onedrive,link is blow
https://netlook1-my.sharepoint.com/:v:/g/personal/yangshuo_netlook1_onmicrosoft_com/Ec0HWUlQN-VDssiv_r6posEBmk2T0x4T6XBFGcvvZN3JZA?e=aQfd0W

</details>

**Comment by Chinaski1** [comment]
Hello @AuroraStar05 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment]
@AuroraStar05 
Please clarify, is the issue still recurring?

**Comment by AuroraStar05** [comment]
> @AuroraStar05
> Please clarify, is the issue still recurring?

Yes

**Comment by Chinaski1** [comment]
Then please follow the instructions that I send above.

**Comment by AuroraStar05** [comment]
> Then please follow the instructions that I send above.

I sent the log on last Thursday

**Comment by AuroraStar05** [comment]
> Then please follow the instructions that I send above.

I sent the log on last Wednesday

**Comment by AuroraStar05** [comment]
@Chinaski1 I sent it again,just now

**Comment by Chinaski1** [comment]
Logs received, thank you

**Comment by Chinaski1** [comment]
@AuroraStar05 
Hello again!
Could you please try to reproduce the issue on the release version and check if it persists there?
- Download link: agrd.io/apk

**Comment by AuroraStar05** [comment]
@Chinaski1 it's gone,but this problem seems always happened after a short time to used

**Comment by AuroraStar05** [comment]
@Chinaski1 and when I reinstall it,this issue will go away

**Comment by Chinaski1** [comment]
In that case, I'm closing the task.
Reopen it if the issue occurs again.
