### ISSUE TITLE
Google Play: com.google.android.apps.maps

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3735]
@adguard-bot commented on [Wed Jan 27 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73308)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.google.android.apps.maps](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.maps)
### Comment
> When protection is on, google maps not working, it shows blank. When protection is off it is working normally.
> --
> The information below is automatically generated. Do not delete it.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/21MVrQ0.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/vmwpPhh.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.6 (1)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances
Custom filter subscriptions: |

**Comment by Chinaski1** [comment]
Not reproduced on my side.
Looks like this issue related to the DNS feature.
The user should try to reproduce it without DNS.
If the issue still persists:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by singh9596** [comment]
Did you find the fix? None of my Google app is working without disabling protection.
