### ISSUE TITLE
Support error with Samsung Free

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardForAndroid#3752]
AdGuard has no support with Samsung Free (formerly Bixby Home), a news application that uses the services of Taboola.

The application is a standard application of Samsung mobile phones

As long as AdGuard protection is working, the application becomes useless

The application gets stuck on the screen to agree to privacy terms and even clicking on agree the application gets stuck

address blocked by AdGuard: api.taboola.com and images.taboola.com

**Comment by Chinaski1** [comment]
Hello @eduardoaddad!

For first you can try to experiment with the AdGuard settings.
- You can find out more about this in our [knowledge base](https://kb.adguard.com/en/technical-support/reporting-tool#solo).
- If disabling all modules, including DNS filtering, has no effect. Then I would like to ask you to collect a full log (When you collect the log, leave the modules disabled).

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Send recived files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by eduardoaddad** [comment]
Log sending by email

**Comment by Chinaski1** [comment]
Hello @eduardoaddad 

You didn't reply to my last email.
You should try disabling Private DNS in the phone settings and enable the system server in the AdGuard settings.
Will the issue recur with this combination of settings?

**Comment by eduardoaddad** [comment]
I only use AdGuard DNS through the AdGuard app

Em qua, 24 de fev de 2021 13:03, Konstantin <notifications@github.com>
escreveu:

**Comment by Chinaski1** [comment]
@eduardoaddad 

Let's test the situation using these configurations

1) DNS Feature is ON, System server is Enabled, DNS Filters is ON
2) DNS Feature is ON, System server is Enabled, DNS Filters is OFF
3) DNS Feature is OFF

**Comment by Chinaski1** [comment]
Hello again!

It looks like you have encountered geoblocking and unfortunately, there is nothing we can do on the application side. Please use another server from the AdGuard DNS list to get access the application.

**Comment by dreamcatch22** [comment]
This issue has not been fixed yet. I have tried everything and cannot get adguard to cooperate with this app.

**Comment by eduardoaddad** [comment]
@dreamcatch22 To work with this application you must not use AdGuard DNS
