### ISSUE TITLE
Failed to install Adguard cert for HTTPS Filtering (Android 11)

### ISSUE THREAD

**Issue by jeffersoncheang** [AdguardTeam/AdguardForAndroid#3762]
Hi all. I followed the steps given to install Adguard cert:

Open Device settings
Go to 'Security'
Go to 'Encryption & Credentials'
Go to 'Install from storage' or 'Install a certificate' (depend on devices)
Select 'CA Certificate' from the list of types available
Accept a warning alert and click "install anyway"

Only up till this step, it didn't direct me to the page where I saved my cert. It stayed on the page of step 5 above.

When I tried to proceed from step 5 to step 6 again, it prompted an error message "Certificate Installer keeps stopping". I had to click "Close App" at this point.

Note: I've tried to force stop "Certificate Installer"; also I deleted Adguard and reinstalled the latest version; deleted all my PIN and fingerprint and reset; deleted all other previously installed Adguard cert; restarted my phone, but to no avail.

What's the issue??

**Comment by anastenko** [comment]
Hello.
To troubleshoot this issue, we need to get additional logs.
Here’s what we need you to do:
1. Collect the debug log as it’s [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here’s the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment]
@jeffersoncheang 

Also, you should try to open  http://local.adguard.org/cert when AG protection is enabled.
What if you go to settings -> security in Android and try to install from there?
In some cases, resetting AdGuard settings can help maybe the certificate generated an invalid one.

**Comment by Chinaski1** [comment]
@jeffersoncheang Any news?

**Comment by jeffersoncheang** [comment]
Thanks @anastenko and @Chinaski1 . Nothing is wrong with Adguard app. Figured it was com.android.documentsui (file picker) that crashed in the background. Clear data& cache of the app and reboot device solved the issue.

Thank you for your assistance. :)
