### ISSUE TITLE
Youtube ads cannot be blocked

### ISSUE THREAD

**Issue by sssamm19** [AdguardTeam/AdguardForAndroid#3765]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by anastenko** [comment]
Hello there.
We do not block ads in the YouTube application itself, since ads are sent by the same stream that videos are sent with.
But if you want to block ads in a particular video you can do the following:
1. Click "Share" below the video
2. Choose "AdGuard" option
3. The video will be opened in a new window without ads
