### ISSUE TITLE
Adgaurd doesn't work alongside other VPN applications

### ISSUE THREAD

**Issue by ham3dt** [AdguardTeam/AdguardForAndroid#3798]
Adgaurd doesn't let orbot and -some- other VPN applications connect or if they connect I don't have internet access. I have to turn off Adgaurd in order to be able to use VPN applications.

- **AdGuard version:**
  - 3.6.1(11)
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - Xiaomi note 9S
- **Operating system and version:**
  - Android 10
- **Root access:**
  - Yes

### Expected Behavior

Work along side all VPN applications.

### Actual Behavior

Blocks VPN connection.

**Comment by Chinaski1** [comment]
Hello!

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Specify the name and version of the VPN applications used.
4. Send a received file to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment]
@ham3dt 
Open Apps management -> Disable protection to the VPN app -> Let us know the result

**Comment by Chinaski1** [comment]
Closed due to no response.
