### ISSUE TITLE
Connections blocked by user rules are first run through Stealth Mode

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3809]
On connections that are going to be blocked by user rules they are first run through stealth mode. This is obvious because some things that I have blocked in user filters that also have tracking parameters that I have listed in Stealth Mode are shown first as being modified by Stealth Mode and then redirected where they are blocked. It would make more sense just to block them first, so **please rearrange the order of operations so that user filters are pinged prior to Stealth Mode rules**.

Helpdesk ID: **503472**
AdGuard: 4.0.24
Android: 5.1.1
Device: Amazon KFFOWI

**Comment by Chinaski1** [comment]
The priority of rules is determined by their syntax, not by the sections in which they are located.
This means that all available rules are collected from the different configuration sections and sent to CoreLibs where the distribution occurs.
You can find more information about rule syntax in our [knowledge base]( https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters).

**Comment by infinitewaveparticle** [comment]
Interesting. Since we can't see the rules for Stealth Mode's tracking parameters, are they written as $removeparam=param1$important ? If so, then that would make sense as to why they're first. If that's the case, then which would be first when comparing a Stealth Mode tracking parameters rule & a user filter also using $important ? Example:

$removeparam=param1$important (from Stealth Mode)
vs.
||example.com/abcdefg/123^$important
when applied to
https://example.com/abdcefg/123?param1=google.com

Would we see the link blocked first or the parameter stripped first (like I've seen)?
