### ISSUE TITLE
Messaging issues when adguard is enabled

### ISSUE THREAD

**Issue by nicolassp** [AdguardTeam/AdguardForAndroid#3823]
Exclude com.google.android.apps.messaging apk from filtering as it blocks rich content messaging very often.

**Comment by Chinaski1** [comment]
Hello @nicolassp 

The messaging application [is not included](https://uploads.adguard.com/Chinask1l4erg.png) in the default filtered list.
Perhaps you have manually activated protection?

**Comment by nicolassp** [comment]
There was a hypothesis because when adguard is enabled very often rcs messaging does not work properly. It may interfere somehow with rcs itself

**Comment by Chinaski1** [comment]
If you notice this behavior here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
4. Send recived file to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by nicolassp** [comment]
@Chinaski1 i will do that of course.

Is there by any chance that the following apps are being filtered?

com.android.service.ims.RcsServiceApp

Carrier services
Carrier settings
Carrier setup

**Comment by nicolassp** [comment]
It was not adguard responsible for this matter. It will be closed.
