### ISSUE TITLE
Adguard Android breaks Wireless Android Auto

### ISSUE THREAD

**Issue by Samuel12321** [AdguardTeam/AdguardForAndroid#3862]
### Issue Details

- **AdGuard version:**
3.6.2 RC2
 - **Filtering mode:**
   - Local VPN
- **Device:**
  - Samsung Galaxy S10e
- **Operating system and version:**
  - Android 11
- **Root access:**
  - No

### Expected Behavior
Adguard does not interfere with wireless android auto

### Actual Behavior

Adguard vpn breaks Wireless Android Auto

### Additional Information

When running android auto wirelessly aduard should disable its vpn or there should be an option to disable adguard on specific WIFI networks such as the one for wireless android auto.

This will become more of a problem as more wireless android auto devices are made

**Comment by Chinaski1** [comment]
Hello @Samuel12321 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Send received archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment]
Are there any updates about this issue? @Samuel12321

**Comment by Chinaski1** [comment]
Closed due not reply
