### ISSUE TITLE
Protection Restarting Randomly

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#3872]
I have noticed that the protection switch gets turned off and then after few seconds gets turned on randomly in the app. This is not because of the filter updates but happens randomly.

Noticed in 3.6.2 (23)

**Comment by Chinaski1** [comment]
Hello!

Actual it is difficult to say at first glance what might be the cause of this behaviour.

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by anastenko** [comment]
@Nzzyme Hello. 
Any news? Did you collect the logs?

**Comment by anastenko** [comment]
I'm closing this issue due to no response. Please re-open it if the issue appears again.

**Comment by Nzzyme** [comment]
No problem. I did not collect the logs but this is something related to AdGuard VPN and the main AadGuard app. I uninstalled the VPN app and no longer seeing this happening. When the VPN was installed and when I used to force close any other app, the protection used to restart not sure why.
