### ISSUE TITLE
Instagram doesn't work in root proxy mode

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#3879]
https://www.reddit.com/r/Adguard/comments/o12vwi/instagram_just_stopped_working_with_adguard_on/

**Comment by jordanswrld94** [comment]
@Alex-302 how can you tell if an apps traffic needs to be bypassed for quick packages in low level settings. Because Facebook Facebook messenger and Snapchat are showing blocked quic
![Screenshot_20230301_074650_AdGuard](https://user-images.githubusercontent.com/118186787/222156876-e857cb39-fede-48f8-a217-de6d201bbbb9.jpg)
