### ISSUE TITLE
Add "Allowlist/Blocklist" feature to apps management

### ISSUE THREAD

**Issue by pongfcnkl** [AdguardTeam/AdguardForAndroid#3898]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:v
  - 3.6.2
- **Filtering mode:Local 
  - VPN
- **Device:
  - xiaomi 6
- **Operating system and version:**
  - Android 10.0 
- **Root access:**
  - yes 

### Expected Behavior
Use magisk to flash this module, adguard disconnects the network 
https://github.com/EternalPain/ZJL

### Actual Behavior

As shown in the figure, there are many roots in the log, and it is invalid to close the routing application 
### Screenshots

<details><summary>

</summary>

![photo_2021-07-04_12-58-52](https://user-images.githubusercontent.com/24273319/124373854-89e52d80-dcc8-11eb-979a-5a8518a0fa33.jpg)

![photo_2021-07-04_12-58-55](https://user-images.githubusercontent.com/24273319/124373855-8b165a80-dcc8-11eb-8109-225a2356ffa3.jpg)

![photo_2021-07-04_21-53-22](https://user-images.githubusercontent.com/24273319/124387749-444d5280-dd12-11eb-99e8-aba5799d7705.jpg)

</details>

**Comment by Chinaski1** [comment]
Hello @pongfcnkl 

It's hard to tell right away what kind of traffic it is that passes over a root. It may be requested from unspecified applications.

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Send the recived file to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by pongfcnkl** [comment]
@Chinaski1 
Has been sent

**Comment by pongfcnkl** [comment]
Excuse me, one week has passed, how is the progress?

**Comment by Chinaski1** [comment]
@pongfcnkl 

Sorry for the late reply.
Unfortunately, there is no relevant information in the logs to explain this behaviour.

We are currently working on the release of version 4.0. In addition to the many changes, there will be added extended logging recording. It will help get the needed info.

Be sure, we return to this discussion after the release.

**Comment by pongfcnkl** [comment]
@anastenko 
Add magisk package name is still the same

**Comment by pongfcnkl** [comment]
This APP is also "root" routing traffic 
https://we.tl/t-wInrTr4HeL
**Need to be given root**

**Comment by admitrevskiy** [comment]
@pongfcnkl Hi!
Try to add `root` as a new line in `pref.excluded.packages`

**Comment by pongfcnkl** [comment]
@admitrevskiy 
still the same

**Comment by admitrevskiy** [comment]
@pongfcnkl could you please record debug logs with current configuration and send it to `devteam@adguard.com`?
Also provide additional information: the time of the problem and screenshots of the filtering log.

**Comment by pongfcnkl** [comment]
@admitrevskiy 
Has been sent

**Comment by admitrevskiy** [comment]
@pongfcnkl 
Hi!
Try to add `0` as a new line in pref.excluded.packages, maybe excluding root UID from VPN will help.

**Comment by pongfcnkl** [comment]
@admitrevskiy 
Still invalid

**Comment by admitrevskiy** [comment]
@pongfcnkl 
Please send debug logs with current config to `devteam@adguard.com`

**Comment by pongfcnkl** [comment]
@admitrevskiy
Has been sent

**Comment by admitrevskiy** [comment]
Looks like we can't manage root on our side to exclude it from VPN. @anastenko try to reproduce this issue, please.

@pongfcnkl 
Just to be clear, does this issue violates logic of some app/system or are you just confused by requests in the filtering log?

**Comment by pongfcnkl** [comment]
@admitrevskiy 
This problem will cause me to be unable to access the Internet, and this[ APP ](https://we.tl/t-wInrTr4HeL)will also cause the certificate error to be unusable

**Comment by admitrevskiy** [comment]
@pongfcnkl 
Could you check one more thing for me?
Switch AdGuard to 'Local Proxy auto mode' (Settings -> Network -> Filtering method) and try to reproduce the issue.

**Comment by pongfcnkl** [comment]
Local Proxy auto mode is still the same

**Comment by pongfcnkl** [comment]
@admitrevskiy 
There are problems like #3820 in Local Proxy auto mode, I rarely use him

**Comment by admitrevskiy** [comment]
I have studied the source code in a little more detail. It seems that there is no way to exclude root from the VPN, since the android API only supports package exclusion, not UID.  

- So, this is the very [start](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/net/VpnService.java;l=768;bpv=1;bpt=0?q=addDisallowedApp&sq=&ss=android%2Fplatform%2Fsuperproject  );
- After adding package name to ‘disallowed’ list it takes a long way and comes [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/connectivity/Vpn.java;l=1460;bpv=1;bpt=0?q=com.android.server.connectivity.Vpn&ss=android%2Fplatform%2Fsuperproject  );
- As you can see, it [tries](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/connectivity/Vpn.java;l=1093;bpv=1;bpt=0?q=com.android.server.connectivity.Vpn&ss=android%2Fplatform%2Fsuperproject  
) to get the UID using the Android PackageManager.

But there is no ‘root’ package and it’s totally ignored. So, this configuration is not supported until there is no way to add raw UID. I don't think that such an opportunity will appear: android developers stick to a very strict security policy.

  On the other hand, we can try to improve this behavior for Auto-proxy mode.

**Comment by pongfcnkl** [comment]
So can you refer to the vpn mode of [shadowsocks Android](https://github.com/shadowsocks/shadowsocks-android)? Can I choose the default blacklist or the default whitelist? 
![photo_2021-08-10_19-14-42](https://user-images.githubusercontent.com/24273319/128857419-820eb268-bb00-4fc6-8615-0f9a0e066f83.jpg)

**Comment by admitrevskiy** [comment]
I guess I don't really understand the question :)
Describe in more detail what you meant.

**Comment by pongfcnkl** [comment]
Now AdguardForAndroid defaults to all routing. Can you refer to shadowsocks Android to modify the VPN mode? Choosing on is to route only the apps I need, choosing Bypass is the same as AdguardForAndroid

**Comment by admitrevskiy** [comment]
Well, is it Blocklist/Allowlist for apps routing or something?

**Comment by pongfcnkl** [comment]
Yes

**Comment by admitrevskiy** [comment]
At this moment it's really hard to implement: AdGuard works in 'Allowlist' mode only and this is the philosophy of filtering and ad blocking. On the other hand, we may try to implement this feature in future updates.
