### ISSUE TITLE
Adguard Android breaks Wireless Android Auto

### ISSUE THREAD

**Issue by nochlab1** [AdguardTeam/AdguardForAndroid#3909]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
  - v4.0.57
- **Filtering mode:**
  - 
  - Local VPN
- **Device:**
  - 
  - Galaxy Z Fold 2
- **Operating system and version:**
  - 
  - Android 11
- **Root access:**
  - 
  - No

### Expected Behavior
Adguard does not interfere with wireless android auto

### Actual Behavior
Adguard vpn breaks Wireless Android Auto

When running android auto wirelessly aduard should disable its vpn or there should be an option to disable adguard on specific WIFI networks such as the one for wireless android auto.

This will become more of a problem as more wireless android auto devices are made

(This is a copy of a different issue but he didn't answer so it was closed so reopening it)

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Chinaski1** [comment]
Hello @nochlab1!

As in the previously closed task, I would like to ask you to collect a log to try to find out the reasons for specified behaviour:

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Send received archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by nochlab1** [comment]
I can send a log but i don't see how it would help, adguard isn't crashing just wireless android auto doesn't work with any vpn

**Comment by ameshkov** [comment]
@nochlab1 does it help to disable filtering for Android Auto app in the apps management settings?

**Comment by anastenko** [comment]
@nochlab1 Any news?

**Comment by zzebrum** [comment]
@nochlab1 what exactly is not working?

**Comment by nochlab1** [comment]
Sorry just had a chance to try it and whitelisting androud auto and google play services worked (i forgot to try just android auto) and it worked i know last year it didn't work so i guess google changed something

**Comment by admitrevskiy** [comment]
@nochlab1 Hi!
Could you please send us some additional logs?
- Upgrade AG to the latest stable version;
- Follow instructions from https://kb.adguard.com/en/android/solving-problems/log#debug;
- Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
- Send received archive to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.


It would be nice if after that you went to the "Filtering Log" section and filter all requests from Android Auto and also attached screenshots.

**Comment by Samuel12321** [comment]
> Sorry just had a chance to try it and whitelisting androud auto and google play services worked (i forgot to try just android auto)

Just whitelisting android auto works

**Comment by ameshkov** [comment]
> Just whitelisting android auto works

@admitrevskiy consider adding it to the default list of exclusions then.

**Comment by artemiv4nov** [comment]
@Samuel12321 Hi! Could you test whether the Android Auto app works when AdGuard VPN works too or not?

**Comment by josejuan83mtz-stack** [comment]
> ### Prerequisites
> 
> Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**
> 
> - [x] I am running the latest version
> - [x] I checked the documentation and found no answer
> - [x] I checked to make sure that this issue has not already been filed
> 
> ### Issue Details
> 
> 
> 
> - **AdGuard version:**
>   - 
>   - v4.0.57
> - **Filtering mode:**
>   - 
>   - Local VPN
> - **Device:**
>   - 
>   - Galaxy Z Fold 2
> - **Operating system and version:**
>   - 
>   - Android 11
> - **Root access:**
>   - 
>   - No
> 
> ### Expected Behavior
> Adguard does not interfere with wireless android auto
> 
> 
> 
> ### Actual Behavior
> Adguard vpn breaks Wireless Android Auto
> 
> 
> When running android auto wirelessly aduard should disable its vpn or there should be an option to disable adguard on specific WIFI networks such as the one for wireless android auto.
> 
> This will become more of a problem as more wireless android auto devices are made
> 
> (This is a copy of a different issue but he didn't answer so it was closed so reopening it)
> 
> ### Screenshots
> 
> 
> 
> <details><summary>Screenshot:</summary>
> 
> 
> 
> </details>
> 
> ### Additional Information
> 
> 
> 

Que esto
