### ISSUE TITLE
Unable to install security certificate for HTTPS filtering

### ISSUE THREAD

**Issue by Fandril** [AdguardTeam/AdguardForAndroid#3915]
![Screenshot_20210724-191543_AdGuard](https://user-images.githubusercontent.com/51031031/126863929-60aaf514-d59b-4540-a642-ab330dc74194.jpg)
It had previously worked just fine. I have tried both manual and automatic install, and still unable to install the certificate. Tried to reinstall AdGuard, clearing the data for Certificate Installer. 

Rooted Samsung S10, Android 9, Magisk 23.0. AdGuard 3.6.2

**Comment by Chinaski1** [comment]
@RaXorX 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Fandril** [comment]
Logs and screenshots sent through email. Thank you very much.

**Comment by Chinaski1** [comment]
I received your email and can say to you that looks like the issue is related to the specificы of your phone's firmware.
Unfortunately, there is nothing we can do to help you on the application side.

> 07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: FATAL EXCEPTION: main
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: Process: com.android.settings, PID: 6919
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: java.lang.AssertionError: android.os.DeadObjectException
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.security.KeyStore.state(KeyStore.java:221)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.security.KeyStore.state(KeyStore.java:233)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at com.android.settings.CredentialStorage.handleUnlockOrInstall(CredentialStorage.java:204)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at com.android.settings.CredentialStorage.onResume(CredentialStorage.java:182)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7558)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4005)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4045)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7037)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: Caused by: android.os.DeadObjectException
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:1140)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.security.IKeystoreService$Stub$Proxy.getState(IKeystoreService.java:862)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.security.KeyStore.state(KeyStore.java:218)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	... 17 more07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: FATAL EXCEPTION: main
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: Process: com.android.settings, PID: 6919
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: java.lang.AssertionError: android.os.DeadObjectException
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.security.KeyStore.state(KeyStore.java:221)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.security.KeyStore.state(KeyStore.java:233)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at com.android.settings.CredentialStorage.handleUnlockOrInstall(CredentialStorage.java:204)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at com.android.settings.CredentialStorage.onResume(CredentialStorage.java:182)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7558)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4005)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4045)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7037)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: Caused by: android.os.DeadObjectException
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:1140)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.security.IKeystoreService$Stub$Proxy.getState(IKeystoreService.java:862)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	at android.security.KeyStore.state(KeyStore.java:218)
07-26 03:34:29.578  1000  6919  6919 E AndroidRuntime: 	... 17 more

**Comment by Fandril** [comment]
Thank you for the rapid analysis. Can you expand on what you meant regarding the "specificы" of my firmware so I can attempt to fix it?

**Comment by Chinaski1** [comment]
This means that the firmware itself does not allow a certificate to be installed in the system.

**Comment by Fandril** [comment]
https://stackoverflow.com/questions/44942851/install-user-certificate-via-adb

Would you recommend forcing the certificate via adb as written on the link or just do a fresh firmware install?

**Comment by Chinaski1** [comment]
I think it is better to start by trying to install the certificate through `adb` since it is a faster option.
And then try to reinstall the firmware.

**Comment by artemiv4nov** [comment]
@Fandril Did you manage to try to install a certificate through adb?

**Comment by Fandril** [comment]
Sorry, I have an issue regarding certificate hash.

If you check on the link I previously provided (https://stackoverflow.com/questions/44942851/install-user-certificate-via-adb), the first step uses openssl to obtain a certificate hash out of the certificate using this command (openssl x509 -inform PEM -subject_hash_old -in charles-proxy-ssl-proxying-certificate.pem | head -1>toto)

I have not been able to achieve this. Can you help me by providing me with such hash?

**Comment by admitrevskiy** [comment]
@Fandril Hi!
Are you facing the issue like that?

```
unable to load certificate
4375473836:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.2/libressl-2.8/crypto/pem/pem_lib.c:684:Expecting: TRUSTED CERTIFICATE
```

Try to fix CA's encoding with the following trick:

```
openssl x509 -inform DER -in <adguard_cert_name>.crt -out <new_adguard_cert_name>.crt
```

And then the hash can be obtained using:
```
openssl x509 -inform PEM -subject_hash_old -in <new_adguard_cert_name>.crt | head -1>toto
```

**Comment by admitrevskiy** [comment]
@Fandril Hi!
Any updates on this issue?

**Comment by Fandril** [comment]
Thank you for follow up.

Unfortunately I am really unfamiliar with the openssl. If it is not too much to ask, can you provide me a step-by-step process on how to install the openssl in the first place? Do I need to install Git first to get openssl?
https://stackoverflow.com/questions/50625283/how-to-install-openssl-in-windows-10

**Comment by admitrevskiy** [comment]
I think that a more correct way for you would be to install another firmware :)
It looks totally broken based on log and symptoms: access to the user certificate store is locked. And God only knows what else may be broken in this rom.

**Comment by admitrevskiy** [comment]
Well, I'm closing this issue for now. Please let me know if you want to try it with Linux/MacOS or if you reinstall the ROM and issue still persists.
