### ISSUE TITLE
i have a problem with notification delay

### ISSUE THREAD

**Issue by nkoc6a15** [AdguardTeam/AdguardForAndroid#3928]
I am using latest adguard. VPN Mode with install Adguard's certification in system using Magisk addon. When i turn off a screen. I cant recieve any notification of Facebook, Instagram and Messenger. How can i fix this? Thank you!

**Comment by infinitewaveparticle** [comment]
Duplicate of #3486 ?

**Comment by anastenko** [comment]
Definitely looks like a duplicate of #3486. Thanks @infinitewaveparticle.
@nkoc6a15 Could you please send us the debug logs? Here's how to do it:

- Open Settings --> Advanced settings --> Logging level --> Choose "Record everything"
- Reproduce the issue and remember the exact time it happened
- Send the logs to devteam@adguard.com and mention the Github issue number and the time when the issue was reproduced
