### ISSUE TITLE
Excluded apps are still filtered while using auto proxy mode

### ISSUE THREAD

**Issue by anastenko** [AdguardTeam/AdguardForAndroid#3957]
- **AdGuard version:**
  v 3.6.2 (23)
- **Filtering mode:**
  HTTP Proxy (Auto/)
- **Device:**
 Samsung Galaxy A80
Adguard version: 
- **Operating system and version:**
   Android 10
- **Root access:**
  Yes
  
### Issue Details

The user has been using Cloudflare DNS with Dns-over-HTTPS mode before testing.
 
- First, switched to Adguard DNS(non-filtering) with the same mode, the problem persisted. 

- Then switched back to Cloudflare DNS with regular mode, the problem was resolved. They also tested DNS-over-TLS mode, and the problem came back. 

- Afterwards tested with Google DNS and only regular mode posed no problems, like the others.

- Then tested Adguard DNS (non-filtering) again with the DNSCrypt mode and the DNS-over-QUIC mode because those modes could be used with Adguard DNS servers only and had no problems with the latter while it still blocked ads with DNSCrypt.

- And finally, tested the DNS requests blocking, and when they disabled it (or the Adguard DNS filter inside it), all the DNS servers worked as they should've. 

No such issue with Local Vpn mode. Only auto local proxy mode blocks ads in all apps.

Ticket number: 533062

**Comment by admitrevskiy** [comment]
There is a problem with Auto-proxy mode, DNS filtering and apps exclusions.

First of all, all apps have the same netId, since there is no tun-interface. So, they use the same local DNS IP address to perform DNS requests. 
Secondly, for the same reason, they use the same cache.
Thirdly, all UDP requests are perfrormed by the 'system' UID.

Thus, we do not have a mechanism that 100% guarantees the exclusion of DNS traffic from filtering.

You ask me, why does this not happen in VPN mode?
`getaddrinfo` will result in `getaddrinfo_with_netid` that differs for traffic inside VPN tunnel and outside of it.

I don't think if we can do anything due to system restrictions.
