### ISSUE TITLE
broken QUIC protocol

### ISSUE THREAD

**Issue by adven2rer** [AdguardTeam/AdguardForAndroid#3971]
I'm running latest Adguard for Android beta 3.6.3 and it totally ruined point of the QUIC: after switching from mobile data to Wi-Fi it lose internet connection for about a minute-two. it's really annoying I has to move to DNScrypt v2 temporarily — that's also not so okay, but internet come back faster. by the way, I use BlahDNS server, but it work the same for Adguard QUIC server — I have checked.

**AdGuard version:**
– v3.6.3

**Filtering mode:**
– HTTP Proxy (Auto)

**Device:**
– Xiaomi Mi 9 Lite (global)

**Operating system and version:**
– Android 11, MIUI 12.6, Xiaomi.EU 21.9.8 

**Root access:**
– Yes

**Comment by Chinaski1** [comment]
Hello there!

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send received archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment]
Any news?

**Comment by adven2rer** [comment]
hello! the issue was fixed with the last update of Adguard on Android, so, this thread can be closed. thank you.

**Comment by adven2rer** [comment]
> Hello there!
> 
> To troubleshoot this issue, we need to get additional logs.
> 
> Here's what we need you to do:
> 
> 1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
> 2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
> 3. Send received archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

hello! the issue was fixed with the last update of Adguard on Android, so, this thread can be closed. thank you.
