### ISSUE TITLE
No internet with HTTP filtering enabled

### ISSUE THREAD

**Issue by JulioQc** [AdguardTeam/AdguardForAndroid#3982]
If I disable wifi and switch to LTE internet works. If I stay on wifi but disable adguard it works. If i disable HTTPS filtering imln adguard it works on either.

I tried reinstalling the CA cert and moving to system store but no improvement after. User or system  storw makes no difference.

This oddly started after I removed some firewall rules on my network allowing google dns (was blocked before) to fix some Chromecast issue. Weird, probably unrelated.

Any ideas whats going on?

Mi 10T
lineageOS 18.1
magisk 23
adguard 3.6.4 (32)

**Comment by Chinaski1** [comment]
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Additionally, export the settings (General -> Export settings -> save it somewhere on the device).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by JulioQc** [comment]
Alright I'll send you those logs later today, after further testing to produce some relevant messages in there.

Also I forgot to mention that my partner's tablet is afflicted of the same problem. Similar setup with Magisk and Adguard, but rooted stock Samsung Android rather than LineageOS.

I've also noticed two (2) Adguard CA being moved to the system store although only the one was installed during setup. Odd.

**Comment by JulioQc** [comment]
Ok I found the issue. Change to my DHCP server sending the non-recursive DNS server on my LAN instead of the outbound PiHole... Solution matches the symptoms and making the switch to the right DNS server solved the problem.

It's always DNS!
