### ISSUE TITLE
Tapping the proxy switch causes AdGuard closing with a prompt error

### ISSUE THREAD

**Issue by biange200** [AdguardTeam/AdguardForAndroid#3986]
![Screenshot_20211001_121023](https://user-images.githubusercontent.com/37582806/135564134-4b1f8381-3ee4-43d1-b610-aa1de4af1957.jpg)
![Screenshot_20211001_120843](https://user-images.githubusercontent.com/37582806/135564137-2506b5ec-07b0-4646-8a8a-22e0a80e98c2.jpg)
![Screenshot_20211001_120819](https://user-images.githubusercontent.com/37582806/135564142-fbf6466f-2e08-416b-86ea-4499b33e7dd4.jpg)
![Uploading Screenshot_20211001_120633.jpg…]()
adguard开启保护 切换代理打开vpn
在通知栏里点击代理断开连接 就提示错误导致adguard自动关闭

**Comment by Chinaski1** [comment]
Hello!

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by biange200** [comment]
hello  已回![Screenshot_20211003_115414.jpg](https://user-images.githubusercontent.com/37582806/135738943-e3d4244b-0ebb-4857-b975-f659e60adcd7.jpg)

**Comment by Chinaski1** [comment]
Did you send the logs to devteam@adguard.com?

**Comment by Chinaski1** [comment]
We received the logs. Thank you.

**Comment by Chinaski1** [comment]
Yes, you need to reset the application settings.

**Comment by biange200** [comment]
重置没用

**Comment by Chinaski1** [comment]
Have you tried running any other VPN service on your device?
Maybe you noticed a similar issue.

**Comment by Chinaski1** [comment]
Sorry for the late reply.
But we need the application logs to find the cause of your issue.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment]
@biange200 Any news?

**Comment by Chinaski1** [comment]
Closed due not reply.

**Comment by Emmeenneti** [comment]
*To whom it may concern*

Hello there.

As I already had deleted my Github account, I request my email address to
be removed from any Github records (notifications bot, newsletter service,
etc..)

The reason I am requesting deletion of my personal data is consent is being
revoked for personal data processing.
The information that I am specifically aware of, that you process or
retain, is as follows:

My email address: ***@***.***
My name, Emme Tidona
Mi IP address eventually

If you process other personal data that belongs to me, which I may not be
aware of, please consider this request to apply to that data, as well. I
would like all of my personal data deleted from your systems.

Please respond in writing to confirm that my request has been honored.

Sincerely,
Emme Enne Tidona


Il Lun 1 Nov 2021, 16:10 Konstantin ***@***.***> ha scritto:

**Comment by Chinaski1** [comment]
@Emmeenneti 

You need to send your request to support@adguard.com
