### ISSUE TITLE
Android interface randomly stuttering

### ISSUE THREAD

**Issue by sebastianjena** [AdguardTeam/AdguardForAndroid#3994]
Version: Nightly 4.0 24 (occured on older nightlies as well AFAIK)
Phone: POCO F3 Android 11, rooted
Settings: Local VPN, HTTPS with moved certs using Magisk, default DNS filtering (tried to turn off for testing)

The issues I have is random UI lags when using the phone. This doesn't look like OS issue because I have solid 120hz each time it happens. Every time it happens, I'm stopping Adguard temporarily by pushing the button from notifications and then turn protection on back again, it solves it for a while but then it happens again.

**Comment by Chinaski1** [comment]
Hello there!

Could you describe your problem in more detail?
It would also be great if you could do a screen recording.

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Kusurisan** [comment]
i think i have a similiar issue but always thought my phone is just getting old or something. i use my phone and everything works fine, but then random without any reason my complete phone freezes and nothing happens anymore.. no buttons respond anymore, touchscreen also not anymore.. and the complete operation system is freezed for like 10-30 seconds. then it suddenly works again again without any reason. i already tried to find the issue by using taskmanagers etc. to see which app it could be but couldn't narrow it really down yet. this started like 1-2 updates ago.

**Comment by sebastianjena** [comment]
@Birbber sorry for no replies, had a quite busy time. I just upgraded to Android 12, I will tell you if was the ROM issue or app

**Comment by Birbber** [comment]
@sebastianjena Sure, waiting for your update on it.

**Comment by sebastianjena** [comment]
It stopped happening on Android 12.. I can't reproduce anymore

**Comment by Birbber** [comment]
Great to hear. I'm closing this issue then.
