### ISSUE TITLE
Internet connection is being blocked randomly.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#403]
ticket id KLJ-151-73935

Помогает только остановка и повторный запуск защиты. Ненадолго.
1. Ситуация проявляется как при соединении по wifi, так и при мобильном интернете.
2. Блокируется весь трафик. Телефон выдает сообщение "Интернет недоступен". 
3. Происходит и во время использования телефона, так и после бездействия. 
4. Стало проявляться после подключения фитнес-браслета Mi Band 1S с программой MiFit. Но соединение с ним идет по Bluetooth. Удаление MiFit не помогло.
5. Когда проблема возникает, то Adguard не встает на паузу и Adguard продолжает увеличивать счетчики принятых и отправленных пакетов.

**Comment by vozersky** [comment]
<script src="https://gist.github.com/vozersky/58594e99894367a83906.js"></script>

**Comment by vozersky** [comment]
<script src="https://gist.github.com/vozersky/58594e99894367a83906.js"></script>

**Comment by vozersky** [comment]
Here is the log with problem reproduced at 20.33: https://gist.github.com/vozersky/58594e99894367a83906 

"Выключил, включил Adguard - интернет заработал. Подключение по Wi-Fi. Есть ощущение, что интернет отключается после какого-то перерыва использования интернета. Например, сейчас была включена онлайн игра Forge of Empires. Сначала все было все хорошо, потом отошёл оставив ее включенной. По возвращении интернета уже не было. Проверил в браузере, тоже нет."

**Comment by vozersky** [comment]
Same issue here:   TICKET ID JTR-490-65787

Also Xiaomi device.

Log: https://gist.github.com/vozersky/c785f8c83433f38a0d6e

**Comment by ameshkov** [comment]
По логу (второму) - у него просто пропадает сеть на пару минут, потом оживает.
Вообще без понятия что может происходить в этом время и почему.

**Comment by TrustCane** [comment]
Привет, у меня тоже Xiaomi. И я уже недели 3 назад обратился точно с такой проблемой. Хочу тебе сказать, как ни странно я тоже вот купил mi fit, и установил приложение mi band. Но все же  **оно здесь не при чем**, ибо им я пользуюсь дня 4, а проблема уже давненько.
Жду что нам с тобой помогут) У меня кстати MI3W

**Comment by ameshkov** [comment]
@TrustCane да я на ваши логи медитировал уже несколько раз, пока просто ума не приложу в чем там дело.

А у Xiaomi нет там какой-то обновленной прошивки?

**Comment by TrustCane** [comment]
Новой версии для моей прошивки нету, но вышла более-менее стабильная прошивка с android 6.0. Стоит поставить? 04.04.2016, 01:09, "Andrey Meshkov" <notifications@github.com>:@TrustCane да я на ваши логи медитировал уже несколько раз, пока просто ума не приложу в чем там дело.А у Xiaomi нет там какой-то обновленной прошивки?—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub   -- С уважением,Копыл Денис

**Comment by ameshkov** [comment]
Да, стоит попробовать, я думаю дело именно в прошивке

**Comment by TrustCane** [comment]
После кучи усилий, я все таки поставил новую прошивку, теперь андроид 6.0. Это решило многие проблемы с запусками приложений, но adguard по прежнему не работает...1:33 PM, 4 апреля 2016 г., Andrey Meshkov <notifications@github.com>:Да, стоит попробовать, я думаю дело именно в прошивке —You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub     %D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BE%20%D0%B8%D0%B7%20%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9%20%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%2E%D0%9F%D0%BE%D1%87%D1%82%D1%8B%3A%20http%3A%2F%2Fm%2Eya%2Eru%2Fymail

**Comment by ameshkov** [comment]
Да елки палки. Скажите пожалуйста, а без Adguard интернет-соединение вот так не пропадает?
Просто по логу ничего особенного не происходит, просто на некоторое время отваливается сеть.

**Comment by TrustCane** [comment]
Нет, так все стабильно работает. Очень непривычно везде видеть рекламу... 11.04.2016, 13:09, "Andrey Meshkov" <notifications@github.com>:Да елки палки. Скажите пожалуйста, а без Adguard интернет-соединение вот так не пропадает? Просто по логу ничего особенного не происходит, просто на некоторое время отваливается сеть.—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub   -- С уважением,Копыл Денис

**Comment by vozersky** [comment]
new log from the user with same problem on on xiaomi device: 

https://gist.github.com/vozersky/ac9b37377422014d9b4d2a79a2d171c7 

it's said that the issue was reproduced at 21:17

**Comment by TrustCane** [comment]
Что мне это дает?)

11.04.2016, 20:30, "vozersky" <notifications@github.com>:
> new log from the user with same problem on on xiaomi device:
>
> https://gist.github.com/vozersky/ac9b37377422014d9b4d2a79a2d171c7
>
> it's said that the issue was reproduced at 21:17
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
Копыл Денис

**Comment by vozersky** [comment]
cases summary:

1. KLJ-151-73935, Xiaomi Redmi Note 2
https://gist.github.com/vozersky/58594e99894367a83906  reproduced at at 20.33

2.JTR-490-65787, Xiaomi MI 3W
https://gist.github.com/vozersky/c388278f142dbae1fb13cea8198dd3cd

3. KPA-928-20328, Xiaomi Redmi Note 2
https://gist.github.com/vozersky/ac9b37377422014d9b4d2a79a2d171c7 reproduced at 21:17

**Comment by ameshkov** [comment]
Мда. Проблема логов в том, что я там не вижу ничего общего.
Что-то вангование по нашим логам не приносит результата.

Надо запрашивать logcat:
https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/62/0/how-to-get-logcat-log-from-android-device
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/63/0/kk-poluchit-log-logcat-n-ustrojjstve-android

**Comment by TrustCane** [comment]
И так... я сделал как было написано, и стало еще интереснее, adguard просто крашится после где то 3 минут работы, может и то меньше. Закрывается сам, не выдавая никакой ошибки. Интернет соответственно пропадает.
[logcat.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/221785/logcat.txt)

**Comment by ameshkov** [comment]
Много вот таких записей в логах:
> 04-15 14:38:06.335  2032  3735 W BroadcastQueueInjector: Unable to launch app com.adguard.android/10170 for broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) }: process is not permitted to autostart

В xiaomi есть свой менеджер приложений, в нем желательно дать нашему приложению права на автозапуск.

**Comment by ameshkov** [comment]
@TrustCane а когда по времени примерно происходили проблемы?

**Comment by TrustCane** [comment]
Да я уже и не помню... Проблему я воспроизводил 2 раза, после второго раза почти сразу же сохранил логи, по этому где то в конце1:57 AM, 18 апреля 2016 г., Andrey Meshkov <notifications@github.com>:@TrustCane а когда по времени примерно происходили проблемы? —You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub     %D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BE%20%D0%B8%D0%B7%20%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9%20%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%2E%D0%9F%D0%BE%D1%87%D1%82%D1%8B%3A%20http%3A%2F%2Fm%2Eya%2Eru%2Fymail

**Comment by ameshkov** [comment]
> Когда проблема возникает, то Adguard не встает на паузу и Adguard продолжает увеличивать счетчики принятых и отправленных пакетов.

Ну вот это вот точно вызвано настройками безопасности в Xiaomi (https://github.com/AdguardTeam/AdguardForAndroid/issues/403#issuecomment-211126096)

Чтобы исправить нужно разрешить Adguard автозапуск (настройки - безопасность - вот там искать).

**Comment by ameshkov** [comment]
Попробуйте пожалуйста разрешить и посмотреть, уйдет ли проблема.

**Comment by TrustCane** [comment]
Проблема не ушла. Было следующее. Разрешил я автозапуск, перезагрузил телефон, и интернет сразу не работал, как только я выключил adguard, интернет заработал2:43 PM, 20 апреля 2016 г., Andrey Meshkov <notifications@github.com>:Попробуйте пожалуйста разрешить и посмотреть, уйдет ли проблема. —You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub     %D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BE%20%D0%B8%D0%B7%20%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9%20%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%2E%D0%9F%D0%BE%D1%87%D1%82%D1%8B%3A%20http%3A%2F%2Fm%2Eya%2Eru%2Fymail

**Comment by ameshkov** [comment]
Да что ж такое то. У нас в офисе есть один Xiaomi, но на нем таких проблем не наблюдается.

А что если для проверки отключить галку "Фильтровать трафик приложений"?
Чтобы Adguard вообще мог только браузеры трогать, а на остальное не влиял?

**Comment by TrustCane** [comment]
И так сделал :D это очень странно. Спустя минут 15, перестали работать и приложения и браузер... Отключение фильтрации гуарда, сразу вернуло работу интернета. У меня еще скорость пишет, так вот в момент когда инет не работал, там и было написано 0.00 к/с, максимум поднималось до 0.05 к/с. Но мне кажется это лишь какое то визуальное изменение. Потом когда отключил, сразу и скорость пошла.6:22 PM, 22 апреля 2016 г., Andrey Meshkov <notifications@github.com>:Да что ж такое то. У нас в офисе есть один Xiaomi, но на нем таких проблем не наблюдается. А что если для проверки отключить галку "Фильтровать трафик приложений"? Чтобы Adguard вообще мог только браузеры трогать, а на остальное не влиял? —You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub     %D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BE%20%D0%B8%D0%B7%20%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9%20%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%2E%D0%9F%D0%BE%D1%87%D1%82%D1%8B%3A%20http%3A%2F%2Fm%2Eya%2Eru%2Fymail

**Comment by Bohdan-SUP** [comment]
Xiaomi Redmi Note 3, MIUI 7, latest beta log - PCC-945-39057

**Comment by ameshkov** [comment]
После релиза 2.5 еще один заход попробую сделать. Пока я что-то без понятия:(

**Comment by evgeniy-ADG** [comment]
> I managed to SOLVE the issue after reading some forums.
> Securtiy--> Permissions--> Autostart and then switch Adguard Toggle to on
> Xiaomi has a very aggressive task killer causing apps to randomly shut down.

**Comment by ameshkov** [comment]
@evgeniy-ADG в случае @TrustCane это не помогло, да(

**Comment by TrustCane** [comment]
Установил я 2.5 ... Все грустно. По прежнему не работает12:56 AM, 25 апреля 2016 г., Andrey Meshkov <notifications@github.com>:После релиза 2.5 еще один заход попробую сделать. Пока я что-то без понятия:( —You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub     Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by evgeniy-ADG** [comment]
1197818 - логи
1411866

**Comment by ameshkov** [comment]
> 1197818

According to this ticket turning autostart off helps with the issue. I have no idea why, though.

**Comment by ameshkov** [comment]
@evgeniy-ADG мне нужно знать точные версии прошивок у всех пользователей. settings -> about

**Comment by vgavrish** [comment]
по id 1197818
Когда основательно тестил была MIUI 8.0.1.0. 
На обновлении 8.0.2.0 еще не тестировал.

**Comment by ameshkov** [comment]
Полная инструкция по настройке Xiaomi:
https://github.com/gshumihin/test/blob/master/xiaomi_issuefix.md
