### ISSUE TITLE
AG protection doesn't start automatically after network changed

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#4092]
hello,
there are adapters for sale that can convert usb output to ethernet connection on android and
I bought one for me and I recently began using it,

so, I disabled wifi and connected to ethernet,
well, android realised the connection and connected me to the internet (a mark like this: <-> was shown on the wifi place),
but AG didn't, AG VPN remained disabled!

please fix

**Comment by Chinaski1** [comment]
Hello there!

Please tell me more about what's happening. After connecting the Internet cable, AdGuard cannot create a VPN connection?
Are we talking about AdGuard or AdGuard VPN?

**Comment by patrickdrd** [comment]
we are talking about AG used in vpn mode, not AG VPN,
so, after connecting AG doesn't start (connection remains disabled, but AG doesn't seem to know that I'm connected to the internet!),
if I start it manually, it works of course, but it should detect that I connected and start the protection

**Comment by patrickdrd** [comment]
I think I need to correct myself:
the case is I've got WiFi, I connect Ethernet, I disable WiFi and protection becomes disabled, while it shouldn't because I'm still connected to the internet

**Comment by Chinaski1** [comment]
@patrickdrd @Titanposeidon

The issue is not reproduced on my side, so I want to ask you to collect the logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send log files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by patrickdrd** [comment]
done

**Comment by Chinaski1** [comment]
Yes, the behavior you described is indeed observed.
We will take this into account in version v4.0. and AdGuard will automatically reconnect.

**Comment by artemiv4nov** [comment]
That's a super important feature for our user @patrickdrd, it can't be closed until I find the solution.

**Comment by artemiv4nov** [comment]
In the v4.0 version, the protection is restarted after network is changed.
