### ISSUE TITLE
AdGuard 3.6.7 Update Downloaded but Fails (Corrupt APK) 

### ISSUE THREAD

**Issue by Flipmode11** [AdguardTeam/AdguardForAndroid#4102]
### Prerequisites

- [ N ] I am running the latest version
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.6.7 beta upgrade to 3.6.7 stable  
- **Filtering mode:**
  - Local VPN 
- **Device:**
  - Galaxy S7 Edge & S10 Plus
- **Operating system and version:**
  - Android 8.0 & 11.0
- **Root access:**
  - No

### Expected Behavior

Expect installation success. Show button to close or open app (normally this is not shown and the installer closes while AdGuard restarts the services).

### Actual Behavior

Shows an error message. Update failed. 

### Screenshots

<details><summary>Screenshot:</summary>
![Screenshot_20220203-172631_AdGuard](https://user-images.githubusercontent.com/7277744/152292753-f5b00922-de6d-4146-a896-d3aa7749b4b5.jpg)
![Screenshot_20220203-172656_Package installer](https://user-images.githubusercontent.com/7277744/152292811-a3b98451-08a1-4c03-b79f-5a94418769b3.jpg)

</details>

**Comment by Chinaski1** [comment]
Hello!

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment]
Any news?

**Comment by Chinaski1** [comment]
Closed due not reply.

Reopen the task if the issue is still reproduced.
