### ISSUE TITLE
Latest One UI 4 Upgrade (Android 12) broke AdGuard

### ISSUE THREAD

**Issue by XtremeMaC** [AdguardTeam/AdguardForAndroid#4107]
Galaxy S20 UItra 5G (SM-G988U1)
Build Number : G988U1UEU2EVA2
Android version : S(Android 12)
https://doc.samsungmobile.com/SM-G988U1/ATT/doc.html --> change doc

On Latest v4.0 nightly 32

Just upgraded to Android 12, it broke a few of my apps including AdGuard.
It's giving me the following error as I try to enable. 
Uninstalled. Reinstalled. All permission set correctly. 

![Screenshot_20220210-205824_AdGuard](https://user-images.githubusercontent.com/11046475/153528218-8fc00fc8-c45c-4b8a-98ca-31bb3db075c5.png)

**Comment by Chinaski1** [comment]
Hello!

Please check if this issue is related to [Restricted Mode](https://kb.adguard.com/en/android/solving-problems/restricted-profile)?

If not I wanna ask you to collect the log files.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by XtremeMaC** [comment]
I've deleted all AdGuard certificates from the phone. Uninstalled AdGuard and AdGuard VPN.
Reinstalled. It's working now. 
Somehow the certs interfered..
