### ISSUE TITLE
Device Upload Speed Greatly Restricted when AdGuard is Enabled, Can't Send Outgoing Videos on Telegram Messenger,

### ISSUE THREAD

**Issue by richaardvark** [AdguardTeam/AdguardForAndroid#4118]
Hello,

I have noticed recently that whenever AdGuard is activated the upload speeds of my device are greatly restricted. This seems to be apparent whenever I run a general speedtest.net Wi-Fi speed test and is also causing issues with other applications and activities. One noticeable problem is now I am having great difficulty sending out going video message files via the messaging app Telegram. If I try to send someone a video with the AdGuard VPN on the video will trickle out as it is transmitted at a very slow speed with only a few kilobytes per second and will take a long long time if it even ever leaves my phone. As soon as I turn off the AdGuard VPN I am able to send videos again and my download and upload speeds are back to normal as captured on speedtest.net.

AdGuard version: 4.0 nightly 32
Filtering mode: Local VPN
Device: OnePlus 8 (IN2015)
Operating system and version: Android 11
Root access: No

**Comment by Chinaski1** [comment]
Hello there!

At the first glance, this issue is related to https://github.com/AdguardTeam/CoreLibs/issues/1561

Could you please clarify the "before" and "after" speed figures?
Also, different combinations of configurations can affect the performance of sites and applications. Could you please send us the log files so we can look at your configurations and perhaps give tips on how to improve performance?

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Send log files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment]
Any news?
