### ISSUE TITLE
AG pretends to be disconnected from the internet when AG enabled

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#4120]
I'm using version 3.6.7 (not premium). I have this problem even though I'm standing next to the router. Sometimes, when sending pictures and messages on Instagram, it does not send as if the internet connection has been lost. I'm already connected to the internet(WiFi) but the WiFi seems to be cut off every ten minutes I guess. There is no problem with the router, everything works fine on the pc. This problem started after installing AdGuard for Android and it's annoying.
 I'm using DNS filtering: AdGuard DNS, Filtering method: Local VPN and HTTPS Filtering.
 Device: Galaxy J7 Prime. Android: 8.1.0. 
I also tested the speed but it seems normal but I don't know why my messages are not being sent or are being sent late. Sometimes the pages load late in browsers.

**Comment by Chinaski1** [comment]
Hello!

Let's try to clarify a few things:

- Have you tried connecting to another DNS server or changing the protocol?
- Does the problem reproduce only on a certain network?
- And in order to understand the causes of the issue it is desirable to look into the logs

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send log files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by gork7777** [comment]
@Chinaski1 I tried turning off DNS and still the same problem. I tried using cellular data instead of WiFi and still the same problem. I'll send the log.

**Comment by Chinaski1** [comment]
1. As an experiment, could you try disabling all filters and see if the issue is reproduced?
2. If yes - open AdGuard settings -> low-level -> excluded.packages -> `exclude Instagram app` (com.instagram.android).
3. Check again.
4. If still reproduced record a new log archive and send it to us.

**Comment by gork7777** [comment]
@Chinaski1 I did step 2 (exclude) and probably couldn't reproduce it again. This solution might be nice for just one application. But this problem can be annoying for other applications.

**Comment by Chinaski1** [comment]
Can you please send the log files?

**Comment by Chinaski1** [comment]
There is no `log.txt `file in the sent archive 
Exactly we need it  to find reasons of the issue.

**Comment by gork7777** [comment]
Sent it again.

**Comment by sfionov** [comment]
@gork7777

It seems like some kind of route loop, since every connection appears again as "com.adguard.system" with different port. Do you have any other filtering software installed, or unusual network settings? Do you use "secure folder" or "work profile"?
