### ISSUE TITLE
Wifi calling gets disconnected with adguard: Heyah 01 PL

### ISSUE THREAD

**Issue by trawel** [AdguardTeam/AdguardForAndroid#4139]
I have a mesh network at my house. During call, when my phone connects to different access point, sometimes wifi call is continued, most of the times wifi call changes into regular one and sometimes (not sure why) the call gets dropped. Without adguard, everything seems to work fine. What additional data can I provide to make it work better?
Carrier Heyah 01 (subbrand of T-Mobile PL).

### Your environment
- Adguard version: latest stable and nightly (no matter)
- Adguard filtering mode: local proxy (root mode)
- Device model: Oneplus 8T
- Operating system and version Android 12.1 (custom ROM)
- Rooted
- Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by trawel** [comment]
Looks like that might be ROM or home network issue.

**Comment by trawel** [comment]
Unfortunately every setting in my home network didn't help. The issue definately exists when DNS filtering is enabled. I'm currently testing with DNS filtering disabled.
What could I provide to find what's causing the issue?

**Comment by trawel** [comment]
With DNS filtering disabled, the issue still exists. So the problem exists because of Adguard or that's ROM side issue

**Comment by Birbber** [comment]
@trawel Hi. Sorry for the late reply! The issue was lost in the queue for some reason. 
Could you please share the app logs so we could think of something?

Here's what we need you to do:
- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
-  Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@trawel I apologize endlessly. Please tell me if the issue is still relevant?
