### ISSUE TITLE
Mullvad VPN not connecting when Adguard is running

### ISSUE THREAD

**Issue by Iowerth** [AdguardTeam/AdguardForAndroid#4142]
Hi.

- **AdGuard version:**
  - v3.6.7
- **Filtering mode:**
  - Local HTTP Proxy (Auto)
- **Device:**
  - Poco F2 Pro
- **Operating system and version:**
  - Android 10
- **Root access:**
  - Yes
- **VPN app installed:**
  - Only Mullvad VPN. No other VPN apps installed

### Expected Behavior

When pressing connection button in Mullvad then connection must be established.

### Actual Behavior

After pressing connection button in Mullvad connection not establish.

### Workaround

To Mullvad start connecting then I must stop Adguard fully (not only protection).

### Questions

My questions are - why Mullvad not connecting when Adguard is running? Why I need to fully stop Adguard to Mullvad begin to start connecting?

**Comment by Birbber** [comment]
@Iowerth Hi!
AdGuard application creates a vpn connection when you enable it. It's possible to run only 1 VPN application at a time, that's why Mullvad VPN has troubles connecting. Please check [the article](https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy) in which we explain how to configure AdGuard to work as a proxy along with some popular VPN applications.
Or have you already configured it?

**Comment by Iowerth** [comment]
@Birbber

> Or have you already configured it?

No, I haven't. I don't see there about Mullvad. Which paragraph should I use?

**Comment by Birbber** [comment]
It's because there's only several popular vpn on the article. One is assumed to configure AdGuard by the given example.
If there's an option to use SOCKS on Mullvad you should be able to get it working that way with a SOCKS proxy.

**Comment by Iowerth** [comment]
@Birbber there are no any options about proxies in Mullvad. Then I can't use both Adguard and Mullvad in the same time?
