### ISSUE TITLE
Issues with the AdGuard starting

### ISSUE THREAD

**Issue by Olcay23** [AdguardTeam/AdguardForAndroid#4148]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Chinaski1** [comment]
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@Olcay23 we didn't find your logs with us. Specify, did you send us the logs? Could you try again?

**Comment by maxikuzmin** [comment]
@Olcay23 ping
