### ISSUE TITLE
Do not try to filter data: URLs

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#417]
https://github.com/AdguardTeam/AdguardForMac/issues/81

**Comment by Revertron** [comment]
Tests show that there is no bug, we work normally on such pages.

**Comment by ameshkov** [comment]
That's not the point. Parser anyway tries to parse "data:" urls, it's just wrong.

**Comment by ameshkov** [comment]
We now ignore "data:" urls while parsing html code.

**Comment by TPS** [comment]
I'm not sure this is optimum, as I think yes/no handling (filter _all_ `data:` images on a site, iff there is a specific filter saying to do so) might be a good option to have.  However, my default site with such ads (https://noscript.net/) looks clean now, so I'm not sure if it contains something to test this with.

**Comment by ameshkov** [comment]
We'd better hide this or remove with html filtering rules.

Original issue with AG for Mac was about 512kb data url. Checking this url against basic filters took a hell of a lot of time.

**Comment by TPS** [comment]
Because it _is_ NoScript's site, Maone (who's on GitHub ;) is well aware of JavaScript- & Ad-blocking, but, by default, most of these ignore `data:` also.  His ads are _designed_ to exploit that so that HTML filtering was quite difficult, & the only way I found was to remove the default `data:`-ignoring, & filter all `data:` on the site.  I'm sure this isn't the only page to do this.  How would AG handle it?

Wouldn't it be better to ignore `data:` past a certain size?  I have doubts that anyone would put up with a ½MB static ad, anyway.…

**Comment by ameshkov** [comment]
The issue is not about ignoring data: urls everywhere. It is about HTML parsing and removing data: URLs from the page code using basic rules for it (rules which allow you to block web requests).

> How would AG handle it?

Easiest ways:

1. Hide it with element hiding rule: ```##img[src^="data:image"]```
2. Remove it with HTML filtering rule: ```$$img[src="data:image"]```

**Comment by TPS** [comment]
That WFM! ☺
