### ISSUE TITLE
Google Maps app can't navigate with AG v3.6.8 (46) enabled.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#4177]
I can't install AG certificate on my HTC U11 with Pixel Experience 11 PLUS rom, so I have no HTTPS filtering.
https://github.com/AdguardTeam/AdguardForAndroid/issues/4173

I have excluded Google Maps app from AdGuard protection.
With AG v3.6.8 (46) enabled (no HTTPS filtering), Google Maps app still can't navigate.

**Comment by Birbber** [comment]
@lancelot-moon Hi! Could you share the debug logs?
Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send it to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Birbber** [comment]
Have you already sent it?

**Comment by lancelot-moon** [comment]
It seems that the problem is from Pixel Experience 11 PLUS rom.
GPS isn't sensitive.
