### ISSUE TITLE
The BlockList Project Phishing and Scam lists are automatically disabled and cannot be reenabled

### ISSUE THREAD

**Issue by rgiotxy** [AdguardTeam/AdguardForAndroid#4180]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

I've subscribed to DNS filters "The BlockList Project (Phishing)" and "The BlockList Project (Scams)", and I keep enabling them on the DNS filtering console, yet every time I go back there, both lists are disabled again.

- **AdGuard version:**
  - AdGuard for Android 3.6.7
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy A51
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

When I check the box and AdGuard claims to have updated settings, I expect the box to still be checked when I get back.

### Actual Behavior

I check the box and AdGuard claims to have updated settings, but the box is no longer checked when I get back.

### Screenshots

I don't think this calls for a screenshot, though I'm willing to add one if the responders deem one necessary.

### Additional Information

I have eight other DNS filters enabled, most of them also from the BlockList Project. None seem to keep automatically disabling like these two.

**Comment by Birbber** [comment]
@rgiotxy Hi! Sorry for the late reply. To troubleshoot this issue, we need to get debug logs of the application.

Here's what we need you to do:
- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Send the fie to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Birbber** [comment]
@rgiotxy Have you already sent it?

**Comment by zzebrum** [comment]
reopen if needed
