### ISSUE TITLE
Facing an issue with Quic addresses

### ISSUE THREAD

**Issue by TriStaRvOiD** [AdguardTeam/AdguardForAndroid#4186]
I am facing an issue with YouTube playback on the Play Store. When I try to play a video of any app, it doesn't play. 
Checking the logs, Adguard seems to be blocking gquic:// addresses with no reason specified. Here's an image.

![Screenshot_20220614-000246_AdGuard.jpg](https://user-images.githubusercontent.com/58824912/173422590-5b5e5e43-5fb5-4fee-a442-f2f76fd485d9.jpg)

I'm using:
• Adguard 3.6.46
on a
• Samsung S20 FE 5G
• arm64, Snapdragon variant
• Android 12, OneUI 4.1

I could provide more info, if need be.

Whitelisting isn't really helping because the addresses are different each time. 

I'm currently unsure whether this blocking happens for other quic addresses. It probably does.
Apologies if this is a duplicate, or a problem with an obvious fix.

**Comment by TriStaRvOiD** [comment]
Videos are playing now (I didn't do anything). The gquic addresses are still getting blocked though.

**Comment by Birbber** [comment]
@TriStaRvOiD Hi! Try specifying the package names of the applications for which quic will be bypassed.
Go to **AdGuard settings** --> **Advanced** --> **Low-level settings** --> Find `pref.quic.bypass.packages` and type the package names. 
Please let us know the result.

**Comment by TriStaRvOiD** [comment]
> @TriStaRvOiD Hi! Try specifying the package names of the applications for which quic will be bypassed.
> Go to **AdGuard settings** --> **Advanced** --> **Low-level settings** --> Find `pref.quic.bypass.packages` and type the package names. 
> Please let us know the result. 

That worked, thank you. Will close this issue now..
Just out of curiosity though, why are the quic addresses being blocked?

**Comment by Birbber** [comment]
If HTTPS filtering is **disabled** for the application (i.e. filtering is based on hostnames only):
- `GQUIC` is **blocked**. We can't extract the hostname from `GQUIC`, so some ads can be missed
- `QUIC` is filtered by hostname - everything should work fine

If HTTPS filtering is **enabled** for the application (i.e. request filtering is required):
- `GQUIC` is **blocked**. We don't know how to filter requests inside `GQUIC`
- `QUIC` is **blocked** because it may contain HTTP/3, which we don't know how to filter yet. Otherwise, we might miss some ads

In the next 3-4 months or so HTTP/3 support will appear in the application, and we won't be able to block `QUIC`. But `GQUIC`, as an outdated protocol, will most likely remain blocked.

**Comment by TriStaRvOiD** [comment]
> If HTTPS filtering is **disabled** for the application (i.e. filtering is based on hostnames only):
> - `GQUIC` is **blocked**. We can't extract the hostname from `GQUIC`, so some ads can be missed
> - `QUIC` is filtered by hostname - everything should work fine
> 
> If HTTPS filtering is **enabled** for the application (i.e. request filtering is required):
> - `GQUIC` is **blocked**. We don't know how to filter requests inside `GQUIC`
> - `QUIC` is **blocked** because it may contain HTTP/3, which we don't know how to filter yet. Otherwise, we might miss some ads
> 
> In the next 3-4 months or so HTTP/3 support will appear in the application, and we won't be able to block `QUIC`. But `GQUIC`, as an outdated protocol, will most likely remain blocked.

I see.
That's interesting. Thank you, appreciate it.

**Comment by Kingsmanvn-Official** [comment]
@Birbber can you add a feature that allows the use of IETF QUIC?
