### ISSUE TITLE
Не блокируется реклама на rutor.info при использовании прокси-схемы

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#4188]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 
  -  3.6.8
- **Filtering mode:** 
  -  HTTP Proxy/Manual
- **Device:**
  -  Highscreen Boost 3 Pro
- **Operating system and version:**
  -  5.1
- **Root access:**
  -  Yes

### Additional Information

При клике в строке поиска или на каких либо элементах панели поиска на следующей странице (по моему рандомно) открывается новое окно с пачкой редиректов :

```
https://jkhad.com/js/listen.php?b=1236&d=http://rutor.info
https://jkhad.com/click/body.php?hash=b81cf3d7bcd1f9840892c44a4a2fec76&id=1236&r=0.8232318944582642
http://t01.rbnt.org/rsc.php?mode=bu&key=592a6e0fdef71a72adc55886eac171f4&scr=1&p=trft&callback=cbfndblpsrtg
http://di7stero.com/cs?wsa=5fec916b34397942315074&s2=1236
http://di7stero.com/rs?s2=1236&tmp_uid=3d4d60b7ab81ae800698a7b59ea7fdf9&wsa=5fec916b34397942315074&r=js&utm_source=script

```

и хоть у некоторых запросов в логе adguard'а стоит статус "заблокировано", от этой проблемы это не избавляет.

Изначально вопрос разбирали здесь https://forum.adguard.com/index.php?threads/rutor-info.48340 и **Alex302** посмотрев HAR-дамп посоветовал завести issue, сообщив что правила фильтрации есть, но реклама тем не менее не фильтруется из-за использования прокси-схемы.

**Comment by maxikuzmin** [comment]
@Baltazar500 sorry for the long response. We do not see ads on this site 
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@Baltazar500 ping

**Comment by Baltazar500** [comment]
@maxikuzmin, а разве снятого HAR - дампа, что посмотрел Alex302 не достаточно ? Я так понял, он понял в чём проблема. Я думал этот вы вопрос уже утрясли между своими спецами. А теперь ещё оказывается, надо снять дебаг логи и adb багрепорты.  Намедни, если будет возможность, займусь.

**Comment by maxikuzmin** [comment]
@Baltazar500 did you make it? We're waiting for the logs.

**Comment by Alex-302** [comment]
@maxikuzmin Здесь инструкция как проверять
https://forum.adguard.com/index.php?threads/rutor-info.48340/post-223175

**Comment by maxikuzmin** [comment]
@Baltazar500 всё таки нам необходимы дебаг логи, повторите и выгрузите, вышлите на почту [devteam@adguard.com](mailto:devteam@adguard.com) как описано выше с указанием времени, и продублируйте пожалуйста HAR дамп.

**Comment by maxikuzmin** [comment]
@Baltazar500 есть новости?
