### ISSUE TITLE
AdGuard keep stopping on Xiaomi phone despite setting the phone up as described in kb

### ISSUE THREAD

**Issue by binarweb** [AdguardTeam/AdguardForAndroid#4199]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - latest version
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Xiaomi Redmi 9
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

After a few minutes (usually 15) after the screen is off, AdGuard for Android keeps closing and a notification pops-up saying that I should setup my device [as described in the help (kb)](https://kb.adguard.com/en/android/solving-problems/background-work).  
I already did the two required steps. The battery saver is off and the "Security" app has on "Lock apps" the AdGuard app.

**Comment by maxikuzmin** [comment]
@binarweb  your issue is still relevant? 
We have now developed an interesting feature - "Watchdog" in AdGuard VPN. 
If your VPN is failing as well, you can try this feature. 
Soon we will add the same feature to AdGuard too.

**Comment by binarweb** [comment]
@maxikuzmin AdGuard for Android already has the "Watchdog" feature and I've set it the first time I've seen it, but AdGuard keeps closing. It had no effect.

**Comment by maxikuzmin** [comment]
@binarweb as far as I know, this feature has not been added to AdGuard now. Send us your logs, just in case, and we'll take a look at them.

Here's what we need you to do:


- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by binarweb** [comment]
I've collected and sent the debug logs to adguard team. Thanks for the info!

@maxikuzmin have [a look](https://imgur.com/a/cp7rwnF) at the "Watchdog" feature.

**Comment by maxikuzmin** [comment]
@binarweb сейчас эта функция работает не так, как должна. Как я уже говорил, ее планируют доработать в следующем обновлении, будет полноценный Watchdog. Пока что могу посоветовать в настройках закрепить приложение. Boost -> Lock Apps -> add AdGuard. Должно помочь
![image (5)](https://user-images.githubusercontent.com/101641415/182841696-3d17ea68-5ace-4357-aa19-6ecef3a08350.png)

**Comment by maxikuzmin** [comment]
@binarweb did this temporary solution help you?

**Comment by maxikuzmin** [comment]
@binarweb any news?

**Comment by maxikuzmin** [comment]
@binarweb this [article](https://kb.adguard.com/en/android/solving-problems/background-work) was recently updated, check it out. That should also help

**Comment by binarweb** [comment]
@maxikuzmin sorry about the slow response. I already added AdGuard to "Lock Apps" as stated in [my first post](https://github.com/AdguardTeam/AdguardForAndroid/issues/4199#issue-1290990718) of this issue.
