### ISSUE TITLE
"Internet is not available" after update

### ISSUE THREAD

**Issue by Beege1** [AdguardTeam/AdguardForAndroid#4210]
![Screenshot_20220802-215233](https://user-images.githubusercontent.com/51408697/182520599-7bc94f8b-d77e-4e57-b404-6e4229f256ba.jpg)

After upgrading to 3.6.9 for Android, I'm now get error msgs "internet is not available"

**Comment by maxikuzmin** [comment]
@Beege1 what version of android do you have?

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@Beege1 any news?

**Comment by hasan4791** [comment]
Same here,
Looks like its getting blocked at ISP level. I'm from India and seeing this error in Airtel Broadband with ipv4 & ipv6 enabled but it works in Airtel 4G.

**Comment by maxikuzmin** [comment]
@hasan4791 @Beege1 issue in the works

**Comment by ameshkov** [comment]
Could you please check this build?
https://uploads.adguard.org/adguard-android_dev_build.apk

**Comment by Beege1** [comment]
That version seems to work. Thank you.

Brian Milburn

**Comment by maxikuzmin** [comment]
@Beege1 great news! Good luck!

**Comment by Beege1** [comment]
Good day,

Received an update notice to version 3.6.10 beta 1 and same problems have
returned.

Best regards
Brian Milburn

**Comment by ameshkov** [comment]
@Beege1 weird stuff, could you please send the log to us again?

**Comment by ameshkov** [comment]
@Beege1 okay, nevermind, found the problem with the build, there'll be another update soon.

**Comment by Beege1** [comment]
That seems to be working. Thanks again.

**Comment by Beege1** [comment]
Received the lastest non-beta version 3.6.10 and all is good. Keep up the
good work!
