### ISSUE TITLE
AdGuard protection is being disabled when enabling AdGuard VPN and vice versa.

### ISSUE THREAD

**Issue by driversti** [AdguardTeam/AdguardForAndroid#4229]
I have AdGuard always on and for some sites I need to use VPN. From time to time when I need to enable AdGuard VPN, AdGuard protection stops working. I enable protection, but VPN switches off. Thus, I need to choose what I want to use: AdGuard App or AdGuard VPN. This is obviously it is not related to Android version, because the same issue exists on A13 as well as on A12. I can't remember for sure, but it seems I spotted that issue on A11 too.

Device:
- Pixel 4a (5G), Android 13

AdGuard app:
- v3.6.7 (41)
- Filtering method: Local VPN
- DNS providers: AdGuard DNS, server type: DNS-over-HTTPS

AdGuard VPN:
- v2.1.2 beta 1 (53)

**Comment by maxikuzmin** [comment]
@driversti please clarify if you have compatibility mode enabled in both applications? Also clarify, have you tried downloading version 3.6.10? Why are you not updating?

**Comment by driversti** [comment]
As of now, I have v.3.6.10 (51). I didn't find steps to reproduce the error. Usually it stops working after 3-7 days. Then I need to reboot my phone and the problem is resolved for a few days.
Both applications are set to compatibility mode.

**Comment by maxikuzmin** [comment]
@driversti could you please record debug logs after repeating the situation?

**Comment by driversti** [comment]
@maxikuzmin sure. We just need to wait when this issue will occur again.

**Comment by maxikuzmin** [comment]
@driversti any news?

**Comment by githubuser013** [comment]
I am facing the same issue, it appears that for some reason when this happen adguard ad blocker compatibility mode option with adguard VPN in advanced settings disappear, until restart the phone.

Were i can send the logs?

**Comment by driversti** [comment]
> @driversti any news?

Not yet 😞

**Comment by maxikuzmin** [comment]
@driversti  here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

However, please clarify the steps to reproduce this problem? At what point do you change compatibility mode? 
When it changes, have you tried changing the mode back? 
If you reboot, does compatibility mode in both applications return to its original position and both run in standard mode simultaneously?

**Comment by maxikuzmin** [comment]
@driversti any news?

**Comment by maxikuzmin** [comment]
@githubuser013 here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to [devteam@adguard.com](mailto:devteam@adguard.com). Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by githubuser013** [comment]
@maxikuzmin 

I upgraded my android from 12 to 13 now everything works normally. I have never faced the issue since the upgrade.
I haven’t changed the compatibility mode on both apps but seems ag ad blocker hide the compatibility mode option when the issue occurs, restart the phone or turn off the ag ad blocker and turn it on again solve the problem, and I can see compatibility mode again automatically.
It happened very rarely and randomly I can’t reproduce the issue, so I’ll keep an eye when this happened again and upload the logs.

**Comment by maxikuzmin** [comment]
@githubuser013 we are aware of this problem. This will be revised in version 4.0, the exact release date is not yet known, but it will happen very soon. Please wait for version 4.0

**Comment by driversti** [comment]
Hi @maxikuzmin 
Finally I've got this issue again. What steps should I perform to provide all necessary information?

**Comment by githubuser013** [comment]
I think i found the cause of the problem, it was (Always-on VPN) option under android settings.
If that option enabled after some time (maybe days) the issue occur.

@driversti 
Is that option enabled in your device? can you confirm Please.
![Screenshot_2022-12-16-07-31-05-30_41a74ddf68be21faad2fbbb691b15143](https://user-images.githubusercontent.com/71437659/208023034-23e12e9c-9d71-41b9-bcc2-29a1658a814a.jpg)

**Comment by driversti** [comment]
Hi @githubuser013 Thank you for your engagement! This option is turned off. (Google Pixel 7 Pro, Android 13)
