### ISSUE TITLE
DNS "dns.adguard-dns.com" does not connect

### ISSUE THREAD

**Issue by BeatDeath** [AdguardTeam/AdguardForAndroid#4231]
I'm trying to connect with your private dns dns.adguard.com in a other device but keeps telling me can't connect
Thanks for the help

**Comment by maxikuzmin** [comment]
@BeatDeath you must mean dns.adguard-dns.com ? 
Please check actual DNS server addresses on this [link](https://adguard-dns.io/kb/general/dns-providers/)

**Comment by maxikuzmin** [comment]
@BeatDeath any news?

**Comment by U0101100** [comment]
Android 12. samsung Note 10+. Can't set up Android DNS with Adguard data. if I trying to connect with DNS Adguard I lose net connection or is not working 
![SmartSelect_20220905_191137_Settings](https://user-images.githubusercontent.com/100161152/188493822-b4e99299-8581-4d8c-929d-e938ddd439e1.jpg)
![SmartSelect_20220905_191118_Settings](https://user-images.githubusercontent.com/100161152/188493823-d79c2dec-7e44-402e-8b16-5cb234fdc726.jpg)

**Comment by maxikuzmin** [comment]
@BeatDeath the issue is closed. If the problem is still relevant, you can reopen the issue

**Comment by maxikuzmin** [comment]
@U0101100 could you please record a video of what you are doing to understand all your steps? Also clarify what DNS you are trying to add, because we were talking to @BeatDeath about DNS "dns.adguard-dns.com"?

**Comment by maxikuzmin** [comment]
@BeatDeath any news?

**Comment by maxikuzmin** [comment]
@U0101100 any news?

**Comment by niStee** [comment]
Title: Recursion issue with tls://dns.adguard-dns.com on Android 14

Description:

I'm experiencing a connection issue with AdGuard DNS on Android 14. When trying to establish a connection using tls://dns.adguard-dns.com, I encounter a possible recursion error. I've attached screenshots for reference.

Environment:

Android version: 14
AdGuard DNS configuration: tls://dns.adguard-dns.com
Steps to reproduce:

Configure AdGuard DNS on Android 14 using tls://dns.adguard-dns.com
Attempt to establish a connection
Expected result: Successful connection establishment

Actual result: Connection cannot be established due to possible recursion error

Attachments: ![Screenshot_20240923-180257.png](https://github.com/user-attachments/assets/46f03f72-8f8f-4c0d-a3e0-6e2f4c0a779b)

![Screenshot_20240923-180341.png](https://github.com/user-attachments/assets/a3d5b4b3-8dfb-4774-add0-205dec7a5683)
