### ISSUE TITLE
Adguard conflicts with LG U+ network provider

### ISSUE THREAD

**Issue by Elimiriel** [AdguardTeam/AdguardForAndroid#4267]
It seems that LG U+, S. Korea cellular network provider, doesn't allow to run Adguard. All apps under the control of Adguard cannot connect to network since I transfered from other network provider. Logs say (A or AAAA), SERVFAIL. Could we find the solution for this problem?

**Comment by Elimiriel** [comment]
In a cirtain log of hails says DNS response is SERVFAIL.

**Comment by Elimiriel** [comment]
I specify to the DNS filtering. Turning the feature off makes seems working now...

**Comment by maxikuzmin** [comment]
@Elimiriel if you disable DNS filtering, everything works correctly? Have you tried choosing a different DNS? That might also help

**Comment by Elimiriel** [comment]
Yes it does. Changing different DNS provider (I tried default and Cloudflare) did not working. Only turning the whole feature of DNS filtering does work.

**Comment by Elimiriel** [comment]
It's weird, 1.1.1.1 dns changing app from the cloudflare does work, in similar way as Adguard; setting local VPN.

**Comment by Elimiriel** [comment]
I've found that switching from VPN mode to local https proxy mode, which is rooted phone only, makes network with DNS filtering again. That's not for non-rooted phones though.

**Comment by maxikuzmin** [comment]
@Elimiriel to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@Elimiriel any news?

**Comment by Elimiriel** [comment]
Sorry, I am positive with CoVID-19, and swiched to other network provider(SKT)... Even though, I could suspect conflict with other dns changer magisk module called "cloudflaredns for ipv4/ipv6".

**Comment by maxikuzmin** [comment]
@Elimiriel clarify, do you still have a problem with your network provider? Or after changing your network provider is the problem no longer reproducing?

**Comment by maxikuzmin** [comment]
@Elimiriel for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
