### ISSUE TITLE
adguard shows weird rules blocking legit domains

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4279]
![Screenshot_20221120_150547_AdGuard](https://user-images.githubusercontent.com/118186787/202926237-e0af2abc-c76c-463a-8c86-a0e485802a94.jpg)
![Screenshot_20221120_150241_AdGuard](https://user-images.githubusercontent.com/118186787/202926238-365a4550-4c1b-4f56-8aa0-b81a371ccdd1.jpg)

what does this mean. or how to fix this

**Comment by jordanswrld94** [comment]
@Alex-302

**Comment by Alex-302** [comment]
> @Alex-302 

Probably a bug. I don't see such rule.

**Comment by jordanswrld94** [comment]
thats what I'm wondering ive been using rhe blocking without that list for days now and everything works fine.

**Comment by maxikuzmin** [comment]
@jordanswrld94 to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@jordanswrld94 any news?

**Comment by jordanswrld94** [comment]
@maxikuzmin did my log help figure out anything?

**Comment by maxikuzmin** [comment]
@jordanswrld94 we need some time, please wait

**Comment by maxikuzmin** [comment]
@jordanswrld94 can you send us extended logs as instructed above? We need the exact time of the recurrence of the problem

**Comment by jordanswrld94** [comment]
@maxikuzmin i did. above along with the time. 7:57:43

**Comment by maxikuzmin** [comment]
@jordanswrld94 I wrote about it:
Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to [devteam@adguard.com](mailto:devteam@adguard.com). Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@jordanswrld94 any news?

**Comment by jordanswrld94** [comment]
heres the androidnone https://ufile.io/c7geh7fd

@maxikuzmin

**Comment by maxikuzmin** [comment]
@jordanswrld94 now there's no need for screenshots of the filter log... I'll text you a third time:

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to [devteam@adguard.com](mailto:devteam@adguard.com). Mention the Github issue number and the exact time when the issue was reproduced.

Your file at the link is blocked by the browser as "suspicious". 
Do you have any difficulties with sending debug logs to the mail? If you do not understand something, I can help you. 
It is also important for us to understand time of error occurrence, so we ask you to repeat steps, record debug logs, specify time of problem reproduction. 
Please do as in instructions or attach debug logs right here, to your email, with time.

**Comment by jordanswrld94** [comment]
files sent with email

**Comment by jordanswrld94** [comment]
i had to send files with an app  my email wont let me send files over 27mb. is there a different email app u recommend

**Comment by jordanswrld94** [comment]
got it. files sent

**Comment by maxikuzmin** [comment]
@jordanswrld94 any news?

**Comment by jordanswrld94** [comment]
what app can i use to send the files all in one email. sorry having trouble sending

**Comment by anonymous-user** [comment]
Can you compress the files into a ZIP file to make it smaller?

**Comment by jordanswrld94** [comment]
they already are in zip format

**Comment by anonymous-user** [comment]
Try uploading to a different cloud service. Perhaps Dropbox or Google Drive. Should be more reputable and less likely to be flagged.

**Comment by jordanswrld94** [comment]
ok sent

**Comment by maxikuzmin** [comment]
@jordanswrld94 I got the logs, we'll check them out

**Comment by sfionov** [comment]
@jordanswrld94 Can you please check which subscription URL is shown in the details of AdGuard URL Tracking filter?

Settings -> Content blocking -> Filters -> Privacy -> AdGuard URL Tracking filter

<details><summary>Example</summary>
<img src=https://user-images.githubusercontent.com/47204/209447549-2d64996c-28e7-46c7-b28f-076b3acf6d49.jpg>
</details>

**Comment by jordanswrld94** [comment]
![Screenshot_20221224_123424_AdGuard](https://user-images.githubusercontent.com/118186787/209447708-ee69cc10-a41d-48ab-8444-cc91af973cf5.jpg)
 @sfionov

**Comment by sfionov** [comment]
@jordanswrld94

URL is correct. It seems that stored filter is somewhat broken.

Your problem can be fixed by triggering filter updates when this filter is enabled - filter will be re-downloaded.

We'll add additional integrity checks into future versions.

**Comment by jordanswrld94** [comment]
that seemed to have worked. i never thought of updating im sorry
