### ISSUE TITLE
Unable to restart adguard once it is killed by the OS memory managment.

### ISSUE THREAD

**Issue by sangalaviral** [AdguardTeam/AdguardForAndroid#4307]
Issue Details

- **AdGuard version:**
  - 3.6.10 (51)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Oneplus 10 Pro
- **Operating system and version:**
  - Android 13/OOS 13
- **Root access:**
  - Yes

### Expected Behavior

Should be able to restart Adguard once it gets kicked out of memory by OS

### Actual Behavior

Once Adguard is kicked out of the memory and killed by the OS, I can no longer start Adguard and it will hang on the splash screen. Only fix is to re-start the device

### Additional Information

I have already enabled background activity, auto start and disabled batter optimization for Adguard.

**Comment by maxikuzmin** [comment]
@sangalaviral I don't have this error repeated.
to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@sangalaviral any news?

**Comment by maxikuzmin** [comment]
@sangalaviral for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
