### ISSUE TITLE
Adguard and Adguard DNS blocks Fitbit internet services. 

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdguardForAndroid#4315]
Hello. Adguard services block Fitbit internet service on the app. 

*Adguard VPN does not seem to cause any issues.*

![Screenshot_20230103-113919.png](https://user-images.githubusercontent.com/72349391/210598866-40293de6-706f-450c-bd97-8daa01e4a686.png)

Turning off Adguard and the DNS fixes the issue. 

![Screenshot_20230103-121328.png](https://user-images.githubusercontent.com/72349391/210598976-406a30ab-b876-4dbc-969a-35363fc7b17c.png)

Where to see this:
Fitbit app, touch profile picture, Fitbit watch e.g. sense 2, then gallery.

**Comment by maxikuzmin** [comment]
@Perfectlynk to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@Perfectlynk any news?

**Comment by Perfectlynk** [comment]
I have send the data.

**Comment by maxikuzmin** [comment]
@Perfectlynk your issue is in progress. We need a little more time

**Comment by Perfectlynk** [comment]
Sure no problem.

**Comment by maxikuzmin** [comment]
@Perfectlynk this is similar to [#82264](https://github.com/AdguardTeam/AdguardFilters/issues/82264)
Please try checking this with filters disabled, then with DNS disabled, then with app filtering turned off. 
Is the Fitbit blocked in all cases?

**Comment by maxikuzmin** [comment]
@Perfectlynk any news?

**Comment by Perfectlynk** [comment]
@maxikuzmin I turned all of them off and Fitbit gallery is still blocked.
Adguard DNS on WiFi could be blocking it but can't turn it off to check right now as it's being used by family.

I'll check tonight.

**Comment by Perfectlynk** [comment]
Update I have to turn off everything you mentioned plus the DNS to fix Fitbit.

**Comment by maxikuzmin** [comment]
@Perfectlynk have you tried unblocking the domains listed in the other[ issue](https://github.com/AdguardTeam/AdguardFilters/issues/82264#issuecomment-846962620)?

**Comment by maxikuzmin** [comment]
@Perfectlynk any news?

**Comment by Perfectlynk** [comment]
Yes I checked and it is Google Analytics. When allowed it works. Thanks for looking into it. I guess if I need the Gallery I'll temporally allow it.

**Comment by maxikuzmin** [comment]
@Perfectlynk glad to hear the problem was solved! Good luck!
