### ISSUE TITLE
No internet connection after turning on filtering

### ISSUE THREAD

**Issue by konnoyuukilove** [AdguardTeam/AdguardForAndroid#4372]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6和4.0最新

### Environment

```markdown
小米13
安卓13
miui14.0.13
```

### Root access

- [X] Yes, I have it.

### Issue Details

开启过滤后无网络连接，dns和安卓疯狂请求

### Screenshots

![Screenshot_2023-01-29-19-27-30-818_com adguard android](https://user-images.githubusercontent.com/111185364/215323842-580e248b-bd7a-42ef-a18e-cd6776f2aad9.jpg)
![Screenshot_2023-01-29-19-31-02-873_com adguard android](https://user-images.githubusercontent.com/111185364/215323855-abfc2e14-4925-4d52-9efc-4521db1716e2.jpg)
![Screenshot_2023-01-29-19-32-22-179_com adguard android](https://user-images.githubusercontent.com/111185364/215323858-0025cf7e-06d4-4da0-8c2f-f2740e2b9a28.jpg)
![Screenshot_2023-01-29-19-35-21-685_com adguard android](https://user-images.githubusercontent.com/111185364/215323860-ee0370bb-7bb1-437d-a1f9-a462477ad386.jpg)

**Comment by maxikuzmin** [comment]
@konnoyuukilove to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@konnoyuukilove any news?

**Comment by maxikuzmin** [comment]
@konnoyuukilove for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
