### ISSUE TITLE
Can't Pause Adguard in v4.0 Nightly 39 

### ISSUE THREAD

**Issue by aespapa** [AdguardTeam/AdguardForAndroid#4406]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 Nightly 39 

### Environment

```markdown
- OS: Android 13
- Device: Samsung Galaxy
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

1. doesn't work pause in Adguard App.
2. Also Notification Pause Button doesn't work.
3. restart again When paused. at this time network connection not working.

https://user-images.githubusercontent.com/92372212/216219793-a8d5464c-9905-4308-b7a4-7b7204d2f5d5.mp4

**Comment by redtrillix** [comment]
Yeah i had this problem too, and the only way to close the app was to kill the background app.


_Phone: Samsung Galaxy A23_
_OS: Android 13_
_Version: AdGuard Premium for Android 4.0 Nightly 39_

**Comment by maxikuzmin** [comment]
@aespapa @redtrillix I don't have this problem repeated. Does it still happen on version 42?
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by redtrillix** [comment]
> @aespapa @redtrillix I don't have this problem repeated. Does it still happen on version 42?
> To troubleshoot this issue, we need to get additional logs.
> 
> Here's what we need you to do:
> 
> - Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
> - Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
> - Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
> - Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

Yeah, sorry my bad.

As of Nightly 40 or 41(currently on 42) i dont have a problem with this anymore.

**Comment by maxikuzmin** [comment]
@redtrillix great! Glad to hear it! 
If you notice anything else, be sure to create new issues

**Comment by aespapa** [comment]
@redtrillix it cools now
