### ISSUE TITLE
Easier access to "Apps management" in version 4

### ISSUE THREAD

**Issue by satomi-ynk-sg** [AdguardTeam/AdguardForAndroid#4408]
### Issue Details

In version 3, we can access "Apps management" right from the menu and switch "AdGuard protection" and "Ad blocking" settings immediately.

In version 4 nightly 39, we have to tap Settings, Filtering, Apps, and then App management.
I would like to have easy access to Apps management so that we can turn on and off Ad blocking and AdGuard protection when we have problems using apps. 

### Proposed solution

How about moving Apps management right under Settings?

**Comment by gitthangbaby** [comment]
Can we bring it right into the bottom bar together along with traffic history? It was MUCH easier to operate AdGuard3.
Also there's so many app views now, and one of them is useful "[Home\chart\]Statistics\Recent Activity\View all Apps" (deep in menus again) as it's sorted by traffic versus "Settings\Filtering\Apps\App management\" (deep again) or versus "Protection\Firewall\Custom Firewall rules" (deep again). But once you click on an app, you need to operate the tiny "|" icon to change its rules which is another annoying and precise 2 click.

Separating Protection vs Settings\Filtering\Filters (deep again) is unwelcome imo.

Confusing & unproductive UI indeed, i still couldn't learn it despite 30y passion for UI & QA. It's all bout Settings + History + Apps all day long. At this point i wish the quick icon opened Assistant instead of full UI as that is helpful.

**Comment by TPS** [comment]
v4.2n1's UI is _much_ better, thanks! 🙇🏾‍♂️

**Comment by vonDubenshire** [comment]
Just saw this in the update notes for today!

![Uploading Screenshot_20230721-164046.png…]()

**Comment by leacha69** [comment]
The Filtered apps page is missing now. That page was easy for a quick glace showing which apps were routed through AdGuard. Now you have to click on each app to see.

**Comment by Peter-maximus** [comment]
any update?

especially on:
_The Filtered apps page is missing now. That page was easy for a quick glace showing which apps were routed through AdGuard. Now you have to click on each app to see._
