### ISSUE TITLE
Nightly release notes have stopped

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForAndroid#4435]
Since the latest round of nightlies has started, the release notes have stopped, only appearing in-app on the update.

Is there any chance the changes can start getting added to the release notes website/GitHub again, or is it put on hold for the moment?

**Comment by maxikuzmin** [comment]
@jslawler of course we will continue to add to the release notes website and GitHub again :) 
Right now we want to release a new nightly version every day so that users get bug fixes quickly and don't have to wait until the next big update.
We'll be sure to tell about all the fixes and changes in the next big update!
