### ISSUE TITLE
VPN fails to start when coming back from the Plane mode

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#445]
The VPN creation fails after coming back from the plane mode. I have to delete the VPN from Android settings and the enable manually adguard. It doesn't work and I can't send reports using the app it gives an error when I click send

I am using a LG g4 with Android 6

It worked well at the beginning but suddenly the VPN creation started to
give error while coming back from plane mode. I have temporary find a fix
by enabling the setting pref.vpn.disable.pause

Logs: ZKK-676-70343

**Comment by ameshkov** [comment]
Weird, I see that Android just does not allow us to create a VPN:
```
Error building vpn interface

java.io.IOException: vpnInterface is null
	at com.adguard.android.vpn.AdguardVpnService.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$1.run(Unknown Source) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

I can't yet understand what is a root cause of this behavior.

Steps to reproduce (from user):
> Delete VPN from android
> Enable adguard and disable several times. Ok
> Set plane mode
> Disable plane mode
> Adguard isn't able to enable
> Try to enable adguard manually. Fail

I wonder what is the first step? What VPN to delete?

**Comment by evgeniy-ADG** [comment]
Will ask.

**Comment by lordraiden** [comment]
I do the first step just to simulate the process from the beginning.

Adguard creates a VPN entry in android settings, in VPN configuration. If this entry is already there I can't activate Adguard, but If I delete the adguard VPN entry, adguard is able to create it again and enable the VPN. If I left the adguard VPN entry in android settings, adguard isn't able to enable either manually or automatically. So what I do is to long click on the VPN entry and then click on Forget.

One workaround I found is to keep the VPN always ON by enabling "pref.vpn.disable.pause" in the low level settings.

So for some reason adguard isn't able to re-enable the VPN if the VPN entry is already created in android VPN settings.

I hope this help to understand the issue.  If you need any other detail let me know.
I'm using android 6, but I didn't have this issue with the stable version.

**Comment by ameshkov** [comment]
> Adguard creates a VPN entry in android settings, in VPN configuration.

I suppose this entry is created implicitly by Android as we just cannot do it on purpose.

> but I didn't have this issue with the stable version.

Could you please try installing the stable version and see if it works ok now.

**Comment by lordraiden** [comment]
I can reproduce it with the stable version as well. I can enable and
disable after install but if I go to plane mode after coming back I get
this error.

Adguard creates a VPN entry in android settings, in VPN configuration.

I suppose this entry is created implicitly by Android as we just cannot do
it on purpose.

but I didn't have this issue with the stable version.

Could you please try installing the stable version and see if it works ok
now.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/AdguardTeam/AdguardForAndroid/issues/445#issuecomment-211320648>

**Comment by ameshkov** [comment]
> I can reproduce it with the stable version as well. I can enable and
> disable after install but if I go to plane mode after coming back I get
> this error.

It seems that Android has somehow "saved" wrong VPN trust settings for com.adguard.android package. I wonder if it's possible to reset all these settings without resetting Android.

Just guessing: have you tried rebooting device?

**Comment by lordraiden** [comment]
After restart I can enable and disable adguard. But if I go to plane mode
and then come back it doesn't work. So probably is something related with
the process that android 6 does when using the plane mode.

Regards

**Comment by ameshkov** [comment]
I am sure the issue is not in Android 6.0 as you're the only one with such an issue. Also I suspect that hard reset will fix the issue (yeah, I know, that's not a very good solution, but anyway).

If only there was some way to clear android permissions settings without hard reset.

**Comment by lordraiden** [comment]
Maybe is because I have installed airwatch and is blocking some
permission.  I won't  do a hard reset for now, I will enable
pref.vpn.disable.pause as a workaround.  Does this have any disadvantage?

I hope you can implement soon the idea of blocking the traffic of certain
apps when the phone is locked, like doze does but more configurable.

Regards
El 22 abr. 2016 13:48, "Andrey Meshkov" <notifications@github.com> escribió:

I am sure the issue is not in Android 6.0 as you're the only one with such
an issue. Also I suspect that hard reset will fix the issue (yeah, I know,
that's not a very good solution, but anyway).

If only there was some way to clear android permissions settings without
hard reset.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/AdguardTeam/AdguardForAndroid/issues/445#issuecomment-213391023>

**Comment by ameshkov** [comment]
> Does this have any disadvantage?

Depends on the device/firmware. I guess you would have felt it already if this protection restart was necessary in your case.

> I hope you can implement soon the idea of blocking the traffic of certain
> apps when the phone is locked, like doze does but more configurable.

Yep, we have it in the road map.
