### ISSUE TITLE
running Adguard with Sagernet results in no connection.

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForAndroid#4455]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 nightly 45

### Environment

```markdown
- OS: android
- Device: galaxy s10
- Firmware:
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Disable WebRTC, Block Push API, Block Location API, Protect from DPI

### Issue Details

Steps to reproduce:
1. connect to sagernet
2. run Adguard
3. browser for a minute or so and then you can't access to anything unless you try to turn off AG.

### Actual Behavior

https://user-images.githubusercontent.com/40741745/218088164-3af23e46-2104-4085-8ba3-326bc23d0a3a.mp4

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@aliafshany I think it has to do with the "Firewall" setting. Try going to Apps management -> SagerNet -> App firewall settings -> enable all switches to use mobile data / wifi
You can also just go to Apps management -> SagerNet -> context menu -> tap on Reset to default

**Comment by aliafshany** [comment]
i did this to get Adguard+Sagernet get to work together.
it's interesting that I had to turn off the DNS option.
idk why but if it was turned on, only sagernet was working because I had excluded it in the settings and none of other apps even chrome didn't work. i could see ! mark on wifi logo too. 


![image](https://user-images.githubusercontent.com/40741745/218554720-97e6b1c2-53ec-4a64-b6a1-15b0e3b8aa83.png)
![image](https://user-images.githubusercontent.com/40741745/218554728-70a77852-3dbf-48a7-a4ae-76f26be108c3.png)
![image](https://user-images.githubusercontent.com/40741745/218554740-cbc3cc36-fbea-4bd6-a781-be0d262c5418.png)

**Comment by Rtizer-9** [comment]
@aliafshany this dns thing is normal considering that sagernet and the likes handle their dns routing in their own way. If you want to use sagernet while keeping dns filtering on in adguard one option is to look into the section "dns setting" of sagernet and try toggling those two options available there (dns routing and local/direct dns).

Second option is to feed adguard with the local dns server of sagernet itself. If you've not changed it then the dns port of sagernet must be 6450 by default which you can feed into adguard by using 127.0.0.1:6450 as dns server address. System is now gonna use the dns server depending on the remote dns server in sagernet and those above two toggles I mentioned above. ( sagernet must be turned on before adding that local dns server otherwise it won't get validated).

**Comment by maxikuzmin** [comment]
@Rtizer-9 thanks for your advice!
@aliafshany please let us know the results

**Comment by aliafshany** [comment]
@Rtizer-9 
@maxikuzmin 

I tried using sock5 ip: port in Sagernet, and here is the result.
It works without a problem, but, after a while which is more than an hour, I get an ! mark on my wifi logo In order to get rid of it, i  have to manually turn on and off Adguard and then reconnect Sagernet.
during that time nothing works btw. it's a blackout.

please see the video ( sorry for the quality, i had to convert it to get it smaller in size):

https://user-images.githubusercontent.com/40741745/218959018-731d057d-993d-4e90-9f2c-2ce8fcdae965.mp4

**Comment by Rtizer-9** [comment]
I'm kinda busy at the moment; I'll reply as soon as I get free. Meanwhile did you did try that dns thing I told above?

Also instead of socks5 proxy you can use that http inbound proxy port 9080.

There's an advance setting in adguard which exposes dns filtering option while configuring proxy so you might wanna check that out too.

That dns exclamation mark thing used to happen with me a lot and even now sometimes but it doesn't happen once I use my setup.

**Comment by aliafshany** [comment]
> I'm kinda busy at the moment; I'll reply as soon as I get free. Meanwhile did you did try that dns thing I told above?
> 
> Also instead of socks5 proxy you can use that http inbound proxy port 9080.
> 
> There's an advance setting in adguard which exposes dns filtering option while configuring proxy so you might wanna check that out too.
> 
> That dns exclamation mark thing used to happen with me a lot and even now sometimes but it doesn't happen once I use my setup.

@Rtizer-9 
yes thank you I did some stuff there and at last, I managed to get it to work thanks to you.
but this ! mark happens many times a day, and it's becoming so annoying tbh.
turning off and on Adguard and Sagernet consumes so much time every time.
i hope @maxikuzmin  could investigate this.

**Comment by maxikuzmin** [comment]
@aliafshany yes, I think this topic will come in handy for someone in the future. Please elaborate on what you did in the end to get Adguard and Sagernet to work

**Comment by Rtizer-9** [comment]
@aliafshany I would be happy to assist you if you can provide me the vmess (or ?) config you're trying to use so that I can test it on my end otherwise it's gonna be a lot of back and forth exchange of us discussing about fiddling with all those sagernet options until we get it working. I'm not well versed with what's actually going on under the hood, I came up with my config after a lot of hit and trial to final get it working. 

If the config involves some private url you can't make public then I'm open to other ways you wanna discuss.

I'd actually need to fine tune a lot of options which you didn't record in the video (I couldn't see the dns server I told you above to setup) so that's gonna take a lot of time if I'll keep asking you to fiddle with one option after another.

**Comment by maxikuzmin** [comment]
@aliafshany @Rtizer-9 for the moment, I’m closing this issue. 
Your experience is sure to be of use to other users in the future. If you would like to add anything to this topic in the future, please write here

**Comment by Rtizer-9** [comment]
@maxikuzmin His issue doesn't seem to have been solved. He was asking for your input in his last comment.

**Comment by maxikuzmin** [comment]
@Rtizer-9 hmm, I must have misunderstood. @aliafshany what about the configuration you're using?
@Rtizer-9 perhaps you could provide your own configuration? I think that might also help.

**Comment by Rtizer-9** [comment]
@maxikuzmin I'm not using Sagernet at the moment and also never used vmess which is what perhaps he is using so maybe his logs are of more importance here I guess.

**Comment by maxikuzmin** [comment]
@aliafshany is a frequent guest in our repository :) I think he'll be able to respond a little later. It would be nice to understand the intricacies of the configuration

**Comment by aliafshany** [comment]
> @aliafshany I would be happy to assist you if you can provide me the vmess (or ?) config you're trying to use so that I can test it on my end otherwise it's gonna be a lot of back and forth exchange of us discussing about fiddling with all those sagernet options until we get it working. I'm not well versed with what's actually going on under the hood, I came up with my config after a lot of hit and trial to final get it working.
> 
> If the config involves some private url you can't make public then I'm open to other ways you wanna discuss.
> 
> I'd actually need to fine tune a lot of options which you didn't record in the video (I couldn't see the dns server I told you above to setup) so that's gonna take a lot of time if I'll keep asking you to fiddle with one option after another.

@Rtizer-9  I apologize for the long delay. It was due to a university matter. I'd be delighted to share the V2Ray configuration with you. Rather than posting it here, could you provide me with a Telegram ID or email address? Alternatively, you can send an email to me at [ali.afshany@gmail.com]

**Comment by aliafshany** [comment]
> @Rtizer-9 hmm, I must have misunderstood. @aliafshany what about the configuration you're using? @Rtizer-9 perhaps you could provide your own configuration? I think that might also help.

@maxikuzmin 
Sure, I can share that configuration with you, but first, could you please share an email or Telegram ID link with me so I can send it?

**Comment by maxikuzmin** [comment]
@aliafshany of course! You can send it to our email devteam@adguard.com with the issue number

**Comment by aliafshany** [comment]
@maxikuzmin  sent!

**Comment by maxikuzmin** [comment]
@aliafshany thank you! 
@Rtizer-9 maybe you have something to add/comment on the configuration?

**Comment by maxikuzmin** [comment]
@aliafshany sorry for the long reply. I haven't been able to replicate the internet drop with your configuration yet. How often do you have this happen in a day?

**Comment by maxikuzmin** [comment]
@aliafshany @Rtizer-9 any news?

**Comment by uaevuon** [comment]
> I'm kinda busy at the moment; I'll reply as soon as I get free. Meanwhile did you did try that dns thing I told above?
> 
> Also instead of socks5 proxy you can use that http inbound proxy port 9080.
> 
> There's an advance setting in adguard which exposes dns filtering option while configuring proxy so you might wanna check that out too.
> 
> That dns exclamation mark thing used to happen with me a lot and even now sometimes but it doesn't happen once I use my setup.

Is it better to use http instead socks5 on sagernet when using with adguard?

**Comment by aliafshany** [comment]
> @aliafshany for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

@maxikuzmin 
I finally managed to get AdGuard to work with V2rayNG proxy mode. I just added HTTP mode instead of SOCKS5. It's been running great so far. Thank you for helping me here.
