### ISSUE TITLE
No user apps under app management

### ISSUE THREAD

**Issue by uaevuon** [AdguardTeam/AdguardForAndroid#4458]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 nightly 46

### Environment

```markdown
- OS: android 13
- Device: poco f3
- Firmware: miui 14.0.23.2.6
```

### Root access

- [X] Yes, I have it.

### Issue Details

 Settings - Filtering - Apps - App mamagement

### Expected Behavior

User apps and system apps both appear.

### Actual Behavior

Only system apps appears and no user apps

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_2023-02-13-16-25-26-710_com adguard android](https://user-images.githubusercontent.com/3542715/218396026-9e1fade4-dc17-474f-9487-8471d8553fb4.jpg)

</details>

**Comment by maxikuzmin** [comment]
@uaevuon I don't have this problem repeated. Could you please record a video of the screen and scroll down to "App management"?

**Comment by uaevuon** [comment]
I already uninstalled and re-installed. so impossible.
This issue is no longer available after I re-installed the latest nightly.

**Comment by maxikuzmin** [comment]
@uaevuon for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Comment by uaevuon** [comment]
https://user-images.githubusercontent.com/3542715/220605785-d29b94a7-a907-4f51-b7da-df880866ed76.mp4

@maxikuzmin Reproduced. Don't know steps, but sometimes it just happens.

Force closing in device settings can fix this issue.

**Comment by maxikuzmin** [comment]
@uaevuon to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@uaevuon any news?

**Comment by uaevuon** [comment]
Sorry. I totally forgot about this, after just downgrading to stable 3.6.54 release.
So closing.

**Comment by maxikuzmin** [comment]
@uaevuon if there are problems again in the future, please reopen the issue of this
