### ISSUE TITLE
Revanced patching hindered by adguard

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#4466]
Please refer to https://github.com/revanced/revanced-manager/issues/483#issuecomment-1428108241

**Comment by maxikuzmin** [comment]
@Bluscream looks like you've got the situation sorted out?
Are there any difficulties right now? If you still have any difficulties could you briefly describe?

**Comment by Bluscream** [comment]
Well, it looks like AG is blocking something that's required by the app

**Comment by maxikuzmin** [comment]
@Bluscream if I understand correctly, there is a sticking error for "creating working directory" in the Revanced manager application.
From the correspondence, I understand that there is a [theory](https://github.com/revanced/revanced-manager/issues/483#issuecomment-1428963372) that the problem is also related to the manager.

Also in that thread they wrote that "Adguard causes the connection corrupted but Revanced Manager need to handle the case when it can't get patches."

And you wrote about, "Adguard causes connection damage, but Revanced Manager should handle the case when it can't get a fix." and offered a solution for Revanced Manager [here](https://github.com/revanced/revanced-manager/issues/483#issuecomment-1429977487).

Nevertheless, it would be nice to have a look at your debug logs to see if there is anything we can do in this situation.
If I missed something, please let me know

**Comment by maxikuzmin** [comment]
@Bluscream any news?

**Comment by Bluscream** [comment]
Oh yeah, sorry. I forgot. Will drop them tonight

**Comment by maxikuzmin** [comment]
@Bluscream any news?

**Comment by Bluscream** [comment]
I will re-open this if it becomes relevant again. Sorry for the inconvinience
