### ISSUE TITLE
AdGuard Nightly (latest version) is crashing

### ISSUE THREAD

**Issue by luk6173** [AdguardTeam/AdguardForAndroid#4477]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.605

### Environment

```markdown
- OS: GrapheneOS
- Device: Google Pixel 6 Pro
- Firmware: https://grapheneos.org/releases#2023021000
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, EasyList Germany, EasyPrivacy, Peter Lowe's Blocklist, Fanboy's Enhanced Tracking List

### Issue Details

Steps to reproduce:
1. Open the App
2. Activate protection
3. After short time, App crashes and protection is not enabled

### Expected Behavior

Protection shoud be active. I'm using AdGuard Nightly from beginning and since AdGuard Nightly Version from 14. February 2023 I can't enable the protection in non WiFi Mode! After I connect to WiFi, protection can be enabled.

### Actual Behavior

Can't enable Protection in mobile data (LTE) mode, because App crashes

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@luk6173 Hi! Let's find the root of the issue. 
Do you have DNS protection module enabled? 
If so, could you disable it and try to reproduce the issue on cellular again? 

Also the debug logs from your device would help a lot. 
Please, follow the steps below to easily collect it and send: 

1. Open AdGuard and go to **Settings** tab -> **General**.
2. Tap the **Advanced** option.
3. Set the **Logging level** to **Debug**. It's desirable to close all background apps that don't concern the problem beforehand.
4. Reproduce the issue. Notice the exact time when it happened.
6. Use the **Export logs and system info** option to save the log file to the phone storage
7. Attach this file to the email and send it to devteam@adguard.com, mention the issue number `#4477` in the subject and the time when the issue was reproduced.

**Comment by pbmcmlxxi** [comment]
Also have the same issue, though it seems on mobile data only. On wifi it seems ok. I sent the logs via email - ticket number 724312.

**Comment by luk6173** [comment]
After disabling DNS Protection it is working on mobile data. I sent also the logs via E-Mail.

**Comment by Versty** [comment]
@pbmcmlxxi @luk6173 We are currently investigating both logs and looking for a cause.

**Comment by luk6173** [comment]
On Version 4.0.621 I can enable DNS Filtering on mobile data without app is crashing, issue seems to be fixed.
