### ISSUE TITLE
DNS protection break network internet connection

### ISSUE THREAD

**Issue by cv19985** [AdguardTeam/AdguardForAndroid#4515]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 nightly 63

### Environment

```markdown
- OS:Android 13
- Device:Samsung S23 (SM-S911B/DS)
- Firmware:S911BXXU1AWBM
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, Filter unblocking search ads and self-promotion

### Issue Details

Steps to reproduce:
1. Wifi On - Adguard DNS protection enabled - internet working
2. Wifi Off - Internet over carrier network - Adguard DNS protection enabled - No Internet
3. Then When I turn off DNS protection internet is ok!

Need to mention that I have tried disabling/enabling several options available in DNS protection or changing DNS protection, without success. Problem remains

### Expected Behavior

Should have internet access in both wifi and carrier network with DNS protection enabled

### Actual Behavior

Have internet with DNS protection enabled, only when using wifi

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by cv19985** [comment]
Furthermore, in order for me to check if there is a problem related to my device, I uninstalled nightly and installed stable version and DNS protection worked in both Wifi and Netwrok.
Updated again to nightly version and problem remains.

**Comment by XBadFellaX** [comment]
Same issue with latest nightly.

**Comment by XBadFellaX** [comment]
It started to work this morning with DNS turner on but after updating to AdGuard for Android 4.0 Nightly 65 internet stopped working with DNS on again. Once DNS is turned off Internet starts to work.

**Comment by floxigen** [comment]
Same issue I've to use android built in private dns

**Comment by XBadFellaX** [comment]
Anyone looking into this?

**Comment by cv19985** [comment]
3 days without response, I guess they are not interested in using any effort to this...  I went back to stable version for time being

**Comment by XBadFellaX** [comment]
They used pretty quick to respond but the response times have increased recently with late to no response for multiple days. I was thinking of switching to stable but hate resetting up my filters etc.

**Comment by XBadFellaX** [comment]
Okay, back to stable - this is the way.

**Comment by Versty** [comment]
@cv19985 Thank you for the bug report. We keep an eye on every feedback submitted, your input is important to us and helps improve the quality of the upcoming release of AdGuard for Android.
We currently have a lot of great changes in the process, so response times may be longer than usual. 

If you are interested in further participation in the nightly testing, we would like to take a look into your logs.
Could you install the latest nightly and collect the logs as described above? 

1. Open AdGuard and go to **Settings** tab -> **General**.
2. Tap the **Advanced** option.
3. Set the **Logging level** to **Debug**. It's desirable to close all background apps that don't concern the problem beforehand.
4. Reproduce the issue. Notice the exact time when it happened.
6. Use the **Export logs and system info** option to save the log file to the phone storage
7. Attach this file to the email and send it to devteam@adguard.com, mention the issue number `#4515` in the subject and the time when the issue was reproduced.

**Comment by cv19985** [comment]
Just sent you email with log. Did most of the sequence since I updated to nightly from stable. Problem still exist

**Comment by floxigen** [comment]
> I dont see many others reporting this, which is weird. I doubt it that no one is using DNS on latest nightly. I am also on a S23 ultra, and you are on S23 as you mentioned @cv19985, I am thinking if this could be related to S23 devices. Thanks for sending them the logs man.

I've the issue and using pixel 7 pro

**Comment by cv19985** [comment]
If you both try to send them your logs maybe it helps them to find out what is happening they can figure out a solution

**Comment by XBadFellaX** [comment]
Hi, @Versty any updates?

Just to mention this started to happen for me after you guys updated DnsLibs to 2.1.27. It was working fine before that.

**Comment by XBadFellaX** [comment]
Any updates on this?

**Comment by Versty** [comment]
@XBadFellaX The work is in progress, this issue will be fixed.

**Comment by cv19985** [comment]
Any update?

**Comment by cv19985** [comment]
Working good with latest nightly 76. Thanks!
