### ISSUE TITLE
De.dhl.paket not working correctly. Section Packbereich throws an error when connected via WiFi

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForAndroid#4548]
### Issue Details

https://play.google.com/store/apps/details?id=de.dhl.paket

Section Packbereich throws an error when connected via WiFi. On Mobile Data no problem. When AdGuard is disabled for this app it works as it should.

No blocked request shown in filtering log when pressing on Retry 

![Screenshot_20230329-150210](https://user-images.githubusercontent.com/34266271/228543880-a20ce4ae-94c4-4c5b-b720-ff3627ab17cc.png)

### Proposed solution

Exclude app from filtering.

**Comment by maxikuzmin** [comment]
@BlazDT sorry, but this app is only available in Germany. We do not have the opportunity to test it.

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@BlazDT unfortunately, we have no way to verify this, as this app is only for Germany.
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by BlazDT** [comment]
Sent log files. Btw instructions are not optimized for version 4 yet.

**Comment by BlazDT** [comment]
Sent again.

**Comment by BlazDT** [comment]
Yes, I am. Sent from my Gmail address.
26th April 2023 19:38 CET.

**Comment by BlazDT** [comment]
/
[adguard_logs_4.0.752_1704_193315 (1).zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11465815/adguard_logs_4.0.752_1704_193315.1.zip)

**Comment by maxikuzmin** [comment]
@BlazDT great! I'll come back a little later when we've looked at your logs.

**Comment by maxikuzmin** [comment]
@BlazDT try disabling DNS and try again. Is the problem still recurring? 
Also, if the problem is still recurring, try disabling each protection unit in turn, and see if the problem still recurs

**Comment by BlazDT** [comment]
Every module inactive, same error.
Also I do not use DNS blocking, only switching DNS.

**Comment by maxikuzmin** [comment]
@BlazDT thanks for the wait, we will need a little more time

**Comment by maxikuzmin** [comment]
@BlazDT in a future update we will add the app to the list of unfiltered apps. 
For now, as a temporary solution, you can add the package name to the "Excluded apps" list in the Low-level settings. 
You can find the name of the package by: Settings tab -> Filtering -> Apps -> Apps management -> click on the desired application -> context menu -> Statistics -> context menu -> Technical info
As I understand it, the name of the package is already specified in the issue name, but it is better to check this in the AdGuard settings.
This should help.

**Comment by BlazDT** [comment]
Package name: de.dhl.paket
Category: 7
Uid: 10227
Target SDK: 33
Version: 9.3.0.54 (c243253fbb)

**Comment by BlazDT** [comment]
As previously mentioned it works with exclusion.
