### ISSUE TITLE
System apps all grouped together in 4.0

### ISSUE THREAD

**Issue by meow-gh** [AdguardTeam/AdguardForAndroid#4573]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.85

### Environment

```markdown
- OS:13
- Device: samsung s23 ultra
- Firmware: latest 1st April patch
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open ag, settings apps 
2. Search for system
3. It will say eg 50 apps.
4. V4 can only manage all settings for all apps at once v3 could manage all settings per system app
5. This blocks system update and doesn't let me selectively block unblock between system update app and other samsung bloatware 
![Screenshot_20230412_023904_AdGuard](https://user-images.githubusercontent.com/130489904/231232215-823b1ed8-8cf3-43bb-940c-8d94c54ee4a6.jpg)
![Screenshot_20230412_023904_AdGuard](https://user-images.githubusercontent.com/130489904/231232251-006331b3-b56c-4416-8c5f-a3f105e6b153.jpg)
Q

### Expected Behavior

As per v3 . Must be able to manage individual system apps

### Actual Behavior

All system apps managed as one

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@meow-gh there are two "down" and "right" arrows to the right of System apps. The "right" arrow opens System apps, and the "down" arrow opens the list of System apps. Please try this

**Comment by jordanswrld94** [comment]
I second this. I cant change any settings for those apps that are grouped. There is also some other apps that are grouped that i cant change settings for:

![Screenshot_20230419_145812_AdGuard](https://user-images.githubusercontent.com/118186787/233186141-2c5b18ed-2560-4e62-9a90-ce7f8021aed5.jpg)
![Screenshot_20230419_145808_AdGuard](https://user-images.githubusercontent.com/118186787/233186163-984ef6e2-cc72-43a1-9b94-01f8e449dd6c.jpg)

**Comment by maxikuzmin** [comment]
@jordanswrld94 @meow-gh sorry for the long wait. The way it was in 3.6 was wrong. It was never possible to make a setting for a specific application, it was a bug. In version 4.0 it will not be possible to do customization for a specific application

**Comment by ameshkov** [comment]
@meow-gh unfortunately, Maxim is right, it is technically not possible to ungroup them.

Let me explain, on Android from a network filtering apps applications are identified not by their names, but by their identifiers (`uid`). That is, when you tell Android that you don't want to filter this or that app, you're actually telling it that you don't want to filter this or that `uid`. Now the problem is that several apps may share the same `uid` and you cannot distinguish them when doing the filtering.

Let's take an example, there are two apps: Download Manager and Downloads. They both share the same `uid`. AdGuard cannot determine which one's traffic it's receiving and so it detects everything as if it originates from the "Downloads" app, but never from the "Download Manager" app (or vice versa). If you disable filtering for one of them, you'll automatically disable filtering for both of them though it may not be clear from the UI.

So what was happening in v3.6 is that we didn't group them in the UI and allowed you to configure filtering for each app individually, but under the hood any setting change that you made to any app in the same group actually either applied to all other apps as well or not applied to any of them.

In v4.0 we tried to clarify this situation in the UI and it now shows how it looks like for our app under the hood.
