### ISSUE TITLE
Adguard is turned off when i turn on screen in morning 

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4574]
This has happened a couple days. I turn my screen on in the morning and adguard will be off. How do i go about capturing a bug log? I have the battery optimization turned off for adguard and set it to unrestricted battery use and have task manager setting disabled in adguard.  This happens on my galaxy s23 ultra and my galaxy z fold 3

**Comment by Versty** [comment]
@jordanswrld94 Hi! The issue may be caused by difficulties with the network or by battery saver. 
First of all, let's try to enable the `Restore VPN automatically` option in the low-level settings. *Settings -> General -> Advanced -> Low-level settings* 

The second option you can enable is the `Watchdog` feature. *Settings -> General -> Advanced* 

Please keep me posted on the results.

**Comment by jordanswrld94** [comment]
> @jordanswrld94 Hi! The issue may be caused by difficulties with the network or by battery saver. First of all, let's try to enable the `Restore VPN automatically` option in the low-level settings. _Settings -> General -> Advanced -> Low-level settings_
> 
> The second option you can enable is the `Watchdog` feature. _Settings -> General -> Advanced_
> 
> Please keep me posted on the results.

I have that option enabled but not watchdog. What should i set watchdog to. What does watchdog do?

**Comment by jordanswrld94** [comment]
I set the adguard watchdog to 10. Ill close this for now
