### ISSUE TITLE
Google app does not respect block by firewall issue

### ISSUE THREAD

**Issue by magnetUser** [AdguardTeam/AdguardForAndroid#4622]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 beta 1

### Environment

```markdown
- OS: Android 12
- Device: Samsung Galaxy Tab A8 (SM-X200)
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Full block of access to Internet via Firewall for browsers and apps.

### Expected Behavior

Full block of Internet on the device except for Adguard app.

### Actual Behavior

Google app has some access to the Internet. It could show what is the national celebration day with a flag today in our country.
How can it has access to this if firewall is on full block?

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by jordanswrld94** [comment]
It is probably cached?

**Comment by ameshkov** [comment]
@magnetUser check that ALL apps are routed through AdGuard.

By default we make a couple of exceptions for the compatibility reasons. We're going to review the list of exceptions in the future, but for now you can manually check it in Settings -> Filtering -> Apps

**Comment by magnetUser** [comment]
Hello!
Anyway to have "full block" of the Internet on the device?
I saw some apps have description "not routed via Adguard", why? Android limitation?

I just want Adguard to have full block of Internet option for the device

**Comment by ameshkov** [comment]
Try enabling routing for all these apps manually and see if there are  any issues. The compatibility issues I was mentioning are rather old and there's a chance everything will work okay.

**Comment by Versty** [comment]
@magnetUser Correct, if an application is not routed through AdGuard, internet usage will not be restricted by Firewall rules for that application. 

Some apps can be marked as "not routed through Adguard" by default in order to maintain stable work of these applications. However, if you don't need internet access for certain applications either way, you can manually enable routing for those applications without any harm. 
We also recommend that you enable the `Always-on VPN` option to protect applications from accessing the internet while AdGuard is restarting.
