### ISSUE TITLE
Pixel 6 Cell Connection Issue 

### ISSUE THREAD

**Issue by aruckeryarosh** [AdguardTeam/AdguardForAndroid#4753]
When using the Beta Update Channel on my Pixel 6 Google Fi connection, I found I wasn't able to use my cellular connection at all. Going back to the Release Update Channel fixed the issue, so I'm back there for now.

**Comment by Versty** [comment]
@aruckeryarosh Hi! 
Does the issue persist on the latest release version AdGuard for Android 4.0?

**Comment by aruckeryarosh** [comment]
Hi! Thanks for the ping. Yes, the problem persists with the newest version.
I have isolated the issue to the DNS monitoring, which I have to turn off
to make the app function.

**Comment by Versty** [comment]
@aruckeryarosh Let's see what went wrong. 

Could you collect the debug logs?

1. Open Settings -> General -> Turn Advanced mode on -> Advanced settings -> Turn Debug logs switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the settings -> Support -> Export logs;
4. System popup will be opened --> Choose "Mail" app;
5. Enter apple@adguard.com as a recipient;
6. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by Versty** [comment]
@aruckeryarosh Have you sent the logs?

**Comment by Versty** [comment]
@aruckeryarosh Closed due to lack of activity. 
Please reopen if needed.
