### ISSUE TITLE
Add LastPass app to the browsers list

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#476]
https://play.google.com/store/apps/details?id=com.lastpass.lpandroid

Please include LastPass as a browser for when you only filter browser traffic. Or add a way to define what apps are browsers.

DKX-523-80100

**Comment by TPS** [comment]
@evgeniy-ADG See https://github.com/AdguardTeam/AdguardForAndroid/issues/25#issuecomment-138887794 re:
>Or add a way to define what apps are browsers.

**Comment by ameshkov** [comment]
> Or add a way to define what apps are browsers.

Hehe, in this case anybody can define all their apps as browsers

**Comment by Revertron** [comment]
> consider including the app to the filtered apps as a browser
Why?

**Comment by TPS** [comment]
Much like #19 & #20, LastPass is designed as a custom browser shell over the OS's own browser component, because Android Chrome isn't extensible enough, so it acts as a full-fledged browser+.

**Comment by TPS** [comment]
Much like #19 & #20, [LastPass](https://play.google.com/store/apps/details?id=com.lastpass.lpandroid) is designed as a custom browser shell over the OS's WebView component, because Android Chrome isn't extensible enough, so it acts as a full-fledged browser:heavy_plus_sign:.

Even better answer:
> The LastPass Android App has a fully functioning browser within the app.

from [the official manual](https://helpdesk.lastpass.com/lastpass-mobile/lastpass-for-android/#h5), so also like #199.

**Comment by ameshkov** [comment]
@Revertron along with adding it to the browsers list we should find out which URLs are used for contacting LastPass servers and add these domains to the default https exclusions list.

**Comment by Revertron** [comment]
I see domains like `lastpass.com` and `pollserver.lastpass.com`.

**Comment by Revertron** [comment]
Added browser and domain.
