### ISSUE TITLE
Connection timed out in latest nightly 

### ISSUE THREAD

**Issue by psydvl** [AdguardTeam/AdguardForAndroid#4786]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1 Nightly 3

### Environment

```markdown
- OS: Android 13
- Device: Oneplus 11
- Firmware: (what is it?)
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard DNS filter, AdGuard Experimental filter, Filter unblocking search ads and self-promotion

### What Stealth Mode options do you have enabled?

Strip URLs of tracking parameters, Self-destruction of third-party cookies

### Issue Details

Steps to reproduce:
1. Install AdGuard 4.1 Nightly 
2. Open almost any app 

### Expected Behavior

Everything loads

### Actual Behavior

If app filtered - no answer or connection timed out 
If app not filtered, but operated through AdGuard - veeeery slow

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_2023-06-15-01-03-29-89_3aea4af51f236e4932235fdada7d1643](https://github.com/AdguardTeam/AdguardForAndroid/assets/43755002/dba255ec-b42d-408d-a1b3-08fb3894f5fa)

</details>

### Additional Information

What apps works in filtered mode: 
YouTube - videos loading without problems, text, previews - very slow 
Google Play - only text 

No other apps works in filtered mode

**Comment by maxikuzmin** [comment]
@psydvl hello!
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by psydvl** [comment]
Sorry for delay, was busy this weekend 
Close this in favor of https://github.com/AdguardTeam/AdguardForAndroid/issues/4808
