### ISSUE TITLE
User rule editor window size bug

### ISSUE THREAD

**Issue by Ali13798** [AdguardTeam/AdguardForAndroid#4836]
Hello, 

When the user role editor opens (protection screen > ad blocking > user rules > top right three dots > open rule editor), the screen size is not adjusted when the keyboard pops up. Instead, when you scroll to the bottom, part of the text is hidden behind the keyboard and can only be accessed by manually dragging the cursor down more. The downside is highlighting text becomes very difficult (for copying, deleting, etc). 

Versions:
Android 13 
Adguard 4.1.58 (4.1 nightly 11)

Related suggestion: 
Is it possible to add a feature to edit individual rules in a dedicated pop up by clicking the text of the item (and limit the toggle function to touching the checkbox area only) instead of having to find the rule in the editor? 

Thanks

**Comment by maxikuzmin** [comment]
@Ali13798 thanks for the long wait! To edit an individual rule from the list, you can swipe the rule to the right and you will get a dialog box with the option to change the rule.
We'll not limit the scope of the switch, this is a general concept for rules.
What about User rule editor, so when typing new rules, the bottom line goes up so that you see all the last text you typed above the keyboard.
If we are talking about a scenario where you go to the User rule editor, and tap on a random place in the list, you can use the text input slider to scroll down the list, just press your finger to display the text input slider and swipe down. Or you can tap on the last line of the User rule editor, and continue editing, the last line will also be displayed above the keyboard even when writing new rules

**Comment by maxikuzmin** [comment]
@Ali13798 what about the keyboard getting in the way when editing in User rule editor, we will fix this in the next updates

**Comment by Ali13798** [comment]
Oh that makes sense now. I did not even think to swipe on the individual items...  thank you for your assistance!

**Comment by artemiv4nov** [comment]
I have re-checked a possible UI bug in rule editor and it's done. The task is closed.
