### ISSUE TITLE
Trial length is announced as 14 days on the "Get free trial" screen 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4842]
### Version
AdGuard for Android 4.0

### Environment
Any compatible android version 

### Prerequisites 
- AdGuard is installed 
- Trial has not been actived on the device before

### Steps to reproduce 
1. Launch AdGuard 
2. Go to Settings tab -> License -> Get free trial 

### Expected behaviour 
Summary text is "Login or sign up to activate your 7-day free trial" 

### Actual behaviour
Summary text is "Login or sign up to activate your 14-day free trial"

**Comment by superlex** [comment]
@Versty

If I'm not wrong, License page should report "7-day free trial", not "14-day free trial" .

![err](https://github.com/AdguardTeam/AdguardForAndroid/assets/1375223/1b263c2a-a257-476b-a3dc-6ffc2e51fe4c)

**Steps to reproduce**

    Launch AdGuard
    Go to Settings tab -> License

**Expected behaviour**

Summary text is "7-day free trial"

**Actual behaviour**

Summary text is "14-day free trial"
