### ISSUE TITLE
Facebook app serve ads (video and sponsorised content even with adguard app)

### ISSUE THREAD

**Issue by Ever4engel** [AdguardTeam/AdguardForAndroid#4943]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2.24

### Environment

```markdown
- OS: Android 12
- Device: Samsung A31
- Firmware: ONE UI5
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Apps like Apps like Facebook in my phone still serve ads even if adguard is working and filters updated.

### Expected Behavior

removed ads (videos) removed while adguard app is runinig

### Actual Behavior

Facebook in my phone still serve ads even if adguard is working and filters updated.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Ever4engel** [comment]
PS: i used default built-in scripts in the app, if there a specific way to remove ads from facebook app imma wait for a reply.

**Comment by maxikuzmin** [comment]
@Ever4engel thanks for the long wait! Yes, you're right. This is a long time topic, it happens due to [ssl pinning](https://www.indusface.com/learning/what-is-ssl-pinning-a-quick-walk-through/). 
This has been previously discussed [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/472), you can research it. You need a rooted device to solve it, to disable ssl pinning.
For the moment, I'm closing this issue
