### ISSUE TITLE
Ispy blocking

### ISSUE THREAD

**Issue by TommyKing** [AdguardTeam/AdguardForAndroid#4956]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS:Android 13
- Device: Samsung galaxy Fold 5
- Firmware: One UI 5.1.1 security patch august 01 2023
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

No filters

### Issue Details

Steps to reproduce:
1. Turn on adguard without any protection
2. Try to navigate to http ://mikrotik .dnssilo .top : 8099
3. You will be face by connecting for a long time and try another browser or check if firewall didnt block your ports

The same happened with desktop

### Expected Behavior

The website will load

### Actual Behavior

See the image

### Screenshots

<details><summary>Screenshot 1:</summary>

When adguard turn on
![Screenshot_20230901_173418_Chrome](https://github.com/AdguardTeam/AdguardForAndroid/assets/6888937/0d2c13db-34d3-46e7-9615-dd95b4b88d79)

If adguard is disabled
![Screenshot_20230901_173625_Chrome](https://github.com/AdguardTeam/AdguardForAndroid/assets/6888937/6ec07597-f0aa-4c82-864f-7dff08774a5e)

</details>

**Comment by maxikuzmin** [comment]
@TommyKing I don't have the same problem with AdGuard enabled. As far as I understand, mikrotik sometimes has problems, because in my case I opened the site with AdGuard either the first time, or I had to refresh the page when it took a long time to load, and then everything loaded instantly. I checked in incognito mode, so it couldn't be cached. But more often than not, I had the page open the first time.
Does refreshing the page help you? Does the page always take a long time to load?

**Comment by TommyKing** [comment]
Here's the video of it

https://streamable.com/ofvtw2

There's no problem at all with mikrotik

**Comment by maxikuzmin** [comment]
@TommyKing sorry, on this link I see "This video has been archived and is not available to watch at this time."
Could you attach the video directly here, or email it to devteam@adguard.com?
Have you tried clearing your browser cache? Does this happen again in another browser?

**Comment by maxikuzmin** [comment]
@TommyKing any news?
