### ISSUE TITLE
Adguard crashes while filtering CM Private Browsing 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#50]
Details are here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/18#issuecomment-140397077

**Comment by TPS** [comment]
Thanks!  But since this issue isn't necessarily this narrow (as mentioned in the above reference), could this be retitled __Too many parallel requests to different servers cause AdGuard to restart__ or suchlike?  I think you'd find more helpful error reports if this issue isn't restricted artificially solely to CM Private Browsing, although I acknowledge it *is* the most consistent culprit! ;)

**Comment by Revertron** [comment]
I've tested the ["CM *un*private browsing"](https://play.google.com/store/apps/details?id=com.cleanmaster.security) for a while. And I couldn't not crash Adguard.
We will need logs of the crash if it is still actual.

**Comment by ameshkov** [comment]
@TPS  

> Too many parallel requests to different servers cause AdGuard to restart

I am pretty sure that's not our problem here.

@Revertron, have you tried it in Proxy+Manual mode? As it's what @TPS uses.

**Comment by TPS** [comment]
@ameshkov @Revertron I've used it in both proxy (x86 tablet with trial license) & VPN (ARM phone on Amazon beta-testing license) & I can still get each to crash with CM Private Browsing.  It seems to happen _less_ with other browsers with usually reliably crash-causing pages (Slashdot articles, &c), but not yet completely crash-proof.  I can't tell if that's due to APK updates since 1st reporting (good job, team! ☺:clap:)  or (_very_ unlikely, I admit) there's some difference from when I first reported in that I was completely unlicensed then — _perhaps_  there's some instability with that?

**Comment by ameshkov** [comment]
I though that it's easy to reproduce, but if it's not then maybe we'll need to see your log file (I hope there will be some errors logged there).

**Comment by TPS** [comment]
> I can't tell if that's due to APK updates since 1st reporting (good job, team! ☺:clap:) or (_very_ unlikely, I admit) there's some difference from when I first reported in that I was completely unlicensed then — _perhaps_ there's some instability with that?

In the interest of further testing this, I've let my trial subscription expire for my x86 tablet proxy-only setup.  I'll report back in a few days whether that makes any difference. ;)

**Comment by Revertron** [comment]
@ameshkov Yes, I've tested in all modes. No problems so far.

**Comment by TPS** [comment]
@Revertron I made sure to have a few crashes of this kind in [my recent log](https://github.com/AdguardTeam/AdguardForAndroid/issues/23#issuecomment-142201379).…  Did you see them?

**Comment by Revertron** [comment]
@TPS There are no crashes, but you can get logs from logcat, I've mentioned there. These logs would be more helpful.

**Comment by TPS** [comment]
Since I last logged, suddenly, I haven't had *any* crashes of this sort.  There've been any number of CM Security updates (which seem to have updated Private Browsing), which seem to have solve this on both the downloaded .115  & the Amazon .106 builds.  So I'd like to mark this ''Closed'' until further notice! ☺
