### ISSUE TITLE
Wrong default label for blocking mode: adblock style rules

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#5076]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3

### Environment

```markdown
- OS:android 13
- Device: galaxy s23 ultra
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Go to low level settings
3. Click custom ip address for adblock style rules, it will show default
4. Click reset low level settings
5. Adblock style rules will change to app default setting but without default label

### Expected Behavior

Adblock style rules show correct labeling for default

### Actual Behavior

Adblock style rules doesnt show default next to "refused"

**Comment by maxikuzmin** [comment]
@jordanswrld94 I don't have this problem recurring. Could you please check if this problem is still recurring? Could you please record a video of the screen and repeat these steps with debug logs?
Please send these files to [devteam@adguard.com](mailto:devteam@adguard.com)

**Comment by jordanswrld94** [comment]
It only occurs on nighly. Sent log and video

**Comment by maxikuzmin** [comment]
@jordanswrld94 right now you're running what version of nightly?

**Comment by jordanswrld94** [comment]
Latest

**Comment by maxikuzmin** [comment]
@jordanswrld94 I watched your video, thanks for the detailed report. The thing is that when you don't add an address in "Custom IP address", the default value is applied. That's what it says in the "Blocking mode for adblock-style rules" setting. But the default state for the "Blocking mode for adblock-style rules" setting is "REFUSED", which means that the bug is not present

The default value is "0.0.0.0"
