### ISSUE TITLE
 adguard ad blocker vpn keeps disconnecting 

### ISSUE THREAD

**Issue by olopezmo** [AdguardTeam/AdguardForAndroid#5083]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard v4.3 Nightly 34

### Environment

```markdown
- OS: Android 13
- Device: Samsung s23 ultra 
- Firmware:S918USQS1AWIF
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1.adguard ad blocker vpn turned on
2. leave app
3. ad block vpn running in background then it disconnects

### Expected Behavior

I expected ad blocking vpn to stay in background.

### Actual Behavior

Ad blocker VPN disconnected when running in background.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@olopezmo could you clarify, do you have only AdGuard installed or AdGuard VPN too? 
Do you have the VPN profile disabled but the protection continues to work (enabled)?

**Comment by maxikuzmin** [comment]
@olopezmo any news?

**Comment by maxikuzmin** [comment]
@olopezmo for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Comment by techiepk** [comment]
> @olopezmo for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

@maxikuzmin while I'm not OP, I've noticed this issue, and maybe a sister issue? I have a 1/1 repro for the random disconnections, still pretty random im afraid, but there seems to be a connection since im a samsung user too with an s22ultra, but I do have a 5/5 repro for an issue that may or may not be linked. 

STR: 
1) enable adguard. 
2) Swipe to go home/open any other app. 
3) while there, notice that the VPN icon is present and adguard notification icon indicates an active connection. 
4) Swipe down from the top of the screen to open notification center. 
5) Wait to see if adguard disconnects while asking you to disconnect 3rd party VPNs, and if not, Swipe down again to open quick toggles. 
6) this should force adguard to disconnect and reconnect. 

Environment:
OS: One UI 6.0
Based on: Android 14
Device: Samsung S22 Ultra
Connection: WIFI, Cellular
Adguard DNS: On with default filters. No additional filters added. 

PS: the random disconnect occurred once again when I was about to upload the video. And this issue has cost me quite a few failed transactions. One of the transactions was never refunded by the company and the bank involved. It's quite a harmful bug. I'd even go as far as saying it could be P1 if not P0.

Check the video for the repro. 

https://github.com/AdguardTeam/AdguardForAndroid/assets/54316635/099335f1-846d-4329-9842-6df44a8344d8

**Comment by RadoslawDeska** [comment]
I had similar issue with random dropping of VPN connection (VPN disappears and no filtering is in effect) quite fast after switching it on in the app. I solved the issue apparently:

In AdGuard v4.8 on Redmi 9T Android 12 open:
**Settings > General settings > Advanced > Low level settings:**
From default settings toggle these ON:

- Automatic restoration of VPN
- Reconfigure automatic proxy server after network change (no matter it might say it is not applied)
- Automatic restore VPN connection.

I am sorry if the names are not exactly as they might be in English version, I use Polish version.

For now I do not observe ANY dropouts in VPN connection, as far as I require the ads to be blocked (in other words: when I use my phone I don't see any problems now).
