### ISSUE TITLE
AdGuard fails to start automatically after rebooting the device with MIUI 13 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#5157]
### Version
AdGuard for Android 4.3.1

### Environment
Android 11, MIUI 13 

### Steps to reproduce 
1. Launch AdGuard and enable the protection 
2. Make sure that the `Launch AdGuard at system startup` option is enabled (Settings -> General)
3. Make sure that the battery optimization is disabled for AdGuard application in the system settings ([detailed instruction](https://adguard.com/kb/adguard-for-android/solving-problems/background-work/#miui-1208))
4. Reboot the device 

### Expected behaviour 
AdGuard is launched automatically and filters traffic 

### Actual behaviour
AdGuard fails to start automatically after rebooting the device 

### Additional info 
Autolaunch option works as expected on devices with MIUI 12

**Comment by loca-lhost** [comment]
How I got it to run automatically run at startup is to toggle always on vpn for adguard.

**Comment by Proxwian** [comment]
To allow AdGuard launch after system boot, you'll need to enable this feature in system settings by yourself for the app.

Sadly, for now universal method to show user this kind of system settings does not exist, because every manufacturer (XIAOMI, OPPO, Vivo, Asus, etc.) make their own implementation of auto-launch setting in different places of system or app setting, those state can't be read from application.
