### ISSUE TITLE
AG YouTube Player can't play Playlists or open YouTube URLs

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#5348]
### Issue Details

I'm surprised that the AdGuard YouTube Player doesn't support
- [x] <details><summary>directly opening YouTube links (when another YouTube app isn't set as default handler)</summary>
![AGa Open w.png](https://github.com/AdguardTeam/AdguardForAndroid/assets/185902/34bfe272-1176-41ab-8bad-91730d716a09)
</details>

- [ ] playlists, e.g., https://youtube.com/playlist?list=PLQuTEsyvhUo-KltlDqDhJDA6jqfYzAdoz

### Proposed solution

AGYTP should support each of the above

_P.S.:  I see a number of open AGYTP  issues from (@ this posting) 3ya.  Are they still current?_

**Comment by TPS** [comment]
@maxikuzmin Thanks, but your issue title change is incorrect.  This is actually the 2 related problems as laid out in the OP.

**Comment by TPS** [comment]
YouTube URLs can now be opened, but playlists still are a no-go, it seems?

**Comment by Versty** [comment]
@TPS Direct opening of YouTube links (when another YouTube app isn't set as default handler) will be available in AdGuard for Android 4.6 beta 1. 

Please create a separate feature request for playlists support (e.g., https://youtube.com/playlist?list=PLQuTEsyvhUo-KltlDqDhJDA6jqfYzAdoz) so that other users can vote in favor of your suggestion.

**Comment by TPS** [comment]
> Please create a separate feature request for playlists support (e.g., https://youtube.com/playlist?list=PLQuTEsyvhUo-KltlDqDhJDA6jqfYzAdoz) so that other users can vote in favor of your suggestion. 

@Versty #5393
