### ISSUE TITLE
Add SponsorBlock for Youtube in Adguard

### ISSUE THREAD

**Issue by biomednet** [AdguardTeam/AdguardForAndroid#5358]
### Issue Details

Ads on YouTube don't always come from Google. It often happens that advertising is inserted by channel owners and video creators. Such advertising cannot be removed by ordinary means, because it is an integral part of the video. You can solve the problem by automatically rewinding and skipping the advertising fragment.

Реклама на YouTube далеко не всегда исходит от Google. Часто бывает, что рекламу встраивают владельцы каналов и авторы видеороликов. Обычными средствами такая реклама не удаляется, потому что является неотъемлемой частью видео. Решить проблему можно автоматической перемоткой с пропуском рекламного фрагмента. 

### Proposed solution

I propose adding to Adguard the ability to skip ads embedded in the video itself. It also automatically skips titles, intros, and so on. In general, build SponsorBlock into it.

Предлагаю добавить в Adguard возможность пропускать рекламу, встроенную в само видео. А так же автоматическиф пропуск титров, вступлений и так далее. В общем, встроить в него SponsorBlock.

**Comment by SeriousHoax** [comment]
I don't know if AdGuard will natively include something like that, but you can use this userscript in AdGuard if you are not aware of it. I use it and it works well:
https://greasyfork.org/en/scripts/453320-simple-sponsor-skipper
BTW, even SponsorBlock is having a hard time with YouTube lately because of the changes made by YouTube:
https://x.com/SponsorBlock/status/1800835402666054072

**Comment by ESurina** [comment]
We will not add such functionality, it is very difficult to implement technically. You can try using the userscript that was mentioned above.
