### ISSUE TITLE
Block ads in gmail

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#541]
http://forum.xda-developers.com/showpost.php?p=66624570&postcount=1138

**Comment by TPS** [comment]
If IRC, there's a # of filters in EasyList, specifically tailored & regularly updated to handle the GMail ads.  Use them, possibly?

**Comment by ameshkov** [comment]
I am pretty sure ads in gmail app are native and have nothing to do with these from the web version.

**Comment by TPS** [comment]
Which is now duplicate?  This or https://github.com/AdguardTeam/AdguardFilters/issues/2222?

**Comment by ameshkov** [comment]
In fact it seems that this task is impossible to do right now.

Gmail uses a double-encryption, passes some encrypted content over https (ads inside). Nothing we can do about it now.

**Comment by uBlock-user** [comment]
Can't HTTPS filtering block ads from loading in the app ? I already have enabled HTTPS filtering and yet those ad banners appear the app in Social and Promotions section.

**Comment by TPS** [comment]
> Gmail uses a double-encryption, passes some encrypted content over https (ads inside).

When I read @ameshkov's [comment above](https://github.com/AdguardTeam/AdguardForAndroid/issues/541#issuecomment-222253613) months ago, I understood it to mean that, once the HTTPS was filtered, the contents had been _further_ encrypted in a manner that AG couldn't handle, so that's where @AdGuardTeam got stymied.

But that should make 1 feel a little better about GMail/GInbox security, right? 😝

**Comment by Bluscream** [comment]
One more reason to use another app :P

**Comment by ameshkov** [comment]
@uBlock-user @TPS is right. You see, ad blocking in apps is often tricky. Devs aren't limited to HTML/CSS as in case of websites, every time it is something new.

**Comment by uBlock-user** [comment]
@ameshkov Nevermind. As a workaround, I have hidden those aforementioned sections, that way I can avoid seeing those ads.
