### ISSUE TITLE
ru.sberbankmobile doesn't work in manual proxy mode

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#545]
ru.sberbankmobile - находится в списке исключений

При включенном adguard не запускается теперь Сбербанк онлайн приложение. Пишет — не удается создать защищенное подключение. Работает только если убрать в соединении настройку прокси localhost:8080. До обновления проблемы не было

"proxyMode" : true,
 "proxyPort" : 8080,
 "proxySetupManualMode" : true,

логи [тут](https://kb.adguard.com/staff/index.php?/Tickets/Ticket/View/285882)

**Comment by evgeniy-ADG** [comment]
s://github.com/AdguardTeam/AdguardForAndroid/issues/169

**Comment by Revertron** [comment]
I think the situation is like this:
We added `ru.sberbankmobile` to net exclusions.
But, in manual proxy mode all apps (that use standard HttpUrlConnection) go through proxy.
The sberbank app is connecting to our proxy, and, because we have no exclusion for domain or package name in ssl_exclusions (only net_exclusions) we are trying to MITM its connects.

There are two paths to correct such problems:
1. We add package names to 2 lists - net_exclusions and ssl_whitelist.
or
2. Before MITM'ing we check if that app is in net_exclusion (those apps will not be mitmed).

I personally prefer second path.

**Comment by ameshkov** [comment]
Second way it is

**Comment by Revertron** [comment]
Okay, I've made a fix, we need to check it.

**Comment by gshumihin** [comment]
Works fine for both VPN and manual Proxy.
