### ISSUE TITLE
Shizuku Support for adguard android 

### ISSUE THREAD

**Issue by Amr3ndr3ndra** [AdguardTeam/AdguardForAndroid#5471]
### Issue Details

Hi i am old user of adguard it's possible to add shizuku support for adguard I am not sure about it but it will be cool features!

### Proposed solution

Add shizuku support if possible 

#### Additional 
added by @Versty 

About Shizuku: https://shizuku.rikka.app
List of supported by Shizuku apps: https://github.com/timschneeb/awesome-shizuku

**Comment by Versty** [comment]
@Amr3ndr3ndra Hi! 
Could you tell us more about shizuku and what kind of support you are looking for?

**Comment by Amr3ndr3ndra** [comment]
Sorry for the late reply I want that adguard run on shizuku like it does run on root I know shizuku is different from root but if it possible then pls add support for shizuku it will be helpful user can connect to any third party vpn services like we do in root adguard!

**Comment by yazhamuthan-aruchamy** [comment]
Hi thanks we are also looking for the android like I am using samsung galaxy A35 5G with knox but the problem is it I use the adguard premium in there then I am not able to use the other VPN like Nordvpn even though I have subscribed for 2 years by using shizuku also it will be fine but that will be a good solution for other android but for us in samsung they will block this once they've found out, but this method of your will prevent from the root check and warranty trip and knox trip will be not available it is also an safety method

**Comment by AbhimanyuKhadse** [comment]
Shizuku support would be great....i agree

**Comment by TPS** [comment]
Duplicates https://github.com/AdguardTeam/AdguardForAndroid/issues/3461, which failed
