### ISSUE TITLE
adguard stops connecting to custom dns server

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardForAndroid#5493]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7.73

### Environment

- OS version:.android 14
- Device: galaxy s23 ultra

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-QUIC

### Issue Details

i dont know how to reproduce it just randomly stops connecting to my dns. i know when it stops because my custom nextdns blocklist isnt being used. and sites i had blocked dont block and also all logging for my device stops when looking at activity log on nextdns so i have to turn adguard on and off then it reconnects to my custom dns. hope someone can reproduce this issue.

### Actual Behavior

for it to keep filtering

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ESurina** [comment]
In order to troubleshoot this issue, we need to get your application logs.

Here's what we need you to do:

1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*.
2. Reproduce the problem, then remember the exact time when it happened.
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*.
4. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[android]` keyword and `ISSUE_NUMBER` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by jordansworld** [comment]
i think this has been fixed
