### ISSUE TITLE
Certificate Authority installed by an unknown third party

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardForAndroid#5500]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7.83

### Environment

- OS version: 14
- Device: zfold 4

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Custom DNS

### DNS protocol

None

### Issue Details

n/a

### Actual Behavior

keeps showing in notifications even after swiping it away. this message doesnt show on my galaxy s23 but does on the zfold oddly

### Screenshots

<details><summary>Screenshot 1</summary>

</details>
![Snapchat-607904830](https://github.com/user-attachments/assets/73223ade-c887-4ef7-9d9d-b10eecd8ed0b)

**Comment by jordansworld** [comment]
![Snapchat-607904830](https://github.com/user-attachments/assets/d66bcd43-1c79-45fe-928c-ccc9a646c6b2)

**Comment by maxikuzmin** [comment]
@jordansworld It looks like you installed the certificate incorrectly and something went wrong... Please try to re-install the certificate and it would be better to remove previous certificates: Settings -&gt; Security&amp;Privacy -&gt; More security &amp; privacy -&gt; Encryption &amp; credential -&gt; Trusted credential 
Clear User and User Credential

**Comment by jordansworld** [comment]
thanks will let u know if it comes back in a couple dags

**Comment by jordansworld** [comment]
i think it is fixed! thankyou. will reopen if i see it again

**Comment by maxikuzmin** [comment]
@jordansworld glad to hear it!

**Comment by RaXorX** [comment]
The certificates need to be installed WITH a security lock on. Swipe or None won't work. If the security lock is removed after installing the certs then the notification appears once again after a reboot. Enabling the lock screen once again won't fix that. The old certs will need to be removed and installed again after enabling the lock screen once again.

Edit: It's not an issue with Adguard but an Android system thing. This only triggers because of the certificates being in the user store. And because of the way certs now are transferred to the system store, they get copied instead of moved. Which leaves them in the user store as well as copying them in the system store as well. Which triggers the issue if the certs were installed without a lock on. If the module can just transfer the certificates by moving instead of copying, there'd be no such notification anymore.
