### ISSUE TITLE
Trackers from the DuckDuckGo converted into Custom List But some of them are not working

### ISSUE THREAD

**Issue by yazhamuthan-aruchamy** [AdguardTeam/AdguardForAndroid#5515]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I just added this and converted into My Own tracking List in AdGuard but when ever I have turned this on but still it was not blocking the trackers for the website. And some domain dares not working like YouTube, google, etc
Website

[newdata.txt](https://github.com/user-attachments/files/17798455/newdata.txt)
https://github.com/duckduckgo/tracker-blocklists/blob/main/web/v6/extension-mv3-tds.json

APP Tracking protection
[Trackerslist.txt](https://github.com/user-attachments/files/17798446/Trackerslist.txt)
https://github.com/duckduckgo/tracker-blocklists/blob/main/app/android-tds.json

Note : This was from the Official GitHub page of DuckDuckGo, I have mentioned the GitHub link for your reference
I need to add this to my AdGuard I am a Pro User but still Some trackers are not blocking, please help me with this.

**Comment by Versty** [comment]
@yazhamuthan-aruchamy Hi! 

The websites (YouTube, Google, etc) are not working because you are partially blocked them with rules from created filter list. You can handle specific cases by using modifiers as described in the article ["How to create your own ad filters"](https://adguard.com/kb/general/ad-filtering/create-own-filters/). 

Another solution here is to find the filter list that suits you best on https://filterlists.com, then add it to the AdGuard as custom filter.
