### ISSUE TITLE
Can't update profile/network services for Sprint through the Settings app.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#673]
"Adguard is blocking phones internal system update to update user data
profile/network services for Sprint through the Settings application.
I've tried adding white list exceptions and https exceptions for these
DNS captures found with Adaway while this update successfully passes
but attempts didn't allow Adguard to successfully pass these updates
to PRL and profile. I wish I could attach screenshots to these
feedback messages; that would make my report easier.
device-api.urbanairship.com udm.scorecardresearch.com
oma.ssprov.sprint.com ssl.google-analytics.com I suspect it's only the
last two but still couldn't connect to network and perform these
updates with these whitelisted or added to https filtering white list.
Maybe you can see the edits I made there but I can't exit this UI to
copy the changes made to it at the moment. Anyway, I can only update
these by turning off the Adguard protection."

id 1138191
Part of log with problem reproduced on 9.52 pm:

<details>
```
20:32:16.229 [pool-4-thread-2] INFO  com.adguard.android.e.c - Transparent proxy setup successful.
20:32:16.232 [pool-4-thread-2] INFO  com.adguard.android.ServiceManager - ServiceManager handle status event: STARTED
20:32:16.264 [pool-3-thread-1] INFO  com.adguard.filter.a.g - Host ru.sb.adtidy.org latency is 208 ms
20:32:16.336 [pool-4-thread-2] INFO  com.adguard.android.ServiceManager - Set vpnAutoPauseEnabled to true
20:32:16.339 [pool-4-thread-2] INFO  com.adguard.android.service.d - Creating AppConflictServiceImpl instance for com.adguard.android.AdguardApplication@15ed082
20:32:16.341 [pool-4-thread-2] INFO  com.adguard.android.e.c - Got app proxy config: host=127.0.0.1 port=8080 transparent
20:32:16.348 [pool-4-thread-2] INFO  com.adguard.android.service.aq - Updating widgets for STARTED protection
20:32:16.349 [pool-4-thread-2] INFO  com.adguard.android.e.a - Proxy service started successfully.
20:32:17.135 [pool-3-thread-1] INFO  com.adguard.filter.a.g - Host us.sb.adtidy.org latency is 98 ms
20:32:17.139 [pool-3-thread-1] INFO  com.adguard.filter.a.g - Fastest host is us.sb.adtidy.org with latency 98 ms
20:32:17.141 [pool-3-thread-1] INFO  com.adguard.filter.a.g - Schedule next detection after 3600 sec
20:34:13.618 [pool-4-thread-2] INFO  com.adguard.commons.utils.h - Initialize ReservedDomains object
20:34:13.744 [pool-4-thread-2] INFO  com.adguard.commons.utils.h - ReservedDomains object has been initialized
21:51:44.217 [main] INFO  com.adguard.android.service.f - Setting language en, System language is en, from resources en
21:51:44.315 [main] INFO  com.adguard.android.service.ah - Creating statistics service instance for com.adguard.android.AdguardApplication@15ed082
21:51:48.166 [main] INFO  com.adguard.android.service.f - Setting language en, System language is en, from resources en
21:51:48.174 [main] INFO  com.adguard.android.service.f - Setting language en, System language is en, from resources en
21:51:48.186 [main] INFO  com.adguard.android.service.f - Setting language en, System language is en, from resources en
21:51:57.052 [main] INFO  com.adguard.android.service.ak - Updating logging levels..
21:51:57.054 [main] INFO  com.adguard.android.service.ak - Logging levels updated successfully.
21:51:59.349 [main] DEBUG c.a.android.ui.SettingsActivity - Saved position and title!
21:51:59.380 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
21:52:04.759 [Thread-1542] DEBUG com.adguard.commons.b.s - TCP id=100106 address=/192.168.1.3:36752 Read 1169 bytes from socket channel
21:52:04.802 [pool-4-thread-31] DEBUG com.adguard.commons.b.m - Write 1169 bytes to /52.204.148.8
21:52:04.803 [pool-4-thread-31] DEBUG com.adguard.commons.b.r - TCP id=100106 Write 1169 bytes to socket channel
21:52:04.892 [Thread-1542] DEBUG com.adguard.commons.b.s - TCP id=100106 address=/52.204.148.8:443 Read 297 bytes from socket channel
21:52:04.905 [pool-4-thread-31] DEBUG com.adguard.commons.b.m - Write 297 bytes to /192.168.1.3
21:52:04.906 [pool-4-thread-31] DEBUG com.adguard.commons.b.r - TCP id=100106 Write 297 bytes to socket channel
21:52:12.001 [Thread-1469] DEBUG com.adguard.filter.proxy.n - Server has accepted new connection on port 52343
21:52:12.007 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 Server has accepted new tcp connection. Connection info=system /192.168.1.3:39939 /68.28.17.153:80 1000
21:52:12.010 [Thread-1542] DEBUG com.adguard.commons.b.s - TCP id=100160 address=/192.168.1.3:39939 Read 146 bytes from socket channel
21:52:12.010 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 Accepting incoming HTTP connection
21:52:12.010 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 Reading HTTP request
21:52:12.012 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 CONNECT oma.ssprov.sprint.com:443 HTTP/1.1
Proxy-Connection: close
User-Agent: samsung/SM-N910P samsung/1.2
Host: oma.ssprov.sprint.com:443


21:52:12.013 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 Processing CONNECT request to https://oma.ssprov.sprint.com:443
21:52:12.014 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.e - TCP id=100160 Connecting to remote endpoint oma.ssprov.sprint.com:443
21:52:12.015 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.e - TCP id=100160 Endpoint oma.ssprov.sprint.com:443 was not found in cache. Creating new endpoint.
21:52:12.089 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 Checking request with HttpRequestFilter
21:52:12.089 [pool-4-thread-70] DEBUG com.adguard.filter.a.f - TCP id=100160 Start filtering http request. With response = false
21:52:12.090 [pool-4-thread-70] DEBUG com.adguard.filter.a.f - TCP id=100160 Filtering http request
21:52:12.101 [pool-4-thread-70] DEBUG com.adguard.filter.a.f - TCP id=100160 No url filter rule found, exiting
21:52:12.103 [pool-4-thread-70] DEBUG com.adguard.commons.b.r - TCP id=100160 Write 87 bytes to socket channel
21:52:12.104 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 Handshake for CONNECT has been sent to client
21:52:12.105 [pool-4-thread-70] DEBUG c.a.android.filtering.filter.f - TCP id=100160 Connection system /192.168.1.3:39939 /68.28.17.153:80 1000 should not be filtered
21:52:12.106 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 Start tunneling data between local and remote endpoints
21:52:12.107 [Thread-1542] DEBUG com.adguard.commons.b.s - TCP id=100160 address=/192.168.1.3:39939 Read 162 bytes from socket channel
21:52:12.107 [pool-4-thread-70] DEBUG com.adguard.commons.b.m - Tunnelling data between /192.168.1.3 and /68.28.17.153
21:52:12.107 [pool-4-thread-70] DEBUG com.adguard.commons.b.m - Write 162 bytes to /68.28.17.153
21:52:12.108 [pool-4-thread-70] DEBUG com.adguard.commons.b.r - TCP id=100160 Write 162 bytes to socket channel
21:52:12.183 [Thread-1542] DEBUG com.adguard.commons.b.s - TCP id=100160 address=/68.28.17.153:80 Read 205 bytes from socket channel
21:52:12.192 [Thread-1542] DEBUG com.adguard.commons.b.s - TCP id=100160 address=/68.28.17.153:80 Closing TCP connection
21:52:12.209 [pool-4-thread-70] DEBUG com.adguard.commons.b.m - Write 205 bytes to /192.168.1.3
21:52:12.210 [pool-4-thread-70] DEBUG com.adguard.commons.b.r - TCP id=100160 Write 205 bytes to socket channel
21:52:12.213 [Thread-1542] DEBUG com.adguard.commons.b.s - TCP id=100160 address=/192.168.1.3:39939 Cannot read more from the socket: class java.net.SocketException recvfrom failed: ECONNRESET (Connection reset by peer)
21:52:12.261 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 Finished tunneling data
21:52:12.262 [pool-4-thread-70] DEBUG com.adguard.android.FilteringLog - TCP id=100160 CONNECT https://oma.ssprov.sprint.com:443 system 162 205
21:52:12.263 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.a - TCP id=100160 Closing HTTP connection
21:52:12.263 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.e - TCP id=100160 Closing proxy connection context
21:52:12.264 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.l - TCP id=100160 Closing TcpConnectionContext
21:52:12.264 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.l - TCP id=100160 TcpConnectionContext has been closed
21:52:12.264 [pool-4-thread-70] DEBUG com.adguard.filter.proxy.e - TCP id=100160 Proxy connection context has been closed
21:52:12.311 [pool-4-thread-28] DEBUG com.adguard.filter.proxy.a - TCP id=100140 Client has not sent any data to the connection. Connection info=com.trtf.blue /192.168.1.3:46484 /184.51.0.89:80 10183
21:52:12.314 [pool-4-thread-28] DEBUG com.adguard.filter.proxy.e - TCP id=100140 Connecting to remote endpoint 184.51.0.89:80
21:52:12.315 [pool-4-thread-28] DEBUG com.adguard.filter.proxy.e - TCP id=100140 Endpoint 184.51.0.89:80 was not found in cache. Creating new endpoint.
21:52:12.332 [pool-4-thread-28] DEBUG com.adguard.filter.proxy.a - TCP id=100140 Start tunneling data between local and remote endpoints
21:52:12.333 [pool-4-thread-28] DEBUG com.adguard.commons.b.m - Tunnelling data between /192.168.1.3 and /184.51.0.89
21:52:14.317 [pool-3-thread-1] DEBUG com.adguard.android.service.ah - Flushing statistics data
21:52:24.453 [main] INFO  com.adguard.android.service.ak - Updating logging levels..
21:52:24.456 [main] INFO  com.adguard.android.service.ak - Logging levels updated successfully.
21:52:33.608 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
21:54:05.296 [main] INFO  com.adguard.android.service.f - Setting language en, System language is en, from resources en
21:56:31.872 [main] INFO  com.adguard.android.service.ak - Start sending feedback message task
21:56:31.916 [main] INFO  com.adguard.android.service.ak - Submitted sending feedback message task
21:56:31.916 [pool-4-thread-53] INFO  com.adguard.android.service.s - Start task al execution
21:56:31.947 [pool-4-thread-53] INFO  com.adguard.android.service.i - Found 8 enabled filters
21:56:31.954 [pool-4-thread-53] INFO  com.adguard.android.service.n - Retrieving HTTPs filtering configuration
21:56:32.776 [pool-4-thread-53] INFO  com.adguard.android.service.n - HTTPs filtering is disabled or CA certificate is not installed
```
</details>

**Comment by ameshkov** [comment]
The thing is that request is going to an upstream proxy (which is located on 68.28.17.153:80). I guess something wrong happens with that request inside AG. And there goes the second issue, request is sent from the "system" app which cannot be simply excluded from the VPN.

I'll prepare a build that should fix the issue after the next beta release.

**Comment by ameshkov** [comment]
@vozersky ask user to try a new beta version and turn AG off for the "Android OS" app.

I mean go to "Apps & Statistics" -> find "Android OS" and uncheck the "Enabled" option there.

**Comment by vozersky** [comment]
Ok.

**Comment by samep** [comment]
Hi, I received the email to install latest beta, uncheck the enable option of Android OS at Settings/Apps and Statistics. I run the update profile and update PRL and get the same issues. The bug report above is mine. I've tried to white list Sprint outgoing URL but no change again. Did same uncheck enable you asked for on both system update apps and Sprint mobile installer but failed still. I went to Adguard General settings and unchecked the option to "block ads in all apps" and the system updates now work. Odd that rechecking the same block now allows the updates to pass through. I'll have to test more to see the toggle is required after each reboot or session.

**Comment by ameshkov** [comment]
@samep in theory unchecking "Enabled" for "Android OS" should have lead to the same result (no ad blocking for the `system` app).

Could you please record a log with "record everything" level with the following configuration:
1. "block ads in all apps" checked
2. "enabled" unchecked for the "Android OS" app

**Comment by samep** [comment]
Actually, I just got the data profile and PRL updates to successfully pass through the firewall by removing the same enable for the application "Samsung DM Service".

I've still got SystemUI, Android OS and the two update applications unchecked as well. But the block ads in all apps is now checked and was when the updates successfully ran just now.

Does this change the attempts with record everything logs you wish to be ran? I think I've provided those already but maybe not all with latest beta application were ran.

Progress. I happened to come up with the idea when I closed settings with smart manager. Recent applications showed Samsung DM Service as a recent app. Unchecked, ran and passed both updates just before finding your request. I was just about to respond to an older email with results.

**Comment by ameshkov** [comment]
> Does this change the attempts with record everything logs you wish to be ran? I think I've provided those already but maybe not all with latest beta application were ran.

In fact I'd like to get that new log nevertheless (with "Samsung DM Service" enabled). You see, the request I saw in the previous log was sent from a "system" app and it should have been enough to uncheck "Android OS" to fix the issue. The new log will help me understand if there is a bug in #732 implementation.

**Comment by samep** [comment]
Something was different this time. Only Android OS had the enable unchecked at Apps and Statistics.

First attempt at data profile update returned app is initializing. First attempt at PRL ran a long time but passed. Second attempt at data profile update passed.

See included log.

Note: I had left the whitelist set as before. Thought I'd mention that since that's how it was tested.

Sent from TypeApp



On Aug 8, 2016, 10:27 AM, at 10:27 AM, Andrey Meshkov <notifications@github.com> wrote:
>> Does this change the attempts with record everything logs you wish to
>be ran? I think I've provided those already but maybe not all with
>latest beta application were ran.
>
>In fact I'd like to get that new log nevertheless (with "Samsung DM
>Service" enabled). You see, the request I saw in the previous log was
>sent from a "system" app and it should have been enough to uncheck
>"Android OS" to fix the issue. The new log will help me understand if
>there is a bug in #732 implementation.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/AdguardTeam/AdguardForAndroid/issues/673#issuecomment-238309002

17:01:32.557 [pool-2-thread-1] INFO  com.adguard.android.service.q - Start executing job Status Job
17:01:32.696 [pool-2-thread-1] INFO  c.adguard.android.service.license.f - Store check result: null
17:01:32.700 [pool-2-thread-1] INFO  com.adguard.android.a.a - Sending license status request
17:01:34.023 [pool-2-thread-1] INFO  c.adguard.android.service.license.f - Backend check result: PREMIUM
17:01:34.030 [pool-2-thread-1] INFO  com.adguard.android.service.h - Set premium preferences to premium=true trial=false expiration=Wed Jun 17 01:54:36 PST 2116 key=HSK533XK
17:01:34.046 [pool-2-thread-1] INFO  com.adguard.android.service.q - Finished executing job Status Job
17:01:36.009 [main] INFO  com.adguard.android.service.ak - Updating logging levels..
17:01:36.010 [main] INFO  com.adguard.android.service.ak - Logging levels updated successfully.
17:01:38.942 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
17:02:15.142 [pool-2-thread-1] DEBUG com.adguard.android.service.ah - Flushing statistics data
17:02:24.637 [Thread-9159] DEBUG com.adguard.filter.proxy.n - Server has accepted new connection on port 37450
17:02:24.652 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Read 242 bytes from socket channel
17:02:24.653 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Server has accepted new tcp connection. Connection info=com.google.android.gsf.login /192.168.1.3:58952 /216.58.216.40:443 10012
17:02:24.654 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Accepting incoming SSL connection
17:02:24.656 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=100132 Received ClientHello:
TLS ClientHello
  Record Layer Version: 0x0301
  Version: 0x0303
  Server Name: ssl.google-analytics.com
  Random Bytes: 798df4d6708514ade39d21791d0e6e2d8921a5bb9f1855b0d3e032dcda27788f
  Cipher Suites:
    0xc02b, 0xc02c, 0xc02f, 0xc030, 0x009e, 0x009f, 0xc009, 0xc00a, 0xc013, 0xc014, 0x0033, 0x0039, 0xc007, 0xc011, 0x009c, 0x009d, 0x002f, 0x0035, 0x0005, 0x00ff
  Compression Methods: 0x0000
  Extensions:
      0x000b -> [3, 0, 1, 2]
      0x000a -> [0, 50, 0, 14, 0, 13, 0, 25, 0, 11, 0, 12, 0, 24, 0, 9, 0, 10, 0, 22, 0, 23, 0, 8, 0, 6, 0, 7, 0, 20, 0, 21, 0, 4, 0, 5, 0, 18, 0, 19, 0, 1, 0, 2, 0, 3, 0, 15, 0, 16, 0, 17]
      0x0000 -> [0, 27, 0, 0, 24, 115, 115, 108, 46, 103, 111, 111, 103, 108, 101, 45, 97, 110, 97, 108, 121, 116, 105, 99, 115, 46, 99, 111, 109]
      0x000d -> [0, 30, 6, 1, 6, 2, 6, 3, 5, 1, 5, 2, 5, 3, 4, 1, 4, 2, 4, 3, 3, 1, 3, 2, 3, 3, 2, 1, 2, 2, 2, 3]
      0x0010 -> [0, 9, 8, 104, 116, 116, 112, 47, 49, 46, 49]
      0x0023 -> []

17:02:24.661 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=100132 Reusing cached SSL properties
17:02:24.662 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=100132 Establishing an encrypted connection with a local client
17:02:24.663 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.q - TCP id=100132 Notify secure renegotiation true
17:02:24.664 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 54 bytes to socket channel
17:02:24.667 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 1204 bytes to socket channel
17:02:24.669 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 9 bytes to socket channel
17:02:24.716 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Read 190 bytes from socket channel
17:02:24.745 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 6 bytes to socket channel
17:02:24.750 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 45 bytes to socket channel
17:02:24.756 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Read 1330 bytes from socket channel
17:02:24.757 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Reading HTTP request
17:02:24.761 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 POST /batch HTTP/1.1
Content-Length: 1011
Accept-Encoding: gzip
Host: ssl.google-analytics.com
Content-Encoding: gzip
User-Agent: GoogleAnalytics/9.4.52 (Linux; U; Android 6.0.1; en-us; SM-N910P Build/MMB29M)
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded


17:02:24.763 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Processing POST request to http://ssl.google-analytics.com/batch
17:02:24.765 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Checking request with HttpRequestFilter
17:02:24.766 [pool-3-thread-46] DEBUG com.adguard.filter.a.f - TCP id=100132 Start filtering http request. With response = false
17:02:24.767 [pool-3-thread-46] DEBUG com.adguard.filter.a.f - TCP id=100132 Filtering http request
17:02:24.769 [pool-3-thread-46] DEBUG com.adguard.filter.a.f - TCP id=100132 Black list rule found: ||google-analytics.com^$empty
17:02:24.771 [pool-3-thread-46] DEBUG com.adguard.filter.a.f - TCP id=100132 Finished filtering http request. Rule found: ||google-analytics.com^$empty
17:02:24.774 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Request has been blocked
17:02:24.776 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 316 bytes to socket channel
17:02:24.779 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Read 31 bytes from socket channel
17:02:24.782 [pool-3-thread-46] DEBUG com.adguard.android.FilteringLog - TCP id=100132 POST ads=1 "https://ssl.google-analytics.com/batch" 500 0 13ms "null" "GoogleAnalytics/9.4.52 (Linux; U; Android 6.0.1; en-us; SM-N910P Build/MMB29M)" com.google.android.gsf.login 0 0
17:02:24.783 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Closing TCP connection
17:02:24.790 [pool-2-thread-1] DEBUG com.adguard.android.service.ah - Counting statistics event data
17:02:24.793 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Closing HTTP connection
17:02:24.795 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.n - TCP id=100132 Closing SSL proxy connection
17:02:24.796 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.q - TCP id=100132 Server alert raised. Level: warning, Description: close_notify close_notify(0)
17:02:24.797 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 31 bytes to socket channel
17:02:24.798 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.n - TCP id=100132 Closing proxy connection context
17:02:24.799 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.l - TCP id=100132 Closing TcpConnectionContext
17:02:24.799 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.l - TCP id=100132 TcpConnectionContext has been closed
17:02:24.800 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.n - TCP id=100132 Proxy connection context has been closed
17:03:15.141 [pool-2-thread-1] DEBUG com.adguard.android.service.ah - Flushing statistics data
17:03:22.924 [main] INFO  com.adguard.android.service.ak - Updating logging levels..
17:03:22.924 [main] INFO  com.adguard.android.service.ak - Logging levels updated successfully.
17:03:24.349 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
17:05:15.664 [main] INFO  com.adguard.android.service.h - Setting language en, System language is en, from resources en
17:05:22.992 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called

**Comment by ameshkov** [comment]
```
17:01:32.557 [pool-2-thread-1] INFO  com.adguard.android.service.q - Start executing job Status Job
17:01:32.696 [pool-2-thread-1] INFO  c.adguard.android.service.license.f - Store check result: null
17:01:32.700 [pool-2-thread-1] INFO  com.adguard.android.a.a - Sending license status request
17:01:34.023 [pool-2-thread-1] INFO  c.adguard.android.service.license.f - Backend check result: PREMIUM
17:01:34.030 [pool-2-thread-1] INFO  com.adguard.android.service.h - Set premium preferences to premium=true trial=false expiration=Wed Jun 17 01:54:36 PST 2116
17:01:34.046 [pool-2-thread-1] INFO  com.adguard.android.service.q - Finished executing job Status Job
17:01:36.009 [main] INFO  com.adguard.android.service.ak - Updating logging levels..
17:01:36.010 [main] INFO  com.adguard.android.service.ak - Logging levels updated successfully.
17:01:38.942 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
17:02:15.142 [pool-2-thread-1] DEBUG com.adguard.android.service.ah - Flushing statistics data
17:02:24.637 [Thread-9159] DEBUG com.adguard.filter.proxy.n - Server has accepted new connection on port 37450
17:02:24.652 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Read 242 bytes from socket channel
17:02:24.653 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Server has accepted new tcp connection. Connection info=com.google.android.gsf.login /192.168.1.3:58952 /216.58.216.40:443 10012
17:02:24.654 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Accepting incoming SSL connection
17:02:24.656 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=100132 Received ClientHello:
TLS ClientHello
  Record Layer Version: 0x0301
  Version: 0x0303
  Server Name: ssl.google-analytics.com
  Random Bytes: 798df4d6708514ade39d21791d0e6e2d8921a5bb9f1855b0d3e032dcda27788f
  Cipher Suites:
    0xc02b, 0xc02c, 0xc02f, 0xc030, 0x009e, 0x009f, 0xc009, 0xc00a, 0xc013, 0xc014, 0x0033, 0x0039, 0xc007, 0xc011, 0x009c, 0x009d, 0x002f, 0x0035, 0x0005, 0x00ff
  Compression Methods: 0x0000
  Extensions:
      0x000b -> [3, 0, 1, 2]
      0x000a -> [0, 50, 0, 14, 0, 13, 0, 25, 0, 11, 0, 12, 0, 24, 0, 9, 0, 10, 0, 22, 0, 23, 0, 8, 0, 6, 0, 7, 0, 20, 0, 21, 0, 4, 0, 5, 0, 18, 0, 19, 0, 1, 0, 2, 0, 3, 0, 15, 0, 16, 0, 17]
      0x0000 -> [0, 27, 0, 0, 24, 115, 115, 108, 46, 103, 111, 111, 103, 108, 101, 45, 97, 110, 97, 108, 121, 116, 105, 99, 115, 46, 99, 111, 109]
      0x000d -> [0, 30, 6, 1, 6, 2, 6, 3, 5, 1, 5, 2, 5, 3, 4, 1, 4, 2, 4, 3, 3, 1, 3, 2, 3, 3, 2, 1, 2, 2, 2, 3]
      0x0010 -> [0, 9, 8, 104, 116, 116, 112, 47, 49, 46, 49]
      0x0023 -> []

17:02:24.661 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=100132 Reusing cached SSL properties
17:02:24.662 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=100132 Establishing an encrypted connection with a local client
17:02:24.663 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.q - TCP id=100132 Notify secure renegotiation true
17:02:24.664 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 54 bytes to socket channel
17:02:24.667 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 1204 bytes to socket channel
17:02:24.669 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 9 bytes to socket channel
17:02:24.716 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Read 190 bytes from socket channel
17:02:24.745 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 6 bytes to socket channel
17:02:24.750 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 45 bytes to socket channel
17:02:24.756 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Read 1330 bytes from socket channel
17:02:24.757 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Reading HTTP request
17:02:24.761 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 POST /batch HTTP/1.1
Content-Length: 1011
Accept-Encoding: gzip
Host: ssl.google-analytics.com
Content-Encoding: gzip
User-Agent: GoogleAnalytics/9.4.52 (Linux; U; Android 6.0.1; en-us; SM-N910P Build/MMB29M)
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded


17:02:24.763 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Processing POST request to http://ssl.google-analytics.com/batch
17:02:24.765 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Checking request with HttpRequestFilter
17:02:24.766 [pool-3-thread-46] DEBUG com.adguard.filter.a.f - TCP id=100132 Start filtering http request. With response = false
17:02:24.767 [pool-3-thread-46] DEBUG com.adguard.filter.a.f - TCP id=100132 Filtering http request
17:02:24.769 [pool-3-thread-46] DEBUG com.adguard.filter.a.f - TCP id=100132 Black list rule found: ||google-analytics.com^$empty
17:02:24.771 [pool-3-thread-46] DEBUG com.adguard.filter.a.f - TCP id=100132 Finished filtering http request. Rule found: ||google-analytics.com^$empty
17:02:24.774 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Request has been blocked
17:02:24.776 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 316 bytes to socket channel
17:02:24.779 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Read 31 bytes from socket channel
17:02:24.782 [pool-3-thread-46] DEBUG com.adguard.android.FilteringLog - TCP id=100132 POST ads=1 "https://ssl.google-analytics.com/batch" 500 0 13ms "null" "GoogleAnalytics/9.4.52 (Linux; U; Android 6.0.1; en-us; SM-N910P Build/MMB29M)" com.google.android.gsf.login 0 0
17:02:24.783 [Thread-9244] DEBUG com.adguard.commons.b.s - TCP id=100132 address=/192.168.1.3:58952 Closing TCP connection
17:02:24.790 [pool-2-thread-1] DEBUG com.adguard.android.service.ah - Counting statistics event data
17:02:24.793 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.a - TCP id=100132 Closing HTTP connection
17:02:24.795 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.n - TCP id=100132 Closing SSL proxy connection
17:02:24.796 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.q - TCP id=100132 Server alert raised. Level: warning, Description: close_notify close_notify(0)
17:02:24.797 [pool-3-thread-46] DEBUG com.adguard.commons.b.r - TCP id=100132 Write 31 bytes to socket channel
17:02:24.798 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.n - TCP id=100132 Closing proxy connection context
17:02:24.799 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.l - TCP id=100132 Closing TcpConnectionContext
17:02:24.799 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.l - TCP id=100132 TcpConnectionContext has been closed
17:02:24.800 [pool-3-thread-46] DEBUG com.adguard.filter.proxy.ssl.n - TCP id=100132 Proxy connection context has been closed
17:03:15.141 [pool-2-thread-1] DEBUG com.adguard.android.service.ah - Flushing statistics data
17:03:22.924 [main] INFO  com.adguard.android.service.ak - Updating logging levels..
17:03:22.924 [main] INFO  com.adguard.android.service.ak - Logging levels updated successfully.
17:03:24.349 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
17:05:15.664 [main] INFO  com.adguard.android.service.h - Setting language en, System language is en, from resources en
17:05:22.992 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
```

**Comment by ameshkov** [comment]
@samep could you please send me the full log to email (am at adguard.com). This fragment is not very useful, just a lonely request to google analytics.

**Comment by ameshkov** [comment]
@samep `com.samsung.syncservice` app will be placed in the default exceptions list just in case. It should resolve this issue for all users.

**Comment by samep** [comment]
Thank you
