### ISSUE TITLE
Adguard kills itself on update

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#696]
Steps to reproduce:
1. Install previous AG version
2. Turn autostart OFF in AG settings
3. Install update and tap "Open" after it
4. AG won't finish loading and will simply close itself.

Here is what's going on:
```
22:44:14.819 [main] DEBUG c.a.a.receivers.PackageReceiver - Package receiver received intent Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.adguard.android flg=0x4000010 cmp=com.adguard.android/.receivers.PackageReceiver (has extras) }
22:44:14.819 [main] INFO  c.a.a.receivers.PackageReceiver - Package receiver received android.intent.action.PACKAGE_REPLACED for com.adguard.android
22:44:14.820 [main] DEBUG c.a.a.receivers.PackageReceiver - Handling our application update
22:44:14.824 [main] INFO  c.a.android.receivers.BaseReceiver - Autostart is disabled and service is not running, we should exit[/
```

I guess Adguard should not react that way on **its own update**. Maybe we should simply ignore it.

**Comment by TPS** [comment]
This actually might be correct, per the _user_.  Folks who have an app set to _not_ autostart wouldn't probably want it running just because of an update. I've several apps like this (_not_ AG! 😉) at which I'd be irritated if they remain running/active just because the dev decided to push an update.  (I even have those blocked in the AG firewall to give me some notice if they run unexpectedly.)

**Comment by ameshkov** [comment]
@TPS it will start anyway as receiver is registered in the app manifest.

The other way to fix all these autostart issues is remove all receivers from the app manifest and register them programmatically.

**Comment by nkartyshov** [comment]
done
