### ISSUE TITLE
App preview does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#973]
Description:
http://forum.xda-developers.com/showpost.php?p=70008707&postcount=1959

> As far as App preview messages, that's located under Settings > Google. When adblocking is enabled for Google Play Services, it says there is no internet connection. With adblocking disabled, it works properly and enables the feature for receiving Allo messages without requiring Allo to be installed.

**Comment by ameshkov** [comment]
@vozersky I need you to test it.

**Comment by vozersky** [comment]
tested on Samsung s7, nexus 5x and 6p
can't make App preview work  for Allo even without Adguard on device at all
(it's all enabled in settings -> google, etc.)

**Comment by ameshkov** [comment]
Huh, so we can't reproduce it right?

**Comment by vozersky** [comment]
Oh, I was able to test app preview now. 
You have to unregister your number in Allo completely, not just uninstall .

But it works fine for me, even with HTTPS filtering enabled, So no, unfortunately we can't reproduce such an issue. 

Could it be a specific filtering rule problem?

Screenshot:
<details>

![screenshot_20170213-135222 1](https://cloud.githubusercontent.com/assets/17472907/22881297/e41a0f4e-f1f6-11e6-9c3f-0c28e10685a4.png)

</details>

**Comment by vozersky** [comment]
It was not an Adguard issue, i guess.

**Comment by ameshkov** [comment]
Got a new bug report:
https://forum.xda-developers.com/showpost.php?p=72034241&postcount=2373

**Comment by carlylemiii** [comment]
Don't know if this is already obvious or helpful in the slightest, but I just want to add that I can access this with Adguard enabled IF I disable HTTPS filtering for Google Play services. Otherwise, it indeed says "No internet connection" for me, as well.

**Comment by ameshkov** [comment]
@carlylemiii this is important indeed, thank you!

So I reckon you can reproduce this issue? We cannot, so I'd be grateful if you assist us with it. 

To find out what's the reason of it, I need to take a look at Adguard's log with "record everything" level:
https://kb.adguard.com/en/android/solving-problems/log

**Comment by carlylemiii** [comment]
Can be found here:

https://my.pcloud.com/publink/show?code=XZ3HRGZpXYxROOwz54SLv15jyFgvXcrlISy

**Comment by ameshkov** [comment]
Found it, thank you very much!

Here's what happens.

GMS establishes a secure connection with `instantmessaging-pa.googleapis.com`. When HTTPS filtering is disabled, everything is simple -- AG transparently tunnels traffic for this domain.

When it is enabled, AG tries to handle it as if it was regular HTTP protocol, which is a mistake as it's not. AG tries to read request data, but the thing is that they use some custom protocol and data is actually pushed from the server side.

@carlylemiii could you please try adding `instantmessaging-pa.googleapis.com` and leave HTTPS filtering enabled for GPS app. Does it help?

**Comment by carlylemiii** [comment]
Confirmed that leaving HTTPS filtering on for GPS but adding that domain to
the HTTPS whitelist resolves the issue.

On Jun 14, 2017 6:40 AM, "Andrey Meshkov" <notifications@github.com> wrote:

Found it, thank you very much!

Here's what happens.

GMS establishes a secure connection with instantmessaging-pa.googleapis.com.
When HTTPS filtering is disabled, everything is simple -- AG transparently
tunnels traffic for this domain.

When it is enabled, AG tries to handle it as if it was regular HTTP
protocol, which is a mistake as it's not. AG tries to read request data,
but the thing is that they use some custom protocol and data is actually
pushed from the server side.

@carlylemiii <https://github.com/carlylemiii> could you please try adding
instantmessaging-pa.googleapis.com and leave HTTPS filtering enabled for
GPS app. Does it help?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardForAndroid/issues/973#issuecomment-308405715>,
or mute the thread

**Comment by ameshkov** [comment]
Resolved, review ID: AFA-CR-29

AG now checks ALPN TLS extension and does not filter HTTPS if the extension is present, but there's no supported application layer protocol found.
